### ISSUE TITLE
Recovering Older Versions of a File mistake in excercise 

### ISSUE THREAD

**Issue by novica** [swcarpentry/git-novice#1025]
### What is the problem?

Recovering Older Versions of a File exerciese in the lesson has an answer that does not correspond to the question. Correct solution says it is both 2 and 4 that are correct but explanation says that 2 is not what we want. My guess is this is just a number mismatch and the correct answer should either say 3 and 4 are correct or reorder the items in the question.

### Location of problem (optional)

https://swcarpentry.github.io/git-novice/instructor/05-history.html

**Comment by martinosorb** [comment]
Hi, thanks for catching this. I think the incorrect sentence is `Answer 2 uses HEAD to indicate the latest`. This does _not_ mean that that answer is wrong. It's explaining why there are two different solutions, however it is not true that it uses HEAD. It _is_true that answer 3 is not correct, for the reason explained there.

**Comment by novica** [comment]
so from:
> Answer 2 uses HEAD to indicate the latest.
to:
> Answer 2 uses the index (staging area) to restore the file to previous version.

But, the question is: Which commands below will let her recover the last _committed_ version .

```
$ git status
On branch main
Changes to be committed:
  (use "git restore --staged <file>..." to unstage)
        modified:   bla.txt

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
        modified:   bla.txt

$ git log
commit d3ed87b6d0d786c4c3a4617bfbab011ff7c05881 (HEAD -> main)
Author: novica <>
Date:   Wed Oct 23 14:56:47 2024 +0200

    1
$ git restore bla.txt 
$ git status
On branch main
Changes to be committed:
  (use "git restore --staged <file>..." to unstage)
        modified:   bla.txt
```

And git restore then gets me back to the staged state of the repo, not the commited. 

But maybe I am misunderstanding something.

**Comment by novica** [comment]
@martinosorb I think this got closed automatically because I misstyped the issue number in the PR for #1026 

Can you have a look?

**Comment by novica** [comment]
This seems to be resolved in the text.
