### ISSUE TITLE
Mistake in "guacamole.md contains a single line, which we can see by running:"

### ISSUE THREAD

**Issue by novica** [swcarpentry/git-novice#1026]
### What is the problem?

The output clearly shows three lines.

### Location of problem (optional)

https://swcarpentry.github.io/git-novice/instructor/04-changes.html

**Comment by martinosorb** [comment]
Thanks for noticing this. This happened due to the switch to markdown in the new "recipes" version of the lesson. Would you be willing to submit a pull request?

**Comment by novica** [comment]
Also, I am mistyping numbers all the time so apologies.
