### ISSUE TITLE
Improve file creation explanation

### ISSUE THREAD

**Issue by novica** [swcarpentry/git-novice#1027]
### How could the content be improved?

In https://swcarpentry.github.io/git-novice/instructor/04-changes.html the text goes as follows:
```
Let’s create a file called guacamole.md that contains the basic structure to have a recipe.
```

Then it says:

```
But remember, the bash command to create or edit a new file 
```

Then it justi gives the command 

```
$ nano guacamole.md
```

None of this makes clear the actually running the above *creates* a file as the introductory sentence states. In fact, it does not. It merely opens the nano buffer. The file will be created upon saving.

I think this needs to be reworded. Maybe the file can be created using `touch`. That would be one of the usual ways to create an empty file in `bash`. If not, then explain that the file is not there until saved.

The lesson goes on to run `ls` but running `ls` before saving will not show a file, and there is nothing in the text about saving.

### Which part of the content does your suggestion apply to?

https://swcarpentry.github.io/git-novice/instructor/04-changes.html

**Comment by martinosorb** [comment]
The prerequisites to this lesson state "In this lesson we use Git from the Unix Shell. Some previous experience with the shell is expected, but isn’t mandatory." My understanding of this is that it should mean it's the reader's responsibility to understand how nano works, as this is outside of the scope of this lesson. Also, it's hard to exit nano without saving, as it will ask first. So I'm guessing this won't be a problem in practice.

**Comment by novica** [comment]
I agree that if you have some knowledge of Shell this is not an issue. But I feel that this is not correct:

> But remember, the bash command to create or edit a new file will depend on the editor you choose (it might not be nano). 

The bash command for creating files is `touch`. 

So maybe:

> But remember, the steps to create create or edit a new file will depend on the editor you choose (it might not be nano). 

Also, to:

> 

I would add:

> Save the file and exit your editor. Next, let’s verify that the file was properly created by running the list command (ls):

**Comment by martinosorb** [comment]
Great, I would agree with these changes. Are you willing to submit a PR on this too?
