### ISSUE TITLE
Fix errors reported by tools/check.py

### ISSUE THREAD

**Issue by iglpdc** [swcarpentry/git-novice#119]

**Comment by iglpdc** [comment]
This will be fix after #114 and #124.

**Comment by iglpdc** [comment]
This is what would be left after #114:
```
ERROR: In /Users/ivan/Documents/swc/git-novice/discussion.md: Found callout box with unrecognized style 'callout'
ERROR: In /Users/ivan/Documents/swc/git-novice/index.md: The linked page reference.html#version-control exists, but the link text 'version control' does not match the (sub)title of that page, 'Reference'.
WARNING: 2 errors were encountered during validation. See log for details.
```

**Comment by r-gaia-cs** [comment]
About

> ERROR: In /Users/ivan/Documents/swc/git-novice/discussion.md: Found callout box with unrecognized style 'callout'

it can be solved with

~~~
$ git diff
diff --git a/tools/check.py b/tools/check.py
index 1c1fc59..106e91c 100755
--- a/tools/check.py
+++ b/tools/check.py
@@ -662,6 +662,7 @@ class DiscussionPageValidator(MarkdownValidator):
     DOC_HEADERS = {"layout": vh.is_str,
                    "title": vh.is_str,
                    "subtitle": vh.is_str}
+    CALLOUTS = {"callout": (None, 0, None)}
 
 
 # Associate lesson template names with validators. This list used by CLI.
~~~

Unfortunately it is related with https://github.com/swcarpentry/lesson-template/issues/199 that we will only close after 5.3.

And about

> ERROR: In /Users/ivan/Documents/swc/git-novice/index.md: The linked page reference.html#version-control exists, but the link text 'version control' does not match the (sub)title of that page, 'Reference'.

I just send a workaround for it (see https://github.com/swcarpentry/lesson-template/pull/239). I prefer to merge it just after 5.3.

**Comment by iglpdc** [comment]
No worries, @r-gaia-cs. I'll remove the 5.3 label.

**Comment by iglpdc** [comment]
#154 fixes the issue with:

> ERROR: In /Users/ivan/Documents/swc/git-novice/index.md: The linked page reference.html#version-control exists, but the link text 'version control' does not match the (sub)title of that page, 'Reference'.

**Comment by daisieh** [comment]
Is this resolved now?

**Comment by iglpdc** [comment]
The only error is now:
> ERROR: In /Users/ivan/swc/lessons/git-novice/discussion.md: Found callout box with unrecognized style 'callout'
WARNING: 1 errors were encountered during validation. See log for details.

which can be fixed as @rgaiacs mentions above, but it's related to the more complicated question of what should be in [discussion.md](https://github.com/swcarpentry/lesson-template/issues/199).

**Comment by iglpdc** [comment]
I'm closing this as the only error we have now should be fixed in the lesson-template repo.
