### ISSUE TITLE
Goal of GitHub Timestamp challenge?

### ISSUE THREAD

**Issue by douglatornell** [swcarpentry/git-novice#120]
What is the GitHub Timestamp challenge in `06_collab` trying to show?

It reads:
 > Create a repository on GitHub, clone it, add a file, push those changes to GitHub, and then look at the timestamp of the change on GitHub. How does GitHub record times, and why?

The "How does GitHub record times, and why?" implies to me that the learners will find that timestamps appear in UTC. Perhaps that was once the case, and internally in git and on GitHub it undoubtedly still is, but on GitHub I see times expressed as `<interval> ago` or a date for older commits, and when I hover over that I see a datetime expressed in my computer's local timezone.

Am I missing something, or has this question been eclipsed by UX improvements?

**Comment by iglpdc** [comment]
Hmm, good question. I've never seen it this way. I understand it as Git recording the time of the commit in your local computer, rather than the time the commit was pushed to Github (or wherever).

**Comment by douglatornell** [comment]
Okay, that interpretation of the question makes sense. That the commit timestamp is the same on GitHub and on my local computer isn't surprising or non-obvious to me now, but then I'm not looking at DVC and GutHub/Bitbucket with new learner eyes/brain.

Thanks for clearing this up for me.
