### ISSUE TITLE
Update the list contributors to this project

### ISSUE THREAD

**Issue by iglpdc** [swcarpentry/git-novice#122]
See #135.

**Comment by r-gaia-cs** [comment]
@iglpdc I my last pull request I update the [list of contributors](https://github.com/swcarpentry/git-novice/blob/gh-pages/AUTHORS). What need to be done is contact

~~~
arohl <a.rohl@curtin.edu.au>
daisie_local <daisieh@gmail.com>
dtrap <dtrapezoid@gmail.com>
efarsarakis <farsarakis@epcc.ed.ac.uk>
janepipistrelle <janepipistrelle@gmail.com>
ttimbers <tiffany.timbers@gmail.com>
~~~

to add the properly entry in https://github.com/swcarpentry/git-novice/blob/gh-pages/.mailmap.

@arohl, @daisieh, @janepipistrelle and @ttimbers can you let us know how you want to get the credits?

**Comment by iglpdc** [comment]
@r-gaia-cs OK, I've just sent an email to the rest of the people.

**Comment by wking** [comment]
On Sat, May 09, 2015 at 10:25:19AM -0700, Raniere Silva wrote:
> daisie_local <daisieh@gmail.com>

This should probably be merged with ‘Daisie Huang <daisieh@gmail.com>’
(e.g. from 2d03eb4, ab0e1ac31, …).

I didn't see obvious matches for the others in the output from:

  $ git shortlog -se

**Comment by iglpdc** [comment]
Should we also amend the commits?

**Comment by r-gaia-cs** [comment]
> Should we also amend the commits?

As you prefer.

**Comment by wking** [comment]
On Sat, May 09, 2015 at 02:31:23PM -0700, Raniere Silva wrote:
> > Should we also amend the commits?
> 
> As you prefer.

If you mean “rewrite history to use the canonical author name in the
historical commit”, then I'm pretty sure you shouldn't.  Adding
entries to .mailmap will have a very similar effect, and it avoids
rewriting the public history.  If you *do* rewrite your master branch,
life gets awkward for anyone downstream [1].

[1]: http://git-scm.com/docs/git-rebase#_recovering_from_upstream_rebase

**Comment by iglpdc** [comment]
Oh, thanks, @wking. I didn't know that reseting the author's name was a rewriting of history.

**Comment by wking** [comment]
On Sat, May 09, 2015 at 03:57:29PM -0700, Ivan Gonzalez wrote:
> Oh, thanks, @wking. I didn't know that reseting the author's name
> was a rewriting of history.

Git is nice, because *everything* in each object goes into that
object's hash [1].  Otherwise it would be hard to figure out if commit
d6f8adac2223f39e1d504412b25b59628e9517a6 meant the one written by
daisie_local or the one by Daisie Huang ;).  Since changing the author
changes the hash, a similar commit by Daisie Huang would have a
different hash, so it would get an unambiguous, unique identifier.

[1]: http://en.wikipedia.org/wiki/Merkle_tree

**Comment by iglpdc** [comment]
Hey, @klee8, how do you wanna get cited for your contribution to git-novice? We don't have your full name and the email we have is not working anymore :-)

(Sorry for the noise for the rest of you.)

**Comment by iglpdc** [comment]
El 09/05/2015, a las 21:33, "W. Trevor King" <notifications@github.com> escribió:

> [1]: http://en.wikipedia.org/wiki/Merkle_tree
> 

I see. Thanks for the link!

**Comment by janepipistrelle** [comment]
I have no idea how these things work, as that was the first time I'd done a
PR!

**Comment by iglpdc** [comment]
@janepipistrelle We just need your full name and email to put in the new [AUTHORS](https://github.com/swcarpentry/git-novice/blob/gh-pages/AUTHORS) file, so you get credit for your work. We're doing a new release that will have a DOI, so it can be cited properly, and we're trying to get everyone's name right.

For you, we only have your GitHub nickname:

`janepipistrelle <janepipistrelle@gmail.com>`
