### ISSUE TITLE
Change deprecated {.input} to {.bash}

### ISSUE THREAD

**Issue by iglpdc** [swcarpentry/git-novice#123]
We should use {.bash} because will make easy if we want to add the prompt by CSS.

{.input} was used in bc.

**Comment by iglpdc** [comment]
Probably, this script makes it eaiser: https://gist.github.com/iglpdc/7686754

**Comment by r-gaia-cs** [comment]
@iglpdc I think that we can close this:

$ git rev-parse HEAD
ff79f5e499affcc2a532cc3e02a595ad955d41a9
$ grep input *.md
~~~

**Comment by iglpdc** [comment]
Yes, I just checked (right before sending an email asking for someone to do it...). Closing.
