### ISSUE TITLE
Cannot make preview: tools/filters/blockquote2div.py not found in path

### ISSUE THREAD

**Issue by petebachant** [swcarpentry/git-novice#14]
I am not able to build a local version of the site using `make preview`. I am running Anaconda (Python 3.4) on Linux, and have installed dependencies in `requirements.txt` via pip. 

```bash
$ make preview
pandoc -s -t html \
	--template=_layouts/page \
	--filter=tools/filters/blockquote2div.py \
	--filter=tools/filters/id4glossary.py \
	-Vheader="$(cat _includes/header.html)" -Vbanner="$(cat _includes/banner.html)" -Vfooter="$(cat _includes/footer.html)" -Vjavascript="$(cat _includes/javascript.html)" \
	-o 01-backup.html 01-backup.md
pandoc: Error running filter tools/filters/blockquote2div.py
tools/filters/blockquote2div.py not found in path
make: *** [01-backup.html] Error 83
```

**Comment by gvwilson** [comment]
Hi @petebachant - can you please tell us which version of Pandoc you have? (pandoc --version)

**Comment by petebachant** [comment]
My pandoc is version 1.12.2.1, the latest in the Ubuntu repositories.

**Comment by r-gaia-cs** [comment]
@petebachant Could you give us the output to

~~~
$ env which python
~~~

and

~~~
$ which pip
~~~

**Comment by petebachant** [comment]
Sure, `/home/pete/anaconda3/bin/python` and `/home/pete/anaconda3/bin/pip`.

**Comment by petebachant** [comment]
I got this working. For some reason, I set Git `core.autocrlf = true`, which must have checked out the files with Windows line endings (I am running a Linux virtual machine with a Windows host). Thanks for your help!

**Comment by gvwilson** [comment]
Thanks Pete - can you please send a PR against the FAQ for 
lesson-template explaining the symptom, cause, and cure?  I'm sure this 
will come up again.
Thanks
reg
