### ISSUE TITLE
Make a new figure for "Conflicts" topic

### ISSUE THREAD

**Issue by iglpdc** [swcarpentry/git-novice#141]
After #97, all the figures have the same style, but `fig/conflict.svg`. I'd like to change it to look more like the rest.

@daisieh, could you make it? There ones you made are pretty nice.

**Comment by daisieh** [comment]
Somehow I never got the notification on this! Yes, I can do this.

**Comment by iglpdc** [comment]
That be great! thanks @daisieh.

**Comment by daisieh** [comment]
Fixed in #245.
