### ISSUE TITLE
Proposal: add a capstone project

### ISSUE THREAD

**Issue by chendaniely** [swcarpentry/git-novice#148]
Lately I've taken time after lunch for students to work on a github project for them to practice all the commands.  I type the instructions on the screen with the diagram for reference.  The instructions are below:

    Pair up, into person A and person B
    Part I
    1. person-A fork person-B's repository
    2. person-A clone the forked repository to your local computer
    3. person-A make a change to the repository
    4. person-A push the change to your github account
    5. person-A create a pull request to person-B
    5.1. collaborate
    6. person-B accept the change    

    Part II
    1. person-B make a new change after your pull request
    2. person-A add person-B's repository as a new remote (upstream)
    	`git remote add upstream GIT_URL`
    3. person-A get the new changes from person-B
    4. person-A update your github fork so it is the same as Person-B    

    part III
    1. switch roles.    

Would we be able to add this to the git lesson?

**Comment by chendaniely** [comment]
Probably needs a discussion and enhancement tag

**Comment by iglpdc** [comment]
Yes! This is something I've been musing about for long now. These are my thoughts.

The current collaboration part of the lesson is built around making the other person a collaborator on GitHub. I think this is a good default:

- It's shorter and simpler than the PR route.
- It's better suited for a small team of researchers working in the same group or department.
- It's the only way to do it if you're taking the lesson by yourself, as you cannot fork your own repos. [1]

However, many of us teach the PR version that @chendaniely mentions. (I do it if I have time). The PR version allows the role-playing that many have reported successful and fun for the students [2].

My idea was to add a script (not the computer type, but the movie type) with the instructions each partners has to enter. I was thinking in using roles for this, so people choose one role (Dracula and Wolfman or whatever) and follow the script from there. 

The script wouldn't be in the lesson as a topic, but as a separate material linked to the instructor guide. If the workshops teaches PRs, instructors just pull the script, distribute it to the learners, and choose roles for everyone (including themselves).

The advantages of this is that you are not tied to teaching PRs and can decide on the flight. The second advantage is that people (including the instructors) won't get lost. Without clear instructions, the room  turns into a mess pretty quickly.

Regarding your particular set of instructions, I would mix the two roles more if possible, so nobody is waiting idle for long.

[1] You could send you a PR to yourself, but this requires different instructions.
[2] http://swcarpentry.github.io/git-novice/instructors.html

**Comment by chendaniely** [comment]
I just saw the other issue that's related: #23

I'm not sure how people go about sending PR's to themselves.  The last time I did that was with @iglpdc at the Harvard workshop, and it required a lot of "please don't type what i'm typing" because I was creating branches.

Adding people as collaborators may be better than PR's since that's probably the model many labs will be using, but the PR way is the 'open science' way.  We can mention adding collaborators, and that will be the same as working on your own repository. By showing them PRs we expose them to something else.

This is one of those cases where just showing it to them once, will make things easier in the future.  People will no doubt see the words `origin` and `upstream` when they start googling for help.

**Comment by daisieh** [comment]
For the UBC and SFU workshops, @ttimbers and I taught some extra lessons that could act as a capstone: 

https://github.com/swcarpentry/git-novice/blob/55e99b82483b7dc0ecc08bb71635220ace47d73a/08-role-play.md
https://github.com/swcarpentry/git-novice/blob/55e99b82483b7dc0ecc08bb71635220ace47d73a/09-forking.md

The advantage of doing it this way is that you really see the problems with merging and collaborating in the same repo, and then you teach forking and have everyone submit PRs that show up like magic in the master repo! Ideally, we'd like that capstone repo to be something that the instructor makes to hold, say, the results of the earlier python/R/shell lessons.
