### ISSUE TITLE
What changes should we make for our 5.4 release?

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/git-novice#155]
Please use this issue for discussion of changes we should make by mid-August 2015.

**Comment by chendaniely** [comment]
add a capstone project #148 
However this typically means (when I teach) spending a half hour after lunch to complete.
But I think it's important for students to go through the entire process on his/her own

**Comment by gvwilson** [comment]
And take out what to make room?

**Comment by chendaniely** [comment]
It may change between different workshops, but many times the people we are teaching do not have an immediate use for SQL.  So not covering certain topics in SQL may be 'acceptable'.
I would suggest going through all of SQL upto aggregation and then do the last lesson on programming with SQL. "Creating and Modifying Data" can be done if there's time.

I typically see instructors explain "Data Hygiene" throughout the lesson

**Comment by gvwilson** [comment]
So if I understand correctly, you're suggesting that we subtract time 
from SQL to make room for more Git?

**Comment by chendaniely** [comment]
Yep.  Also there are some workshops where SQL isn't covered, just more programming in language x.  So SQL seems like an appropriate place to cut.  Again, if the host explicitly ask for more SQL because they use databases a lot, then don't cut it.

**Comment by iglpdc** [comment]
At risk to stir up old discussions, I'd like to move the open science section out of here. I taught Git last week and, again, I had no time to do cover open science. In fact, it has been the case in all the workshops I've been. I'd like to have the open science into its own, expanded lesson, and open the discussion if we want to add it to our core (taking the space left by SQL) or offer it as an option.

The other thing could be have a separated cheatsheet, maybe with diagrams, with the commands covered in the lesson, as @douglatornell mentioned here [2].

Finally, decide on the format of the "longish" discussion items, e.g. how to write a good commit message  (see the conversation around here [3]) 

[1] https://github.com/swcarpentry/site/issues/917
[2] https://github.com/swcarpentry/lesson-template/issues/242#issuecomment-105663867
[3] https://github.com/swcarpentry/git-novice/issues/71#issuecomment-81821132

**Comment by daisieh** [comment]
I've never tried to teach the open science section; I'd agree with moving it out of here as well.

**Comment by psteinb** [comment]
+1
Neither does it fit, nor is it cover at a level that the topic deserves AFAIK

**Comment by iglpdc** [comment]
Closing as this doesn't apply anymore.
