### ISSUE TITLE
Have students give planets repo a unique name

### ISSUE THREAD

**Issue by maneesha** [swcarpentry/git-novice#158]
After the git workshop I taught, I think it was confusing for students to pull a classmate's repo that was named `planets` but was different from their own `planets` repo. 

This may be fixed if we have students name their repos something unique... i.e., `planets-username` or something like that.  It would involve fixing references to `planets` throughout the lesson, including some of the images.  If others think this would help I can edit all the text and images I can work on this... just don't want to start unless there is consensus that this would work.

**Comment by iglpdc** [comment]
I agree this is confusing. I'm not even sure if all OS will handle the situation in the same way (Mac OS adds a "1" to the folder name".)

As you say, the best solution is to add their partner's username (they need it to clone) to the folder name when cloning:

~~~
git clone https://github.com/vlad/planets.git vlad-planets
~~~

**Comment by Ry4an** [comment]
WIP at #216
