### ISSUE TITLE
Remove references to sections that don't exist

### ISSUE THREAD

**Issue by maneesha** [swcarpentry/git-novice#159]
In the git lesson, in the Remotes in GitHub section, there are some references to sections that don't exist (perhaps they did in earlier versions of the curriculum? or am I missing something?)

> Most programmers use hosting services like GitHub, BitBucket or GitLab to hold those master copies; we’ll explore the pros and cons of this in the final section of this lesson.

This comparison isn't actually in the final section of this lesson.

> You may see a -u option used with git push in some documentation. It is related to concepts we cover in our intermediate lesson, and can safely be ignored for now.

Is there an intermediate lesson?  If not can we just say it's an intermediate concept that can be safely ignored for now?

If others agree I can make these changes.

**Comment by iglpdc** [comment]
> In the git lesson, in the Remotes in GitHub section, there are some references to sections that don't exist (perhaps they did in earlier versions of the curriculum? or am I missing something?)

This is discussed in the open science part of the lesson [1]. 

>     Is there an intermediate lesson? If not can we just say it's an intermediate concept that can be safely ignored for now?

Yes, there is one, but not sure where lives anymore. I wouldn't mind leaving it as is, but maybe better to change "intermediate lesson" to "a more advanced/intermediate concept"

[1] https://github.com/swcarpentry/git-novice/blob/gh-pages/12-hosting.md

**Comment by maneesha** [comment]
Bitbucket & Sourceforge are mentioned in the hosting section but specific pros/cons are not actually addressed. Gitlab isn't  mentioned at all.

**Comment by iglpdc** [comment]
Fixed by #218
