### ISSUE TITLE
git in RStudio

### ISSUE THREAD

**Issue by noamross** [swcarpentry/git-novice#162]
In workshops teaching R through RStudio, it's becoming a more common pattern to teach this git command line lesson, then follow it with a short lesson demonstrating the git GUI interface in RStudio.  It would be useful to have this "transition" lesson written up with screenshots.  While RStudio isn't quite a full-featured git GUI it is the environment many students will use.

This could also live in the r-novice repositories.

Here are some lessons designed for teaching git only through RStudio which could be adapted:

1. https://github.com/microbialinformatics/assignment01
2. https://jennybc.github.io/2014-05-12-ubc/ubc-r/session03_git.html

There are a couple of technical issues for this:

1.  RStudio may need to be pointed to the git executable, especially on Windows machines. Instructions: https://stat545-ubc.github.io/git03_rstudio-meet-git.html 
2.  Remote tracking must be set up on the repository using the `-u` flag, e.g. `git push -u origin master`.
3.  If students want github passwords to be stored, this will need to be activated.  This may not be necessary during the workshop but one could point them to a resource showing how for later: https://stat545-ubc.github.io/git06_credential-caching.html

**Comment by iglpdc** [comment]
I agree it could be a good thing to have some extra topics on how to use git from the interfaces provided by other tools. These materials e.g. "Using Git with Rstudio" or "Using Git with Matlab" (which has also a similar GUI for Git), could be linked in the main lesson, but not be part of it, so instructors and solo learners can follow the link if the are using RStudio or Matlab.

**Comment by iglpdc** [comment]
I'm closing this after merging #183.
