### ISSUE TITLE
`gedit -s` not working properly

### ISSUE THREAD

**Issue by clois** [swcarpentry/git-novice#174]
I set up gedit to be the default editor with the -s option, but it is not working

This is what I get when I do `gedit --version`:
`gedit - Version 2.28.4`

**Comment by jiffyclub** [comment]
[This post](https://fabianschuiki.wordpress.com/2012/05/20/use-gedit-as-git-editor/) and [this post](http://stackoverflow.com/a/19457491/1405710) suggest that you need a newer version of gedit (3.x) and `gedit -w -s`.

**Comment by iglpdc** [comment]
Thanks @clois and @jiffyclub. I fixed the lesson and added a comment to the [configuration problems wiki](https://github.com/swcarpentry/workshop-template/wiki/Configuration-Problems-and-Solutions).
