### ISSUE TITLE
"Remotes in GitHub" claims to cover cloning from github but does not do so.

### ISSUE THREAD

**Issue by dham** [swcarpentry/git-novice#176]
One of the learning objectives of this lesson is "Clone a remote repository."

However the lesson does not actually cover cloning, it only covers adding a remote to an existing repo.

**Comment by daisieh** [comment]
We cover this in the next lesson; we should just move this objective there.

**Comment by iglpdc** [comment]
This is fixed: we mention "cloning" only on [08-collab.md](https://github.com/swcarpentry/git-novice/blob/gh-pages/08-collab.md). Closing.
