### ISSUE TITLE
Add some diagrams like these

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/git-novice#178]
https://marklodato.github.io/visual-git-guide/index-en.html

**Comment by daisieh** [comment]
I always find the branching/node diagrams to be very confusing, which is why I went with a different visual metaphor for my diagrams.

**Comment by iglpdc** [comment]
I draw those in the whiteboard when I teach. Even if we don't use them in the lesson itself, I think they make a useful resource to instructors wanting to draw diagrams and also as a cheat sheet for learners. I'd say add the link to the instructors' guide with a comment.
