### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by rgaiacs** [swcarpentry/git-novice#181]
Some instructors reported that a few students had

> incredibly simple Git commands in Git Bash resulted in a seg fault.

Instructors think this might have to do with a combination of recent changes to Git Bash and people not having admin privileges on their computers, but we're not sure.

**Comment by jiffyclub** [comment]
It sounds like this only affects Windows users?

**Comment by rgaiacs** [comment]
> It sounds like this only affects Windows users?

Yes. I will try get more information from the instructors.

**Comment by iglpdc** [comment]
I'm closing this an opening a new issue [1] in the workshop template rep  as I think it belongs there better. 
[1] https://github.com/swcarpentry/workshop-template/issues/262
