### ISSUE TITLE
Git intermediate lesson

### ISSUE THREAD

**Issue by hpourreza** [swcarpentry/git-novice#184]
There is a reference to an intermediate lesson on http://swcarpentry.github.io/git-novice/07-github.html under the 'The ‘-u’ Flag' title but I could not find any such lesson the repo. Could you please point me to where I can find this lesson?

**Comment by daisieh** [comment]
We don't have one yet, but maybe we should...

**Comment by wking** [comment]
On Mon, Nov 16, 2015 at 08:00:29PM -0800, Daisie Huang wrote:
> We don't have one yet, but maybe we should...

It looks like the intermediate-lesson reference landed in 2bb19be7
(Removing a few FIXME markers in Git lessons, 2013-11-29), and was
bumped again in swcarpentry/bc#191, so it's likely that the
intermediate lesson it refers to is [1].  But looking through the bc
logs for intermediate/git and the earlier git/intermediate (from
before swcarpentry/bc@b8c7dc3b7) I don't see any references to ‘git
push -u …’).

Issues that might be good fits for an intermediate lesson: #190, #188,
#187, #179, #171, #169, #88, #71, and the hosting section (does anyone
get to that with novices?).  While we're spinning off lessons, I think
the following belong in an open source / licencing lesson: #180, #173
and the current open-science and licensing sections.

[1]: https://github.com/swcarpentry/bc/tree/gh-pages/intermediate/git

**Comment by iglpdc** [comment]
We will (hopefully) have one intermediate lesson soon. As far as the removal of the text you mentioned, see #218.
