### ISSUE TITLE
Add this (or something like it) to the lesson?

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/git-novice#188]
* http://justinhileman.info/article/git-pretty/full/
* https://twitter.com/emmajanehw/status/549919920990208000

**Comment by jttkim** [comment]
While this surely has put a smile on my face I'm not so sure these flowcharts are exactly novice materials, for two reasons. (1) Novices can have a tenuous grasp on reading flowcharts and they may be put off by them, and (2) the implied background situation (with multiple repos, including one at github, and others depending on that) is (way too) advanced, it will take novices a long way to understand that scenario.

**Comment by wking** [comment]
On Sun, Nov 15, 2015 at 05:57:20PM -0800, Jan T. Kim wrote:
> … the implied background situation (with multiple repos, including
> one at github, and others depending on that) is (way too) advanced,
> it will take novices a long way to understand that scenario.

+1.  There's a big gap between “I pulled our collaborative master, and
now have to resolve a merge conflict” (which is where git-novice will
take you) and “Given a queue full of pull requests, the easiest ones
to grok will be reviewed first, will get more feedback, and as a
result, will be merged first” [1] (which is what Hileman is helping
you with).  I think there's certainly room for a lesson around
branching, pull-requests, and collaborative workflows.  Talking about
focused branches with pretty, atomic commits would be a great fit
there, but that's not this repository.

[1]: https://presentate.com/bobthecow/talks/changing-history#slide-17

**Comment by daisieh** [comment]
Definitely too advanced for git-novice, IMO.
