### ISSUE TITLE
Updating GitHub screenshots

### ISSUE THREAD

**Issue by wking** [swcarpentry/git-novice#192]
I haven't looked through all of our figures in detail, but it looks like at least `fig/github-find-repo-string.png` will need to be updated after [the new repo look is rolled out][1].

[1]: https://github.com/blog/2085-a-new-look-for-repositories

**Comment by rgaiacs** [comment]
I think that will be nice to have one standard size/resolution for screenshots.

**Comment by iglpdc** [comment]
Closed by #202.
