### ISSUE TITLE
Rstudio git integration should mention XCode command-line tools bug

### ISSUE THREAD

**Issue by emilydolson** [swcarpentry/git-novice#193]
This is a note that we should add information on how to deal with the executable git not being accessible on macs because the XCode license needs to be accepted.

(will provide more details later)

**Comment by iglpdc** [comment]
Thanks, @emilydolson. Do you think the workshop template repo could be a better place to talk about this? In this lesson we focus on how to use Git and assume that people have a working installation. I agree, thought, that as we talk about the integration with RStudio, it could be also good to mention it here.
