### ISSUE TITLE
Suggest adding two more cartoons in the reference section

### ISSUE THREAD

**Issue by apawlik** [swcarpentry/git-novice#196]
...especially after your trainees feel confused during the pair exercise when they work together for the first time on the remote repo (links thanks to 	Clair Barrass from EPCC):

https://xkcd.com/1597/

https://hikaruzone.files.wordpress.com/2015/10/in-case-of-fire-1-git-commit-
2-git-push-3-leave-building2.png?w=800&h=559

**Comment by iglpdc** [comment]
@apawlik do you have a sugeestion on where to add them?

**Comment by iglpdc** [comment]
@apawlik I'm closing this as I don't see a good place to add the new files. If you have some placing in min, please reopen or send a PR. Thanks!
