### ISSUE TITLE
Exploring history doesn't mention that "git checkout <commit> <file>" stages

### ISSUE THREAD

**Issue by amueller** [swcarpentry/git-novice#205]
It might be a bit confusing to the students that if they do `git checkout <commit> <file>`, `git diff` doesn't show any changes. The changes are automatically staged, so they have to do `git diff --staged` to see the changes.

I feel that this should also be reflected in the figure: http://swcarpentry.github.io/git-novice/05-history.html

**Comment by iglpdc** [comment]
I agree. When I teach the lesson I actually follow a slightly different approach. I think novice users would commit more often than checkout/reset, so I don't expect them to remember which the exact way to undo things. Instead what I ask them to remember is that `git status` has the answer. 

If you just saved (without staging) some changes that you want to undo, `git status` tells you to `git checkout -- <file>` to undo.

If you actually staged you changes, `git status` tells you to `git reset HEAD <file>` to undo. The changes are back to your working dir, so you can decide if you want to fully get rid of them by doing `git checkout -- <file>`. In some sense, you just undo the last step.

If you actually committed you changes and you really want to go back to a previous version, you do `git checkout <commit> <file>`, which again undoes only the "last" step and put your changes in the stage.

I think it's better to split this topic into two: one about diffs and different formats for commit ids and the other on how to undo things with the two case for `git checkout` and the case for ` git reset HEAD`.
