### ISSUE TITLE
create slide deck for teaching?

### ISSUE THREAD

**Issue by amueller** [swcarpentry/git-novice#206]
I really like the slide decks by @abostroem in addition to doing live-coding [so you can show diagrams etc].
I think we should try to recreate them using a more open tool, possibly directly using reveal or jupyter notebooks?
Currently they seem to be trapped in slides.com.

**Comment by daisieh** [comment]
Do you have a link to her slide decks?

**Comment by amueller** [comment]
here:
http://slides.com/abostroem/local_version_control#/
http://slides.com/abostroem/deck-4#/
http://slides.com/abostroem/deck-5#/

I started a jupyter based slideshow here:
https://github.com/amueller/git_workshop

**Comment by gvwilson** [comment]
Instead of creating a slideshow, how about adding diagrams to the existing course notes? It would then be easy to create an extra page in the course notes that had just the diagrams.

**Comment by amueller** [comment]
@gvwilson that sounds also good.
I don't like the bullet point format that much, but I like to be able to show people the instructions for the exercises.

**Comment by abostroem** [comment]
I use the slides for teaching - not just the diagrams. I find they distill down the information in the lessons to something that students can read to supplement what I'm saying. Also, echoing @amueller I like having the exercises written with reminders of the commands we've learned.

**Comment by iglpdc** [comment]
I like @abostroem 's slides for a fast-paced lesson or a quick review of the materials, but I don't see that much need for them in our slow-paced, live-coding workshops. 

Slides tend to be packed with too much, often repeated information. It also happens to be very hard to read text on the screen while listening to the instructor, so, in general, I prefer to use slides only to backup the talking with *visual* information.

Also for people following the lesson at home, the html version of the lesson is better than the condensed version that slides may show.

So, I'm -1 for this type of slides. I see though two cases when slides could be really useful. The first one is to show the diagrams in the lesson and the second to show challenges. It would be really nice to have some sort of tool to extract those from the markdown and create a slideshow, so the instructor could switch between a browser with the slideshow and the terminal with the live code.

**Comment by amueller** [comment]
@iglpdc what do you mean by "show challenges"?
I will indeed be teaching a lesson that is much shorter than a standard SWC workshop on git, so the requirements are a bit different.

I agree that for "at home", the html version is great.

I don't really have any experience teaching SWC lessons, so I'm happy for any input and I certainly don't want to push my arguments. I was watching the scipy 2015 git course to see how others teach the material, and that was using the slides.

**Comment by abostroem** [comment]
I agree that for "at home" the html is better.

I find students like having the slides as reference material. In practice I switch between slides and command line. I like to explain what I'm about to do before I do it and having text is useful for that.

**Comment by iglpdc** [comment]
> @iglpdc what do you mean by "show challenges"?

Typically at the end of each topic we have a set of challenges, short exercises that learners are asked to complete on their own after the instructor finishes teaching the topic (see e.g. [06-ignore.md](https://github.com/swcarpentry/git-novice/blob/gh-pages/06-ignore.md)).

Despite most challenges are very short, it's hard to explain to the learners what the challenge is about if you don't actually show the text from the lesson in the screen. So, the instructor typically goes to the html of lesson, scrolls down to the end and tells everybody to do the second challenge starting from the bottom (or whatever). 

What I was suggesting is to have one slide per challenge in the lesson, so the instructor can switch quickly to that slide. To make it perfect, I'd like to be able to select the challenges that I want to include in advance (there are way more challenges than time to do them) and pass them to a script to build my "challenges" slideshow with only those that I intend to do in the workshop.

> I will indeed be teaching a lesson that is much shorter than a standard SWC workshop on git, so the 
> requirements are a bit different.

I see. Then probably the slides allow you to go faster. I agree that it would be nice to have something like @abostroem's for that case, or to review everything at the end.

**Comment by daisieh** [comment]
Personally, I find it really helpful to have the diagrams from the lessons available on a second projector, in addition to the live-coding on the main projector. I've included such a slide deck in #191, but it's not ideal because it's a pdf slide deck, so it can't change when we update the lessons, but it has many of the same features as @abostroem's without any of the text.

**Comment by gvwilson** [comment]
All figures from each lesson's episodes are now stored in `/figures/` in the rendered version - can this one now be closed?

**Comment by TomKellyGenetics** [comment]
I like the diagrams in the slides. I generally find myself drawing the git concepts on a whiteboard in a addition to live coding. They seem a bit redundant with the live-code sections though.

Perhaps it would be better to streamline them as a visual aid, say keeping the diagrams and exercises but cutting the overlap with live-coded sections. Leaving up a summary could help during setup or exercises.
