### ISSUE TITLE
Clarify where to find instructions on formatting, building, and submitting lessons

### ISSUE THREAD

**Issue by catherio** [swcarpentry/git-novice#207]
In this repository, the file README.md states "Please see https://github.com/swcarpentry/lesson-template for instructions on formatting, building, and submitting lessons"

However, when I arrive at the lesson-template repository, there is no README.md, nor is it clear where else to find the instructions mentioned.

One possible fix could be to add a README.md to the lesson-template repo. Another possible fix could be to point readers of this repo to http://software-carpentry.org/blog/2014/10/new-lesson-template-v2.html instead.

**Comment by gvwilson** [comment]
Good catch - the instructions are now in https://github.com/swcarpentry/lesson-example so that .../lesson-template only contains the style files themselves. I'll update the docs here and in other lessons.

**Comment by iglpdc** [comment]
Thanks @catherio! I've moved the issue to the lesson template repo, so we don't forget to fix it. I'm closing this.
