### ISSUE TITLE
Split "Exploring history" in two topics

### ISSUE THREAD

**Issue by iglpdc** [swcarpentry/git-novice#212]
This follows up from #205. First, the title of the topic is a bit confusing: first thing coming to my mind is the topic is about `git log`. Second, we should mention `git diff --cached`. I think it's good practive to use before `git commit` when the commit is not trivial. Third, we motivate the use of a VCS for its great "undo" features, so I think we should give the topic a more prominent place in the lesson.

My proposal is split "Exploring history" in two topics. One topic would be about `git diff` and the different formats for commit IDs and including `git diff --cached`. We can called this "Comparing different versions". The other topic would be about how to undo mistakes recovering from changes that you saved but not staged, saved and staged, saved and committed. We can called this "Undoing mistakes". This would address in the more basic parts of #179.

**Comment by amueller** [comment]
+1! In particular when combined with ``checkout`` I think the ``cached`` option is important (otherwise you can't see the changes done by checking out a file).

**Comment by iglpdc** [comment]
I'm closing #88, but adding it here as a reference: the rewrite of this topic has to take #88 into account.

**Comment by iglpdc** [comment]
Same for #179: take it into account when rewriting this topic.

**Comment by kekoziar** [comment]
It seems the novice-level suggestions in this issue have been addressed in subsequent episode PRs. Other topics suggested - such as `reset` and `rebase` - through links to other issues are intermediate and advanced topics, and so are out of scope for a novice lesson. I'm relabeling the issue as intermediate, so it can easily be found if an advanced git lesson is developed.
