### ISSUE TITLE
all-in-one html has lessons in wrong order

### ISSUE THREAD

**Issue by lexnederbragt** [swcarpentry/git-novice#213]
I wanted to use http://scf.rgaiacs.com/nightly/git-novice/all-in-one.html for printing out all the material for a workshop, but found the order of the subjects was wrong, e.g. the order was

* Collaborating
* Automated version control
* Conflicts
* Hosting

Etc.

I also have a question: these all-in-ones are the nightly builds, so they may deviate from the released version of the lesson?

Tagging @rgaiacs because I suspect he may be able to help.

**Comment by rgaiacs** [comment]
> I wanted to use http://scf.rgaiacs.com/nightly/git-novice/all-in-one.html for printing out all the material for a workshop

=)

> but found the order of the subjects was wrong, e.g. the order was

At some point `make` doesn't sort the files by default. I think that I fixed that on my [pull request](https://github.com/swcarpentry/lesson-template/pull/281). I need to apply that on the machine that is building the lesson and I should do it on Sunday.

> I also have a question: these all-in-ones are the nightly builds, so they may deviate from the released version of the lesson?

**Yes.**

**Comment by lexnederbragt** [comment]
Thanks! Is having an all-in-one html for the released version a good idea/possible?

**Comment by rgaiacs** [comment]
> Is having an all-in-one html for the released version a good idea/possible?

cc @jiffyclub

**Comment by rgaiacs** [comment]
> I wanted to use http://scf.rgaiacs.com/nightly/git-novice/all-in-one.html for printing out all the material for a workshop, but found the order of the subjects was wrong

@lexnederbragt Should be OK now. Could you double check?

**Comment by lexnederbragt** [comment]
The git one looks good now. Thanks!

**Comment by iglpdc** [comment]
I'm closing this then. Thanks @rgaiacs.
