### ISSUE TITLE
Can this material on branching be recycled?

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/git-novice#225]
https://github.com/swcarpentry/bc/pull/471

**Comment by iglpdc** [comment]
Maybe, I'll take a look. But I prefer to move it to Git intermediate lesson. (I'm writing a draft of the lesson with all the stuff that is hanging around here: I'll post it soon.)

**Comment by wking** [comment]
On Wed, Feb 03, 2016 at 08:33:07AM -0800, Ivan Gonzalez wrote:
> I'm writing a draft of the lesson with all the stuff that is hanging
> around here…

I'll ping @rgaiacs, since he just taught an intermediate-Git lesson
and has the basic lesson template all filled in [1].

[1]: https://github.com/rgaiacs/swc-git-intermediate

**Comment by iglpdc** [comment]
Oh, great! I just took a look to @rgaiacs 's lesson and it's pretty much what I was thinking in (prolly minus `bisect`, plus more "undos" and `git add -i`). I think the goal should be to be able to do a PR to a repo and be able to handle most of the common hiccups in doing that.

**Comment by wking** [comment]
On Wed, Feb 03, 2016 at 09:04:36AM -0800, Ivan Gonzalez wrote:
> …prolly minus `bisect`, plus more "undos" and `git add -i`…

Once learners have a reasonable foundation, intermediate/advanced
additions are mostly orthogonal.  So you can skip the bisect section,
or an interactive-add section, etc., without missing something
critical for a subsequent topic.  You'll just want time estimates in
the topics and a note in instructors.md suggesting folks pick and
choose what they want / have time for.  The limit on the repo will
just be “does the lesson maintainer want to take responsibility for
maintaining $CONTENT?” and “are any novice Git users interested in
$CONTENT?”.

**Comment by rgaiacs** [comment]
@iglpdc I was planning to transfer that "intermediate" lesson that I wrote to Software Carpentry. I was only waiting to us have a procedure for it.

**Comment by gvwilson** [comment]
:+1: to moving it to intermediate Git.

**Comment by chendaniely** [comment]
@iglpdc I'm running a few git workshops at school.  I'm happy to use and provide feedback.

**Comment by rgaiacs** [comment]
@iglpdc I'm happy to work with you on the intermediate lesson during end of spring or summer.

**Comment by justbennet** [comment]
@rgaiacs @iglpdc Did the intermediate Git lesson material get committed?  I don't see a repository for it, but perhaps I'm looking in the wrong place?

I was just looking at the warning message from Git 1.8 about the change in behavior of an unqualified `git push origin` and wondering whether to propose adding to the git configuration section of git-novice `git config --global push.default ***`, where perhaps what we suggest could do with a little discussion?  Or would that be better discussed here?

**Comment by wking** [comment]
On Wed, Apr 27, 2016 at 03:07:00AM -0700, justbennet wrote:
“I was just looking at the warning message from Git 1.8 about the
change in behavior of an unqualified `git push origin` and wondering
whether to propose adding to the git configuration section of
git-novice `git config --global push.default ***`”

I'd much rather teach folks to explicitly list the branches they're
pushing and pulling.  For lessons that don't teach “branches”, it will
take a minute or so to motivate the presence of ‘master’ in ‘git push
origin master’.  But I don't think it will take as long or pull in as
many unexplained terms as it would take to explain push.default.
