### ISSUE TITLE
licensing: mention apache license, give properties of licenses

### ISSUE THREAD

**Issue by amueller** [swcarpentry/git-novice#227]
Currently the licensing part mentions MIT, BSD and GPL. I think it should also mention the apache license.
It also doesn't really give any advice when or why to pick MIT, BSD or GPL.
It links to dx.doi.org/10.1371/journal.pcbi.1002598, but I feel there should be a two-sentence summary.

There are these two paragraphs:

> If you want…
> 
> …the widest possible distribution and adoption, fewest restrictions on users, open and transparent source code, peer review, community contributions to the codebase, and easy incorporation of your code by others… then a permissive FOSS license such as the BSD/MIT, Apache, or ECL licenses may work well. Because of the few requirements on users, these licenses are amongst the easiest to apply and administer, and promote unfettered incorporation of your code into other software—including copyleft or commercial software. Despite their general permissiveness, they do assure continued author attribution in any and all redistributions or derivative works.
> 
> …to assure the benefits and openness of FOSS in all future derivatives of your work, open and transparent source code, peer review, community contributions to the codebase, and the potential incorporation of your code into other copyleft-licensed works… then you should consider a copyleft FOSS license like the GPL, LGPL, or MPL. These licenses, by requiring anyone who distributes the unmodified or modified code to do so under the same license, guarantee perpetual open source of your work. Some copyleft licenses, such as the GPL, have particularly strong developer communities, encouraging community contributions to your software. The copyleft requirements of these licenses can sometimes, however, dissuade others from adopting or incorporating your code.

I think a shorter form of this should be included. It should also be mentioned that BSD and MIT are pretty equivalent, while there are patenting protections in Apache.

**Comment by gvwilson** [comment]
Sure, please go ahead and propose wording.

**Comment by wking** [comment]
On Wed, Feb 03, 2016 at 12:03:33PM -0800, Andreas Mueller wrote:
> Currently the licensing part mentions MIT, BSD and GPL. I think it
> should also mention the apache license.  It also doesn't really give
> any advice when or why to pick MIT, BSD or GPL.

See #195 (which landed a reference to Apache) and #194 (where there
was some discussion about the level of detail we want to get into in
this repo).

**Comment by amueller** [comment]
I think we should try to keep things very simple and short, but still give some background.
I think making it easy for people to choose a license (and telling them they can always relicense) makes it more likely that people will actually add a license to their project.
I expect that telling them it's a daunting task and not explaining the options will make it less likely that people add a license.

I'll try to reformulate without adding a lot of text.

**Comment by wking** [comment]
On Wed, Feb 03, 2016 at 01:40:14PM -0800, Andreas Mueller wrote:
> I think making it easy for people to choose a license (and telling
> them they can always relicense) makes it more likely that people
> will actually add a license to their project.

That's a good point, but mention that this gets harder as copyright
holders become more diffuse.  For example, if you land a GPL
contribution and then that author dies, you'd be tracking down their
inheritors to figure out who to ask about relicensing that
contribution.

> I'll try to reformulate without adding a lot of text.

Or just explain why licenses are useful (“stuff is usually ‘all rights
reserved’ by default”) and link to [1]?  That gives the generic view,
and Morin (already linked) and VanderPlas (SWC ties, and also has a
related post [2]) will fill in the academic/science angle.

So I think this topic has been well covered in other places, and we
benefit by just linking out instead of regenerating those discussions
here.

[1]: http://choosealicense.com/
[2]: http://www.astrobetter.com/blog/2014/03/10/the-whys-and-hows-of-licensing-scientific-code/

**Comment by amueller** [comment]
I agree about linking out, but I feel that an executive summary can help. Having to read another whole whole page to read seems to require a substantive investment. Maybe choosealicense.com is brief enough, though.

**Comment by gvwilson** [comment]
But again, what are we taking out to make room for this?

**Comment by wking** [comment]
On Wed, Feb 03, 2016 at 02:40:18PM -0800, Greg Wilson wrote:
> But again, what are we taking out to make room for this?

I think we can drop a lot of the existing 11-licensing.md in favor of
a link to choosealicense.com.

**Comment by gvwilson** [comment]
Does that mean that we don't talk about licenses in class, and just 
point them at extra reading?

**Comment by wking** [comment]
On Wed, Feb 03, 2016 at 03:29:06PM -0800, Greg Wilson wrote:
> Does that mean that we don't talk about licenses in class, and just
> point them at extra reading?

Maybe?  We'd want to talk over whatever language we keep, and maybe
show an choosealicense.com screen-shot?  I'd be interested to know how
much time the existing text gets in live lessons.

**Comment by gvwilson** [comment]
I give licensing 5-10 minutes when I teach Git, and "where do I put my 
repo?" gets another 5-10 depending on the audience.

**Comment by amueller** [comment]
I'm happy to work on the writing, but I've never seen this taught, so I can't judge how much time everything takes. Is there a video for me to go by?

On the other hand, the teaching and the material on the website are not one-to-one, right? So we could rephrase the website a little bit. And I totally understand that making everything longer is not an option.

**Comment by wking** [comment]
On Wed, Feb 03, 2016 at 03:49:03PM -0800, Greg Wilson wrote:
> I give licensing 5-10 minutes when I teach Git, and "where do I put
> my repo?" gets another 5-10 depending on the audience.

I haven't timed it, but my trimmed-down version is in #229.  I think
there's still enough content there that the lesson will be meaningful
if the WAN is inaccessible.

**Comment by iglpdc** [comment]
I'm closing this via #229. We don't have much time to talk about this in the lesson, so this shorter version fits well. I would like to see this further expanded in a full open science lesson though...
