### ISSUE TITLE
hosting: discuss private hosting and transitioning from private to public repos

### ISSUE THREAD

**Issue by amueller** [swcarpentry/git-novice#228]
I think a relatively common model (for better or arguably for worse) is that people develop their code in private, and make it public on publication. I think we might want to discuss this strategy, and how it can be implemented very easily using github, and free private repositories (used for research), or using a self-hosted repository that is later pushed to an open platform.

I think it is worth pointing out that creating a self-hosted repository can be done by running `git init --bare` on a shared file-system.

**Comment by gvwilson** [comment]
I think it's an interesting topic - what would you take out to make 
room?  (Our lesson is already full to bursting, so additions have to be 
matched with deletions.)

**Comment by iglpdc** [comment]
This is related to #224, or better, related to a solution for it. I think it's important too, but I'd prefer to see it in the (coming really soon) intermediate lesson.

**Comment by amueller** [comment]
Maybe take out the ISP or the CI part? But I'd be happy with just having it in the intermediate lesson. Though the CI should maybe also go into the intermediate part?

**Comment by kekoziar** [comment]
Since github now has private repository options for free accounts, this proposed workflow is not current (e.g. changing from private to public is simple now), or an intermediate/advanced topic (migrating a repository between different hosting solutions) and out of scope for a novice lesson.
