### ISSUE TITLE
Expand discussion of hosting on github or bitbucket

### ISSUE THREAD

**Issue by avishek-r-kumar** [swcarpentry/git-novice#237]
I believe a major barrier for some students to using hosted VC services is that they do not want to make their code public. 

I'd like to see some small additions to the hosting section of the git lesson:

1. Github is free as long as your publicly host your code. 
2. Github will cost money for private hosting. 
3. Bitbucket offers unlimited free public and private repos to work on projects, papers, etc. that you may not want to be made public provided you register with a *.edu, .ac.il, edu.sg* email address.

**Comment by petebachant** [comment]
GitHub does have an [educational program](https://education.github.com/) however, with 5 free private repos for students.

I don't know if it's appropriate to editorialize, but working openly should be promoted. Learners should not be afraid to share their work, as long as it's licensed properly. They should think not of their work being "stolen" or criticized but of the opportunities for others to make their work better.

**Comment by avishek-r-kumar** [comment]
I don't think you are editorializing. I think this is an important topic. 

I agree working openly should be promoted and the ultimate goal. My argument is the following: 
Students (and PIs) may feel apprehensive about having their work publicly available online *at first* for fear of ridicule, undue criticism, or having your work stolen . This is akin to someone feeling nervous speaking or performing publicly for the first time. Typically someone performs in a safe setting with people they trust and receives constructive feedback. They then have the confidence to perform publicly. I believe the same logic can be applied to open science until it becomes a strong mainstream culture. In short, private hosting is a step toward public hosting and much easier then just making the jump to full open science where their work is shared, improved and ultimately better adopted. 

I have also amended my previous comment adding github for education and expanding the types of email addresses bitbucket offers for academic accounts. 

Please let me know what you think.

**Comment by petebachant** [comment]
I agree that private repos may be a "gateway drug," but there must be some way to quantify how extremely rarely people will randomly seek out code to criticize, so there's really nothing to lose. The worst that could happen is a random person comes along and makes your stuff better, which has happened to me a few times. 

I'm not sure how to address the scooping concern. I make sure I have a "how to cite" in the README of any repo that I may use in a publication someday. However, code/data citations via figshare or Zenodo DOI aren't tracked by Google Scholar... yet.

**Comment by petebachant** [comment]
Note this is related to #228.

**Comment by iglpdc** [comment]
I'm going to closed this per #238. I don't think we should focus that much in the commercial strategies of the different hosting providers, as they change often and have not much relation with the main point of the lesson. The only reason we use Github versus its competitors (or even self-hosted solutions) is because it seems to be popular and also the choice for hosting the Software Carpentry repos. We mention the main players in the lesson (Github, Bitbucket and Gitlab) and I think this is enough for people to make up their choices.
