### ISSUE TITLE
Demonstrate drag n' drop file upload (new feature)

### ISSUE THREAD

**Issue by rossmounce** [swcarpentry/git-novice#240]
For novices, I think it'd be great to demonstrate drag n' drop file uploads, to make them feel more comfortable with some of what github does -> "it's just like DropBox, but better!" https://github.com/blog/2105-upload-files-to-your-repositories

Idea sketch for how this functionality could be incorporated:
0: sign-up 
1: upload a .csv (drag n drop) 
2: make changes to different lines of .csv, re-upload (drag & drop) 
3: show version-diff on web -> "wow, cool"
4: now for the command-line interface...

I'd argue this feature should be demonstrated very early-on to give some early encouragement (a taste of what's to come) and insight into why github is so useful. Who wouldn't want unlimited public file storage for files under 100MB? Having GUI-methods really lowers the barriers for those that are apprehensive. It will hopefully get people interested before the scary terminal CLI-stuff happens.

**Comment by iglpdc** [comment]
In my experience comparing to other tools is not worthy as a motivation, as it touches some people's feelings ("my tool also does this thing"), so I'd prefer avoid the mention to Dropbox, but other than that, I think we could add this as a callout or exercise at the end of the Github topic. 

@rossmounce would you like to make a PR with this?

**Comment by shals3** [comment]
@iglpdc I added what I thought about this my existing PR [Updates to episodes 02 and 07 #492]

**Comment by kekoziar** [comment]
Addressed with PR #492
