### ISSUE TITLE
Improve the "Getting ready" section

### ISSUE THREAD

**Issue by iglpdc** [swcarpentry/git-novice#275]
Getting ready should call for change of directory, same as the rest of the lessons:

``` cd && cd Desktop```

to avoid problems with permissions. Also, this allows the learner to have a clear idea of where the repo is in the filesystem, inspect the repo with the GUI, etc...

This in connection with [this thread in the Discuss list](http://lists.software-carpentry.org/pipermail/discuss/2016-June/004538.html).

**Comment by gvwilson** [comment]
As per @beroe's mail on the Discuss thread, we should tell people to do this with two commands:

~~~
cd
cd Desktop
~~~

to avoid having to explain `&&`.

**Comment by embray** [comment]
I might go one better and update the Windows installer to make this the default path for Git bash (does it really put people in System32 by default??)  I'd have thought it would be C:\Users\<username>\ thought that's not much better for many users.

That said it would be good to have in the tutor notes as well.  I find that Windows students definitely get confused about "where they are" in the Windows file system.
+1 to putting their files on Desktop (and then immediately having them create a directory on Desktop to cd into, i.e.

```
cd
cd Desktop
mkdir swc
cd swc
```

**Comment by lexnederbragt** [comment]
The lesson starts by making a 'planets' directory (see http://swcarpentry.github.io/git-novice/03-create.html). I think it would be confusing to have them make a `swc` directory in addition.

**Comment by iglpdc** [comment]
Closed by #279.
