### ISSUE TITLE
Update collaborating section to accept push access

### ISSUE THREAD

**Issue by sstevens2** [swcarpentry/git-novice#278]
Hey all,
Taught the git section for a workshop yesterday.  Github has some updates and now when you add someone to push to your repo, they have to accept that access.  I think we should add directions for this.  We had a little trouble because some people didn't get the little bell in the corner for notifications and we had to go to https://github.com/notifications manually to accept permissions.
Sarah

**Comment by iglpdc** [comment]
Sorry, @sstevens2, I'm not sure what you mean. In the lesson we ask people to add their partner as a collaborator to their repo, so the second person gets push-rights. Are you saying that this has changed?

**Comment by sstevens2** [comment]
Yes, it has changed.  Before the partner automatically got access to the repo once added.  Now they (the partner) have to accept access, by going to their notifications.

**Comment by iglpdc** [comment]
I see, @sstevens2 . Do you wanna submit a PR with a fix?

**Comment by sstevens2** [comment]
Created a quick and simple PR to fix it.  Let me know what you think @iglpdc 
Thanks!

**Comment by iglpdc** [comment]
Fixed by #228
