### ISSUE TITLE
Move location of directions to use own information in git setup instructions

### ISSUE THREAD

**Issue by gallington** [swcarpentry/git-novice#281]
Right now the caveat that you should use your own name, email, etc. rather than Dracula's "info" comes after the code example. I have seen students accidentally get ahead of themselves and copy this code in directly. I would recommend that this info comes first.

**Comment by iglpdc** [comment]
Thanks @gallington. We have now a better writing of this paragraph (see #280) that also addressed som issues with privacy that surfaced a few weeks ago. I think that with the new writing the text is better after the commands, so I'm closing this issue.
