### ISSUE TITLE
Add a callout box or a note regarding scrolling down through git log

### ISSUE THREAD

**Issue by gallington** [swcarpentry/git-novice#284]
If students keep adding and committing they may end up with a scrollable output from git log, which is presented as a " : " and is confusing for the novice. 

Suggested hint to add to lesson:
If output of git log is stalled on : 
this is due to the less program, which makes the output of git log scrollable.
Type q to exit this screen. Type h to get help.

**Comment by iglpdc** [comment]
Yep, @gallington , good point, this is actually something we see every workshop. Would you like to make a PR with a fix? I'd suggest adding a short sentence (or a call out) with that info:

- long log outputs a presented in a pager program (it's `less` by default, but it can be changed in the settings. I dunno whether is better mentioning `less` or the word pager)
- to get out, press q,
- to move to the next page, press space bar.
- to search for a word, press `/` and the type the word you're searching for (maybe this one shouldn't be mentioned: it's useful, but maybe too much.)

**Comment by iglpdc** [comment]
See a fix #293.

**Comment by TomKellyGenetics** [comment]
+1 This comes up in most of our workshops too, this behaviour is also used to navigate the "help" in R so it is useful in both lessons.

However, note that some systems (e.g, Mac) print the `log` to the terminal instead so not all machines will enable this behaviour.
