### ISSUE TITLE
Recreate html

### ISSUE THREAD

**Issue by lexnederbragt** [swcarpentry/git-novice#291]
Sorry for doing this, but I am asking both because I demoed to our group of instructors and helpers how to fix an issue by submitting a PR (#279, now merged but see #290) but can't show them that the change is now visible, and second, I will be teaching the git module on Monday. So can I ask for a regeneration of the html versions of the changed pages? Preferably after merging #290?

**Comment by iglpdc** [comment]
Hi @lexnederbragt, I just updated the html.
