### ISSUE TITLE
"fatal: no files added" not on all platforms?

### ISSUE THREAD

**Issue by lexnederbragt** [swcarpentry/git-novice#295]
In https://github.com/swcarpentry/git-novice/blame/gh-pages/06-ignore.md after

`$ git add a.dat`

the output in the lesson material says 

>The following paths are ignored by one of your .gitignore files:
a.dat
>Use -f if you really want to add them.
>fatal: no files added

On my Mac, with git version 2.8.1 (as well as an older one I tested before), that last line (starting with 'fatal') does not appear. Is this a platform specific or git version specific issue?

**Comment by iglpdc** [comment]
Maybe. Same for my here, but also on a Mac.

**Comment by rgaiacs** [comment]
Tested on Linux. And I got the same result. I believe this is version specific.
