### ISSUE TITLE
add notepad++ alias

### ISSUE THREAD

**Issue by raynamharris** [swcarpentry/git-novice#302]
In git-novice/02-setup.md there is a nice section on configuring notepad++ for windows. I find that in addition to git config, one also needs to create an alias to allow the user to call notepad++ document from the command line. I suggest adding this line of code after the command to configure notepad++  

`$ alias notepad="'c:/program files (x86)/Notepad++/notepad++.exe'"`

**Comment by TomKellyGenetics** [comment]
+1 Never been able to use `notepad` for SWC. We always resort to `nano`, editing in the terminal is useful for power users but a familiar environment will be helpful for some.

**Comment by iglpdc** [comment]
Closed by #320
