### ISSUE TITLE
Do a better job of explaining the staging area

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/git-novice#315]
See https://github.com/swcarpentry/bc/issues/746 for earlier discussion.

**Comment by humberto-ortiz** [comment]
Is this issue still open? The current lesson (https://github.com/swcarpentry/git-novice/blob/gh-pages/_episodes/04-changes.md#staging-area) has a description of the staging area, and includes an example of committing changes to a bibliography and citations, but not an unfinished discussion. The description of the staging area includes an analogy with gathering people for a group picture.

**Comment by iglpdc** [comment]
Closing this, as it seems solved in the current version.
