### ISSUE TITLE
Git Bash 2.10.1 doesn't launch on Windows 10 Home

### ISSUE THREAD

**Issue by rgaiacs** [swcarpentry/git-novice#347]
One of my learners installed Git Bash yesterday, tested it and it was OK. Today, during the workshop the learner asks Windows to launch Git Bash but not happens.

**All** shortcuts looks to be configured to run `"C:\Program Files\Git\git-bash.exe" --cd-to-home` that for unknown reason to me don't work. I changed it to `"C:\Program Files\Git\git-bash.exe"` and I managed to run Git Bash.

This only happened to one of my learners but I thought that we could investigate it later.

**Comment by djamant** [comment]
I was having the same problem too. This solution fixed for me as well. Thanks, @rgaiacs !

**Comment by kelseyhoover** [comment]
Thank you! This was very helpful!

**Comment by pepezane** [comment]
Hi 

I have the same problem, did what was suggested but mine still will not work.

**Comment by Tig10** [comment]
I have attempted this solution and it has not worked for me. Has anyone found out why this is happening?

**Comment by jinhojang** [comment]
This fixed my problem as well. thanks a lot

**Comment by rgaiacs** [comment]
I'm closing this because we should be using [2.16.2](https://github.com/git-for-windows/git/releases/tag/v2.16.2.windows.1) instead of 2.10.1.

**Comment by widdowquinn** [comment]
Not reopening, but I just saw this with 2.16.2 and Windows 10 in today's workshop at St Andrews.

**Comment by royki** [comment]
It was working fine with 2.16.02, suddenly got the problem and after changing to 2.16.2 it's same. Why is this sudden death?

**Comment by mkaatman** [comment]
Having this issue on git version 2.18.0.windows.1

**Comment by sikanderrafiq** [comment]
I did the same, but not working for me. I am using Git-2.22.0-64-bit.

**Comment by kekoziar** [comment]
Hi, @sikanderrafiq. I know it's frustrating when software doesn't install correctly.  The best place to report it is in the [workshop-template repository](https://github.com/carpentries/workshop-template), since Git Bash is a tool that is used across many lessons.

**Comment by sikanderrafiq** [comment]
Problem resolved.

**Comment by mkaatman** [comment]
@sikanderrafiq this will be more helpful to future readers if you mention what your solution was.

**Comment by sikanderrafiq** [comment]
Sure. I am using Git-2.22.0-64-bit.exe and I was facing a problem when I was selecting the option "Use Window's default console window".  

Git works fine for me when I have selected the option "Use MinTTV (the default terminal of MSYS2)" instead of an earlier one in configuration "which terminal emulator do you want to use with Git bash"
I hope this help.
Sikander

**Comment by sikanderrafiq** [comment]
I have installed on Windows 10 Pro.

**Comment by LilithElina** [comment]
I'd like to add that this is apparently still an issue, both with Window's default console and the other option. Me and one of our learners can't open Git Bash right now on Windows 10. Luckily, we can use the Terminal in RStudio instead.

**Comment by QiangHu1** [comment]
I got the same problem today. But I solved it when I did the same thing as @sikanderrafiq.

**Comment by kepee98** [comment]
Thank you. Indeed helpful👍

**Comment by learning0007** [comment]
> Sure. I am using Git-2.22.0-64-bit.exe and I was facing a problem when I was selecting the option "Use Window's default console window".
> 
> Git works fine for me when I have selected the option "Use MinTTV (the default terminal of MSYS2)" instead of an earlier one in configuration "which terminal emulator do you want to use with Git bash" I hope this help. Sikander

how to change my default terminal msys2 to MinTTV  @sikanderrafiq
