### ISSUE TITLE
exercise solution rendering broken in "Creating a Repository"

### ISSUE THREAD

**Issue by pierre-haessig** [swcarpentry/git-novice#350]
Hi,

I believe there is a small syntax typo at the end of the [Creating a Repository](http://swcarpentry.github.io/git-novice/03-create/) page (rendered html version identified by meta tag: http-equiv="last-modified" content="2016-10-11 21:05:25 +0000")

Problem description: the solution to the exercise "Places to Create Git Repositories" doesn't render (bunch of mixed up text).

I looked at the source code, but I'm not familiar with the "fancy" markdown being used. I compared with the next lesson (where rendering is fine), I only found that there is one extra blank line in the quote block between the exercise and its solution. Could it be the cause for the bad parsing?

best,
Pierre

**Comment by daisieh** [comment]
I fixed this in https://github.com/swcarpentry/git-novice/pull/351

**Comment by pierre-haessig** [comment]
Thanks! I guess this issue can be closed as soon as the PR is merged and the html gets regenerated.

**Comment by maglet** [comment]
Thanks for looking into this! I'm teaching this on Sunday, would be nice if it gets merged before then

**Comment by iglpdc** [comment]
Closed by #351
