### ISSUE TITLE
Exploring History actually involves losing a change

### ISSUE THREAD

**Issue by lexnederbragt** [swcarpentry/git-novice#352]
`05-history Exploring History` starts by adding another line to `mars.txt`:

> An ill-considered change

but erroneously only lists that new line in the output of the first diff. This change is never committed.

Later, `mars.txt` is overwritten and then recovered from the current HEAD. In effect, this deletes the "An ill-considered change" line from the file.

Solution could be to rewrite the first part of `05-history` to not add another change.

**Comment by billsacks** [comment]
I would suggest a different set of fixes for this problem:

1. Keep the first part of `05-history`, adding the "ill-considered change"

2. After introducing `git diff HEAD mars.txt`, describe the two-commit version of `git diff`. I rarely want to compare my dirty working copy with some previous commit, so I think it would be more useful to explain the `HEAD~1` syntax in the context of diffing two commits.

    So in place of `git diff HEAD~1 mars.txt` we'd have `git diff HEAD~1 HEAD mars.txt` - whose output matches what's currently shown. Similarly, in place of `git diff HEAD~2 mars.txt` we'd have `git diff HEAD~2 HEAD mars.txt`. And similarly for following diffs that use SHAs to identify the commits.

3. When it gets to `now how can we restore older versions of things?` skip the part about overwriting the file: There are already undesirable changes in our working copy, so we should rework the example to explicitly illustrate undoing the `An ill-considered change` line.

**Comment by martinosorb** [comment]
Hi all! PR #581 fixes the bug following points 1 and 3 raised by @billsacks. I left point 2 open to further debate for now.

**Comment by kekoziar** [comment]
As stated above, PR#581 fixes the original issue by implementing points 1 & 3.  Since point 2 is a separate point which involves how people use `diff`, please open a new issue to improve the section.

**Comment by billsacks** [comment]
Thank you!
