### ISSUE TITLE
Episode 1: "merging" graphics is misleading

### ISSUE THREAD

**Issue by andreas-h** [swcarpentry/git-novice#357]
I believe that the merge.svg image in Episode 1 is misleading: Both changes just append text at the end of the original document, which means that when merging , it is not clear which of the new lines (from version 1 or version 2) should go first.

I think it would be better if versions 1 and 2 would add new text at different parts of the original document, because then the merge would be clear.

**Comment by kekoziar** [comment]
@andreas-h , I understand what you are saying.  Will you revise the image?

**Comment by djhoese** [comment]
I'm preparing to use the git lesson as my teaching demo and had the say opinion about the image as @andreas-h. I was also wondering if red and green are maybe not the best colors to use. I'm not sure if color blindness is an issue with these exact shades of red and green, but even to me (not colorblind) I can see how it might be a confusing diagram. Another thing that seemed odd to me about it is the use of red when talking about possible merge conflicts, but not having red represent a conflict.

@kekoziar I'm not sure I have the time to update the image(s) but if someone did have the time, how would they do it? What is the preferred way of modifying svg images?

**Comment by juholehtonen** [comment]
I drafted a new version of this figure. The logical and the colour blindness issue solved.

**Comment by juholehtonen** [comment]
A PR https://github.com/swcarpentry/git-novice/pull/722
