### ISSUE TITLE
[Episode 07] [Episode 08] - mention why origin nickname is so common

### ISSUE THREAD

**Issue by pshriwise** [swcarpentry/git-novice#359]
Might be a good idea to indicate why this nickname is the most common because it is the default nickname in git when cloning a remote repository. This could be good to indicate explicitly in lesson 08 as well to reduce confusion. Maybe even add a quick `git remote -v` command to show the user it was automatically created.

**Comment by swaldman3** [comment]
I'm happy to make this change as my instructor checkout PR, but... er... can anybody tell me *why* origin is the convention? A few minutes on google didn't help.

**Comment by pshriwise** [comment]
Hi @swaldman3 - thanks for picking this up! 

I don't know of a particular reasoning behind choosing `origin` as the default remote name other than its meaning (to me) is something like "this is the origin of the clone you made". My take is that the important part for the learners is that it will be there when they clone repos, and is simply (as you said) a convention in git.

If you're willing, a note explaining a bit more on remotes as aliases to other repos with commands for renaming/changing them would probably be helpful to some as well!

**Comment by pshriwise** [comment]
Looking at the lessons again, some of this is explained in Episode 8, but I think knowing these things upon first seeing that remote name will reduce confusion. Maybe that note I alluded to would be better placed in Episode 8 after the `git remote -v` command is introduced.
