### ISSUE TITLE
using gui editors for commit messages

### ISSUE THREAD

**Issue by chendaniely** [swcarpentry/git-novice#360]
Notes from the 2016-11-04-nsbe workshop:

students on windows machines are unable to get sublime text working from git bash
even after they copy paste the git config from the setup page in the lesson.

**Comment by jsan4christ** [comment]
There is a very useful guide here how to add text editors to Git, following it I was able to atom as my default edit. Let us know if you still help.
https://help.github.com/articles/associating-text-editors-with-git/

**Comment by iglpdc** [comment]
Thanks for the link @jsan4christ !

We have most of them in the episode on how to [setup git](http://swcarpentry.github.io/git-novice/02-setup/). We are missing some, though: atom for Windows and Textmate for Mac.

I didn't want to have an extesive list of editors (they come and go and it's hard to maintain), but we are pretty much there, so we could add these to complete the pack.

Would you like to send a PR with this? A link to the Github page you qouted would be helpful too (they probably would keep it very much up to date).

**Comment by kekoziar** [comment]
Original issue addressed in https://github.com/swcarpentry/git-novice/pull/499
Suggestion can be searched for and revisited if someone wants to actively work on it.
