### ISSUE TITLE
Reference site doesn't contain anchor links

### ISSUE THREAD

**Issue by andreas-h** [swcarpentry/git-novice#362]
Throughout the lecture, there are links to the explanation of certain words in the glossary / reference, for example,

https://swcarpentry.github.io/git-novice/reference/#version-control

However, the reference website https://swcarpentry.github.io/git-novice/reference/ does not contain any corresponding anchor links, so that the user has to find the word she is interested in in the reference list by herself.  It would be more convenient if the reference website contained anchor links, e.g., `#version-control`, such that the hyperlinks going to the reference take the user directly to the word of interest.

**Comment by gvwilson** [comment]
Agreed - once GitHub deploys the latest version of Kramdown (the 
Markdown parser used by Jekyll), it will automatically generate IDs for 
us that we can link to.

**Comment by iglpdc** [comment]
I'm closing this as we cannot fix it form this repo.
