### ISSUE TITLE
RStudio episode missing "save file" step

### ISSUE THREAD

**Issue by brainwane** [swcarpentry/git-novice#368]
In [Using Git from RStudio](https://swcarpentry.github.io/git-novice/14-supplemental-rstudio/ ) the instructions tell the participant to edit `pluto.txt` and then:

> We can also use RStudio to commit these changes. Go to the git menu and click “commit”:

The participant will need to *save* the changes to `pluto.txt` before committing. We should add this to the instructions.

**Comment by iglpdc** [comment]
Closed by #433
