### ISSUE TITLE
Intermediate lesson?

### ISSUE THREAD

**Issue by jarrah42** [swcarpentry/git-novice#383]
In _episodes/07-github.md, the section on the '-u' flag (line 176) mentions an intermediate lesson. Is there such a lesson? If not, then this section should be removed or reworded to explain what the '-u' option is for.

**Comment by rgaiacs** [comment]
> Is there such a lesson?

I thought we had a draft but I couldn't find it. :-(

> If not, then this section should be removed or reworded to explain what the '-u' option is for.

I agree with you.

**Comment by iglpdc** [comment]
Closed by #385
