### ISSUE TITLE
Issues with discussion.md

### ISSUE THREAD

**Issue by iglpdc** [swcarpentry/git-novice#41]
`discussion.md` was added in #36, but doesn't comply with the lesson template completely. From https://raw.githubusercontent.com/swcarpentry/lesson-template/gh-pages/tools/check.py:

- [x] Heading at line 15 should be level 2
- [x] Heading at line 115 should be level 2
- [ ] Found callout box with unrecognized style 'challenge'
- [x] The document links to 03-conflicts.html, but could not find the expected markdown file `03-conflicts.md`

**Comment by iglpdc** [comment]
@r-gaia-cs Do you know why the "challenge" style is not being picked up in this file?

**Comment by r-gaia-cs** [comment]
@iglpdc Thanks for address this issue.

> Do you know why the "challenge" style is not being picked up in this file?

The HTML file is OK. `tools/check.py` need a small change because we didn't expect to have challenges at `discussion.md`, check https://github.com/swcarpentry/lesson-template/pull/173.

**Comment by gvwilson** [comment]
I don't think challenge exercises belong in the general discussion - 
that's meant to be "further reading" and pointers, rather than a lesson 
per se.

**Comment by iglpdc** [comment]
Should we take them out? After a PR this week we have some in this repo. I think we should of discussion is not meant to be a lesson.

Ivan
