### ISSUE TITLE
Add link to LibreOffice track changes

### ISSUE THREAD

**Issue by jenningsdt** [swcarpentry/git-novice#414]
At the end of Lesson 1, there is a mention of Track Changes in both Microsoft Word and LibreOffice Writer.  However, LibreOffice was not mentioned earlier in the lesson alongside Microsoft Word and Google Docs. I suggest adding LibreOffice to this list along with a link to its track changes help: https://help.libreoffice.org/Common/Recording_and_Displaying_Changes

**Comment by iglpdc** [comment]
Thanks, @jenningsdt! I think your suggestion makes sense. 

Would you like to add the link yourself and become a contributor? Even if you are not very familiar with Git/Github, you can make the change using only your browser. If you want to try, follow [this link to the file you want to change](https://github.com/swcarpentry/git-novice/blob/gh-pages/_episodes/01-basics.md). You will see an icon for a pencil in the top right corner:

<img width="1056" alt="captura de pantalla 2017-05-30 a las 10 27 12" src="https://cloud.githubusercontent.com/assets/1700319/26588344/0f5f176a-4523-11e7-9a6c-b2939968c897.png">

Click on the icon and you will be able to edit the file from your browser and add the link to the LibreOffice docs. (The syntax to add a link is a bit weird, but you can follow the examples for the links for Word and Google Docs).

When you are done, you should scroll down to the bottom of the page and commit your changes by creating a new branch and starting a pull request.

<img width="954" alt="captura de pantalla 2017-05-30 a las 10 35 57" src="https://cloud.githubusercontent.com/assets/1700319/26588665/f03fa6dc-4523-11e7-9f31-754ff8dc9e3c.png">

This will fork a copy of your repo and present you with a page to confirm the pull request. You can add some comments there if you want, but that's pretty much it.

Let me know if you have any trouble. (And sorry for being too verbose if you already know how to do all this :)

**Comment by iglpdc** [comment]
Closed by #417
