### ISSUE TITLE
Cover how to exit VI/VIM

### ISSUE THREAD

**Issue by ErinBecker** [swcarpentry/git-novice#435]
Originally submitted to instructor training repo. Please see discussion here: https://github.com/swcarpentry/instructor-training/issues/487

**Comment by lwasser** [comment]
just note that this is covered in the config materials -- http://swcarpentry.github.io/git-novice/02-setup/#exiting-vim

**Comment by iglpdc** [comment]
Yes, it covered already in the setup. Thanks anyway, @ErinBecker.
