### ISSUE TITLE
Introduce stash and pull --rebase in Conflicts

### ISSUE THREAD

**Issue by shippy** [swcarpentry/git-novice#436]
The workflow introduced in 09-conflict works well with non-parallel collaborators who always commit and push their local changes. But beginners often forget to commit, or make experimental changes that they don't want to share but also don't want to lose. This has one or both of the following effects:

1) Shared repo is littered with meaningless local commits and automatic post-pull merge commits which [mess up the linear history](http://devblog.nestoria.com/post/98892582763/maintaining-a-consistent-linear-history-for-git). (This also hurts the "write meaningful commit messages" instruction.)
2) Novice colleagues are wary of pulling in others' changes.

I'd argue that for most use cases, teaching novices to do `git stash`, `git pull --rebase`, and `git stash pop` is the superior strategy to "`git pull` and deal with it." It brings in the changes; it replays local work on top of them; and if there's a merge conflict, it is resolved with `origin/<branch>` as the "correct history" parent. In short, it does what you'd expect without stepping on anyone's toes in the process.

Alternately, we could omit `git stash`, which would make `git pull --rebase` the enforcer of timely committing of unstaged changes.

Here's a couple of related articles:

* https://mislav.net/2013/02/merge-vs-rebase/
* https://adamcod.es/2014/12/10/git-pull-correct-workflow.html
* the more insistent https://coderwall.com/p/7aymfa/please-oh-please-use-git-pull-rebase
* but do note the more skeptical [discussion on SO](https://softwareengineering.stackexchange.com/questions/307063/why-does-git-pull-perform-a-merge-instead-of-a-rebase-by-default), which raises points that mostly don't apply to (a) small projects (b) with a central authoritative repository that (c) doesn't require merges from downstream.

### This would add unnecessary complexity!

Yes, but not that much of it. The lesson is well-equipped to explain what `git pull --rebase` does differently from `git pull` and why the former is preferable to the latter. Since git configuration is introduced earlier, there's also space for suggesting the setting of `git config --global pull.rebase true` or introducing an alias.

On the other hand, doing this:
* reduces unexpected "git magic" ("why is it making me make a merge commit?")
* removes complexity from tail effects like [foxtrot merges](https://bit-booster.blogspot.ca/2016/02/no-foxtrots-allowed.html)

### This is an opinionated workflow

Of course. So is the default workflow. I do think that this is a better workflow for most researchers.

**Comment by shippy** [comment]
[Subsection "Centralized Workflow" in this Atlassian tutorial](https://www.atlassian.com/git/tutorials/comparing-workflows) is a good illustration of what I have in mind (sans `stash`). With pictures! Without `stash`, but with instructions for dealing with conflicts that might arise halfway through the rebasing.

Perhaps having a clean & informative history might not be worth additional cognitive load -- while some time is spent on `git log`, I don't imagine that initial learners will be using it heavily anytime soon.

Then again, this could be a simple information box / exercise. ("Are you getting tired of writing commit messages after each pull? Try this one simple trick!") I imagine it would go like this:

1. Explain the use case ("there are central repo updates that you know about, and you have some local changes of yours that don't interfere with them"), 
2. Show how `pull` and `pull --rebase` differ in terms of what they do to the commit tree (which is another chance to reinforce the understanding of the underlying model), 
3. Suggest that if a conflict arises in the middle of rebasing, they should `git rebase --abort` and do a standard `git pull` instead.
4. (Maybe do another push-pull exercise that highlights the difference, or use that as a kick-off point.)

I *think* it would be similar in length to the potentially-excised exercise in #272, but I guess a PR and stopwatch is the only way to find out. @daisieh, should I try to create it, or is the idea so off-base that it's unlikely to be merged?

**Comment by daisieh** [comment]
I would say this is something for a possible git-intermediate lesson. I don't think we need our learners to understand nested repos or similar things per se, just to basically understand the idea that the repo's guts are stored inside the .git hidden directory.

**Comment by rgaiacs** [comment]
> I would say this is something for a possible git-intermediate lesson.

I second @daisieh.

**Comment by kekoziar** [comment]
Issues labeled intermediate and out of scope can still be accessed if closed. So, the suggestion is not lost for a potential future intermediate git lesson.

**Comment by katrinleinweber** [comment]
Reading the arguments here, I wonder whether #543 should be revisited? It seems [much narrower](https://git-scm.com/docs/git-pull#Documentation/git-pull.txt---allow-unrelated-histories) and also rather on the "intemediate" level, no? cc @amaji  & @nhejazi

`pull --rebase` may also be intermediate, but it does cover both cases (conflict & online-`init`-ed ReadMe file) and is thus likely to be more useful in day-to-day work.

**Comment by nhejazi** [comment]
Thanks for bringing this up @katrinleinweber -- I agree that #543 is quite a bit narrower than the discussion here but I do think that at some level this lesson, even if targeted towards beginners rather than intermediate learners, has to deal with the issue of a merge conflict of the sort dealt with in that PR. From teaching this lesson and related material on git, I've seen this come up in practice and think it's good for a researcher who has seen this lesson to be able to reference what to do in that situation. I approved that PR since it doesn't introduce much technical material (only introduces the solution to such a problem) and since it only does so in an exercise. I do agree with much of the discussion above that detailed presentation of strategies for handling local commits should be deferred to a intermediate-level lesson.

**Comment by amaji** [comment]
@nhejazi Very nicely explained. I totally agree with your point.
@katrinleinweber Thanks for bringing this up. I had the same concern when I noticed the exercise for the first time. But since this is not part of the core lesson, I an not too concerned. During workshops, I rarely have time to do all the exercises, hence it is optional reference material.
