### ISSUE TITLE
Text wrangler configuration needs to include CLI interface step

### ISSUE THREAD

**Issue by lwasser** [swcarpentry/git-novice#437]
Currently the git setup specifies how to setup a default text editor. 

http://swcarpentry.github.io/git-novice/02-setup/

`$ git config --global core.editor "edit -w"`

However, when you setup text wrangler on MAC, it only works if you have the Command Line Interface (CLI) tools installed too. You can install these from Text Wrangler directly (preferred) or by downloading them and runing the executable. These instructions should be added to the lesson as otherwise that step doesn't work! we taught this today and ran into the issue with several students.

Here's the download

https://www.barebones.com/support/textwrangler/cmd-line-tools.html 

but if you have the app already installed the download will tell you to install from text wrangler directly.

**Comment by GlazerMann** [comment]
pull submitted, along with swapping BBEdit for TextWrangler.

**Comment by iglpdc** [comment]
Fixed by #442
