### ISSUE TITLE
Showing use of "git --help"

### ISSUE THREAD

**Issue by sriharisundar** [swcarpentry/git-novice#438]
I feel showing the output of "git --help" command either after explaining "git init" in lesson 3 or at the start of lesson 4 will be very helpful. 

This can help go over the subsequent commands that appear in the lesson and give a brief overview of these. It also helps re-iterate about the "--help or -h" flags and man pages in the shell. Moreover it nudges people to explore things they could do with git that are not explained in the lessons.

If it is deemed worth it, I can try to implement it and submit a PR!

**Comment by rgaiacs** [comment]
> I feel showing the output of "git --help" command either after explaining "git init" in lesson 3 or at the start of lesson 4 will be very helpful.

Please use `git help` instead of `git --help`. `git --help` is a alias for `git help` and the official documentation says

~~~
'git help -a' and 'git help -g' list available subcommands and some
concept guides. See 'git help <command>' or 'git help <concept>'
to read about a specific subcommand or concept.
~~~

**Comment by iglpdc** [comment]
Hi, @sriharisundar

Are you still interested in submiting a PR about this? I think it would be a good addition. Probably the best would be a callout box somewhere toward the end of lesson 3.

**Comment by sriharisundar** [comment]
Hi @iglpdc

Yes, I am still interested in submitting a PR. I will do it soon.

**Comment by jhlegarreta** [comment]
@sriharisundar I thought that I would go ahead and try to provide a fix to the issue after a prudential time since it was opened. Thanks for understanding.
