### ISSUE TITLE
Section on "Branching" in relation to collaboration.

### ISSUE THREAD

**Issue by brandonkrull** [swcarpentry/git-novice#441]
A majority of times when collaborating on open source projects, you will not just push changes directly to the master branch, but rather to a separately named branch, and then create a pull request. Currently, this lesson contains no information about branching. The lesson could benefit from the idea of "branches" and how these can be used locally for trying new types experiments in your every day life in addition to collaborative environments.

**Comment by asadaqain** [comment]
I want to add that it should be in-scope as some users may not reach open source project level although user may be working alone / with colleges. Its best they learn how to do branching from the start, atleast locally.

So suggestion below may be applicable to "Tracking Changes" or "Collaborating" lessons or even possible new lesson of "Best Practices" or "Branching 101" (which could include Naming branches, working locally, merging, remote branches etc)

When I read branching may be too advanced topic [guide.md](https://github.com/swcarpentry/git-novice/blob/f77ead1d7f3fa9323d6cc668937bb03d3d8abb76/_extras/guide.md), it made me question it. SWC does have lessons such as "Exploring History" of checking out git commits and not losing HEADs (which may take them to rebasing)! To me that seems far more complex than branching, which can save you loads of time and is a best practice! 

**Scenario**

**Problem:** User clones a repo, does work. Discovers the path they were on is wrong or no longer needed! What should the user do?

**Possible Solutions:**

1. User could checkout out from the remote and re-commit but that just messes up the log.

2. cd .. nuke the project directory and clone it again. This may work in some cases but its not practical. 

3. **One should be working is a local branch!** (Proper Solution)

~~~sh
    (A lesson would go in detail of explainations)

    * $> git clone / git pull origin master
    * $ master> git checkout -b "To-be-abandoned" 
    * $ To-be-abandoned> Create files
    * $ To-be-abandoned> git adds and commits 
    * $ To-be-abandoned> Create more files. Oh! No longer 
    need to work on this!
    
    Life Saving Steps
    * $ To-be-abandoned> git add + git commit -m "Do not need it anymore" 
    * $ To-be-abandoned> git checkout master
    * $ master> git branch -d abandon-feature (delete the branch)
    * All is well
~~~

**Comment by kekoziar** [comment]
Branches are out of scope for a novice lesson. Hopefully, at some point, the intermediate and out of scope suggestions will be their own lesson.

PRs labeled _intermediate_ and _out of scope_ can still be accessed if closed.
