### ISSUE TITLE
Should we be recommending Sourceforge?

### ISSUE THREAD

**Issue by aragilar** [swcarpentry/git-novice#458]
Currently we recommend 4 online services: GitHub, Bitbucket, Gitlab and Sourceforge. Sourceforge has not always been a reputable place to download software from (see https://en.wikipedia.org/wiki/SourceForge#Controversies), should we keep recommending it (the main advantage of Sourceforge over the other recommended as far as I know is mailing list hosting, for which there are alternatives).

If we want to keep providing other options than the big 3, we could look at adding Launchpad (https://en.wikipedia.org/wiki/Launchpad_(website)) and/or GNU Savannah (https://en.wikipedia.org/wiki/GNU_Savannah).

**Comment by iglpdc** [comment]
Sounds good! I'd say drop Sourceforge and do not add Launchpad or Savannah, as they are not as popular for scientific software, but we could also add either/both of them as you said.

**Comment by iglpdc** [comment]
Fixed by #462
