### ISSUE TITLE
Correction to data path for Python lesson, episode 4, solution to the last exercise

### ISSUE THREAD

**Issue by kmichali** [swcarpentry/git-novice#460]
Hi, 
I propose a change to the Python lesson, episode 4, solution to the last exercise called "Generate Composite Statistics".

During the whole lesson the attendees are inside ~/Desktop/python_novice_inflamation/data/.  Yet the solution to the exercise assumes that they are in ~/Desktop/python_novice_inflamation/.

I propose to change the solution to the exercise from:

import glob
import numpy
import matplotlib.pyplot

filenames = glob.glob('data/inflammation*.csv')

to:

import glob
import numpy
import matplotlib.pyplot

filenames = glob.glob('inflammation*.csv')

Cheers,
Katerina

**Comment by iglpdc** [comment]
Hi, @kmichali ! Thanks for your contribution. I think you meant to open the issue at [the python lesson repo](https://github.com/swcarpentry/python-novice-inflammation). I'm closing this here, but you definitely should open it there.
