### ISSUE TITLE
Live cording at the begening could be less confusing

### ISSUE THREAD

**Issue by Sabryr** [swcarpentry/git-novice#476]
Comments for git-novice/_episodes/03-create.md
The initial steps of initiating  a Git repository  starts with creating the directory called planet and changing to it.
$ mkdir planets
$ cd planets

Without telling where the directories are created. I would suggest using pwd to find this out or move to the home directory first. 
To make things even confusing in the exercise following this, moves to the home directory and create a directory with the same name again. 
This is followed by initiating a Git repository in a subdirectory. My opinion is that first up exercise should not ask the student to do something not correct. This not only leads confusion for users who are new to Unix, also confuses Git new comers as fixing this error requires to introduce concepts discussed later on (i.e. gitignor).

**Comment by kekoziar** [comment]
Hi, @Sabryr.  Thanks for the comments.  The setup section (http://swcarpentry.github.io/git-novice/setup/) of the lesson indicates what home directory learners are working from.  

Regarding the exercise: I've taught Git a few times, and have not experienced learners being confused by introduced errors and how they are fixed; it is a common teaching technique.  I would be interested if my experience regarding this is common or an outlier.   However, I understand your comment with referring to something not yet introduced (i.e. gitignore).  What change do you suggest?

**Comment by kekoziar** [comment]
Issue resolved with PR #459
