### ISSUE TITLE
Pilotting the new GitHub labels

### ISSUE THREAD

**Issue by fmichonneau** [swcarpentry/git-novice#483]
@iglpdc @daisieh @nhejazi @kekoziar 

I added to the repository the proposed set of GitHub labels that we're planning to use across all repositories for the Carpentries. We are in a piloting phase and we want to start using them to see if adjustments are needed before we deploy them everywhere. We are going to test them first in a few repositories including this one until the end of the month. The goal is make it easier for people to contribute to the lessons by identifying more clearly which issues can be worked on, and the type of work that needs to be done, and to make it easier for you as a maintainer to sort through the issues and pull requests you receive.

It would be great if you could split among yourselves the issues that are currently in the repository and assign at least 2 labels for each: one in the "status" category, and in the "type" category. Depending on the context, you may also want to add the "bug-bbq", the "good first issue" or the "high-priority" labels.

Ideally, we'd like to remove the legacy labels by the end of the month as well, so issues with these old labels should be re-assigned new labels.

I'd like your feedback on how well these labels capture the type of issues that are currently in the repository, or that you have received in the past. If you feel that some labels don't capture the nature of the issue, or if the meaning of the labels is too unclear to make a call, I'd really like to hear about it.

The definition of the labels is available in this proposal: https://docs.google.com/document/d/1b3nIZ6N4IHY24JmLNQ5rkwUACEVS9Hls3auzZD7zHqk/edit

Feel free to ping me on Slack, by email or here if you have any questions or with your comments/feedback.

Thank you for your help with this!

**Comment by raynamharris** [comment]
Do only maintainers or people with write access have the ability to add labels?

**Comment by fmichonneau** [comment]
yes, only people with write access can add labels.

**Comment by rgaiacs** [comment]
> Do only maintainers or people with write access have the ability to add labels?

People with write access **to the repository**. We were suppose to call this people maintainers of the lesson. ;-)

This is a GitHub restriction. We can't do anything.

**Comment by iglpdc** [comment]
I think we're done. There is a couple of PRs that are hard to classify, but we will fix this soon, but I think the issues are in good shape now. 

@fmichonneau, I'm closing this. Feel free to reopen/make changes to the current labels.
