### ISSUE TITLE
Instructor Notes - reset instructions

### ISSUE THREAD

**Issue by allisongofman** [swcarpentry/git-novice#493]
It might be nice to include in the instructor notes the instructions for resetting the instructor's git directory and file structure from the sample dataset between lessons so that the live coding always looks like the students' screen. While it's not too difficult, it's easy to miss something and it would be helpful to have a checklist to ensure consistency. 

---

**Comment by iglpdc** [comment]
Thanks, @allisongofman ! What do you mean exactly by resetting the instructor's git directory?

**Comment by esmesh** [comment]
I second this, although I'd phrase it as: "The instructor notes should include starting setup assumptions for each lesson."

For example, [7 - Remotes in GitHub](http://swcarpentry.github.io/git-novice/07-github/index.html) assumes that we already have the planets/ local repo with mars.txt in it *and* that we have a GitHub account already created. It also assumes that we *don't* have a planets repo already in our GitHub account (i.e. if an instructor has taught this before, they may want to delete the GitHub repo so they don't confuse learners by creating "planets2", "planets3", ...).

**Comment by kekoziar** [comment]
Since the lesson creates the directories and repositories as needed and with the learners, why wouldn't instructors just delete directories and git repositories between lessons?
