### ISSUE TITLE
Address learning objective on Descriptive Commit Messages  - Lesson 4: Tracking Changes

### ISSUE THREAD

**Issue by infosleuth** [swcarpentry/git-novice#506]
One of the learning objectives for Episode/Lesson 4: Tracking Changes is "Distinguish between descriptive and non-descriptive commit messages." 

To help the lesson meet this objective, we could
- Add a specific heading for this section within the lesson, to make it more obvious for the learner
- Highlight some or all of the 7 recommendations from "Good Commit Messages" article, instead of just having a link to the article
- Move the challenge exercise "Choosing a Commit Message" closer to the section about writing good commit messages (e.g., just below the text,  "Good commit messages start with a brief (<50 characters) summary of changes made in the commit. If you want to go into more detail, add a blank line between the summary line and your additional notes."
- Specify in more detail, why each answer in the challenge exercise "Choosing a Commit Message" is descriptive or not, AND why it meets the Good commit messages criteria or not, plus refer the reader back to the Good commit messages article.

**Comment by iglpdc** [comment]
Closed by #510
