### ISSUE TITLE
Lesson 14 - No guidance for RStudio users when Git.exe path not pre-filled

### ISSUE THREAD

**Issue by richmccue** [swcarpentry/git-novice#507]
One thing I ran into while trying to complete "Lesson 14 - Supplemental: Using Git from RStudio"  (version 1.1.383) on a Windows 10 computer was that the Git executable path was not pre-filled for me.

I had to go looking for the git.exe file which was buried pretty deep in the file system "Tools" -> "Global options" -> "Git/SVN": 
C:/Users/rmccue/AppData/Local/GitHubDesktop/app-1.1.1/resources/app/git/cmd/git.exe 
![git-r-integratin](https://user-images.githubusercontent.com/581697/39550467-3becd1b2-4e16-11e8-8b39-c4eddbd94b60.png)

I'm not sure my problem was due to the configuration of my Windows 10 workstation (I didn't have any problems on my Mac laptop), but if not, it might be helpful to include instructions for Windows users on how to find their git.exe file as a linked resource for learners who get stuck. I'd be happy to work on those instructions if the community would find it useful/helpful.

Cheers,

Rich

**Comment by iglpdc** [comment]
Thanks, @richmccue ! I think it will be useful to have this included in the lesson, so people can solve the problem when follow the lesson at home.

Woudl you like to add the description of the fix (with the screenshot, if possible) to the lesson? As it seems to be something specific to Windows, you could do a callout called "Set the Git executable in Windows" or something like this.

**Comment by bencomp** [comment]
Was this issue fixed by #531 ?
