### ISSUE TITLE
Make 01-basics objective broader

### ISSUE THREAD

**Issue by iglpdc** [swcarpentry/git-novice#523]
The first episode is more a description of  "a" version control system, rather than of Git. I think that's useful as this is the first exposure of many learners to the concept. Also, the model based on diffs in not completely accurate for Git. A compromise to be both accurate and keep it simple could be to change the second objective to reflect this. So, what about?

```
Understand the basics of how Git works.
```
to 
```   
Understand the basics of how version control system work.
```

(See #519 for background)

**Comment by djsperka** [comment]
I'd agree with iglpdc on changing the second objective. That's more aligned with the actual content. I might offer another suggestion:

Understand the basic operations common to all version control systems.

**Comment by kekoziar** [comment]
Implemented in https://github.com/swcarpentry/git-novice/pull/715
