### ISSUE TITLE
Update maintainers list

### ISSUE THREAD

**Issue by iglpdc** [swcarpentry/git-novice#524]

**Comment by iglpdc** [comment]
Hi, @munkm ! Do you wanna add yourself to the maintainer list in the README?

**Comment by iglpdc** [comment]
Also, could we reorder the list, so it's alphabetical order?

**Comment by munkm** [comment]
Hi @iglpdc! I'd be happy to update it. I'm looking forward to working with you all.

**Comment by munkm** [comment]
I opened a PR rather than directly committing to the repo. For small fixes like that, generally do the maintainers commit directly to the repo or submit a PR?

**Comment by iglpdc** [comment]
Thanks! I usually do a PR that I merge myself if it's something trivial: maintaince, obvious typos, updates of the template,...
