### ISSUE TITLE
Lesson 3 - Expanded explanation of git init

### ISSUE THREAD

**Issue by leligdon** [swcarpentry/git-novice#526]
As one of the key points of the lesson is that git init initializes a repository, a second line of notes could be added to explain the git init command in more detail, specifically that the repo or “storage area” being initialized includes everything in the repository, i.e all files, sub-directories, and their files.  This could help prepare learners for the “Places to Create Git Repos” activity as well. 

While teaching the git init command, I find it helpful to 1) reiterate that the creation of the directory and the creation of the repo are two different and independent processes and 2) that initializing the repo includes everything included in it.   This is not explicitly stated, but maybe it should be?

**Comment by munkm** [comment]
These are great points to emphasize in this lesson @leligdon. Thanks for bringing them up. 

Your point about the .git directory tracking everything in the directory also helps to answer the lesson "question" highlighted at the start of the lesson. Would you be interested in submitting a pull request to address both points 1 and 2 that you brought up?
