### ISSUE TITLE
Git log example has extra options that aren't explained.

### ISSUE THREAD

**Issue by childers** [swcarpentry/git-novice#536]
Looking at: http://swcarpentry.github.io/git-novice/04-changes/index.html

I think that adding the --graph option is useful in general, but the fact that this is not explained and does not actually show anything understandable in the output took away from when I was working through this.  

---

 ```shell
 $ git log --oneline --graph --all --decorate
 ```

```shell
 * 005937f Discuss concerns about Mars' climate for Mummy (HEAD, master)
 * 34961b1 Add concerns about effects of Mars' moons on Wolfman
 * f22b25e Start notes on Mars as a base
```

---

Can this edited to remove --graph as an option?  If it would be more informative later, we can add it later with a description.

Alternatively, lets add callouts for all the other options listed so they aren't just dropped in with no explanation.

**Comment by rgaiacs** [comment]
> Alternatively, lets add callouts for all the other options listed so they aren't just dropped in with no explanation.

Could you add the explanation? Thanks in advance.

**Comment by juliambrosman** [comment]
Perhaps by callouts they mean explanations within the teaching materials about what each of those flags is doing?

I agree with the general comment.  The outputs of  ```git log --oneline``` and ```git log --oneline --graph --all --decorate``` are nearly identical at that point in the lesson which means the utility of one over the other is likely lost on learners.

The point would be stronger if the ```git log --oneline --graph --all --decorate``` was revisited in or moved to the Conflicts section of the lesson as the graph could look more interesting at that point.
