### ISSUE TITLE
Adding lesson on creating "github.io" - Lesson Contribution

### ISSUE THREAD

**Issue by sheraaron** [swcarpentry/git-novice#537]
Hello,

My name is TJ Nguyen, I am doing my checkout process after taking my training.

I would like to make a contribution to the Version With Git lesson in the Software Carpentry database. I was thinking maybe there could be a lesson on creating a github.io seeing as it could be useful for researchers that want to get there work/research online as a website or blog. There is also this program called Pelican which is python based used for creating websites/blogs. I could see this being a joint lesson with python and git. There are many benefits to knowing how to use these two things and maybe the carpenters could teach it.

I hope that was a good contribution and that maybe it is considered to be added.

Thank you,

TJ

**Comment by munkm** [comment]
Hi TJ!

Thanks for filing your first issue with the swc/git-novice. It's great to have new suggestions on the lessons. 

I personally think knowing how to build a webpage using github's infrastructure is super useful. I use my personal page regularly. 

That said, our [contributing.md](https://github.com/swcarpentry/git-novice/blob/gh-pages/CONTRIBUTING.md) cautions adding completely new lesson material to the swc lessons, i.e. : 
> Our lessons already contain more material than we can cover in a typical workshop, so we are usually not looking for more concepts or tools to add to them. As a rule, if you want to introduce a new idea, you must (a) estimate how long it will take to teach and (b) explain what you would take out to make room for it. The first encourages contributors to be honest about requirements; the second, to think hard about priorities.

In that sense, we should open this up for more discussion. I'm of the mind that you've suggested a really useful tool and it would be great if it could be taught to interested learners, but I'm not sure the swc/git-novice lesson is the right place for this content. Is there a part of the lesson that feasibly could be removed to add this new lesson? How long would it take to teach a gh-pages / rendering jekyll pages / previewing the webpage locally-themed lesson?

**Comment by sheraaron** [comment]
Hello!

I do agree that the content I proposed could be useful! For the time range I am not 100% sure, some colleagues and I are actually doing a workshop tomorrow to teach this kind of stuff (creating a github.io and using pelican to generate the website/blog). If you are interested I could take notes and we are actually planning on filming it if you are interested in seeing how it goes. This is our first workshop so it will allow us to work out any kinks and hopefully help contribute to the lesson so it could fit into swc (shortening length or removing any unnecessary material).

TJ's email is as follows: nguyentj@msu.edu

**Comment by munkm** [comment]
Hi @sheraaron. I'm going to close this issue because it is out of scope for this particular lesson. That said, I'm many in the carpentries community would love to hear a bit about how incorporating github.io into a lesson on git went for your workshop.
