### ISSUE TITLE
Incorrect solution to exercise about README

### ISSUE THREAD

**Issue by amaji** [swcarpentry/git-novice#541]
This is related to https://github.com/swcarpentry/git-novice/issues/422

The solution for the final exercise in section "Remotes in GitHub" says:
```
In this case, since we already had a README file in our own (local) repository, we’d see a merge conflict ...
```
However, we did not create a README file in the local repository as part of the lesson, therefore, this is incorrect. Merging (`push` or `pull`) with remote still fails due to "unrelated histories."

The exact error message is:
```
[git-lesson] $ git pull
fatal: refusing to merge unrelated histories
[git-lesson] $ git status
On branch master
Your branch and 'origin/master' have diverged,
and have 4 and 1 different commits each, respectively.
  (use "git pull" to merge the remote branch into yours)

nothing to commit, working tree clean
```
We can avoid this using the option `--alow-unrelated-histories`
```
[git-lesson] $ git pull --allow-unrelated-histories
Merge made by the 'recursive' strategy.
 README.md | 1 +
 1 file changed, 1 insertion(+)
 create mode 100644 README.md
```

**Comment by nhejazi** [comment]
Thanks for reporting this error. If you're interested in contributing the fix via a PR, feel free to submit one and we'll try to get it merged quickly; otherwise, just let us know and one of us maintainers will implement a version of the change you've given above.

**Comment by amaji** [comment]
@nhejazi Thanks for the note. I shall submit a PR by this weekend.

**Comment by amaji** [comment]
@nhejazi I submitted a PR. Please verify layout of the solution (i.e. the code blocks are properly nested inside solution block). Let me know if any changes are needed.
