### ISSUE TITLE
Fix anchor links to reference

### ISSUE THREAD

**Issue by sdsu-unrc** [swcarpentry/git-novice#544]
Hi, I'm submitting this as part of the instructor training checkout process.

It is kind of a small thing, but I noticed that links in the lesson to the reference page (<https://swcarpentry.github.io/git-novice/reference>) are broken.  I think this is because they use html anchor tags and the tags on the reference page are either missing or not configured to match the calls.

Example--in the <https://swcarpentry.github.io/git-novice/04-changes/index.html> section the line just before the Staging Area section has:

To allow for this, Git has a special staging area where it keeps track of things that have been added to the current changeset but not yet committed.  In markdown the "changeset" link looks like

[changeset]({{ page.root }}/reference/#changeset)

which appears in html as <https://swcarpentry.github.io/git-novice/reference/#changeset>
 
which gives a page not found.

Since this seems like not a too difficult fix, I'd be willing to submit a pull request and try to do the fix as a learning exercise for myself.

Thanks,

Brian Moore (sdsu-unrc)

**Comment by munkm** [comment]
Hi Brian, 

This is a great catch! Thank you for being so thorough in your issue. If you're willing to submit a Pull Request with a fix we'd really appreciate it! Let me know if you have any questions regarding the fix, I'd be happy to work with you on it.

The reference page does appear to have working links (such as the link to `changeset` from the definition for `commit`, for example) so I suspect that you can use those as a guide for the fix.

**Comment by sdsu-unrc** [comment]
Madicken,

thanks for the reply.  I may have some dumb questions, as this would be my first pull (and possible merge).

The first thing to do is fork (I'm reading CONTRIBUTING.md).
Then I work on that, and then make the pull request after I have a proposed fix, right?

Brian

--
Brian Moore, Research High Performance Computing Specialist
University Networking and Research Computing (UNRC)
SOHO  206A, Box 2201, Brookings, SD  57007
brian.moore@sdstate.edu
605.688.4679 (wk) / 605.521.3062 (cell)

________________________________________

**Comment by sdsu-unrc** [comment]
I think I am ready to do a pull request.  Note I have so far worked in my forked copy of the gh-pages branch.  I did create a new branch locally, but I could not figure out how to get the pages to render on github, which I needed to do to check and see if the links were working.  (I also tried to build locally with the make commands, but that looks challenging right now ... )

As for the edits, here is what I have done: after some experimentation, I find that if I replace /# with just # in these links, they work.
For example, in 01-basics.md, replaced

[commit]({{ page.root }}/reference/#commit))
with
[commit]({{ page.root }}/reference#commit))

I did a grep on all the .md files in _episodes and replaced all that I found.
Also there was one instance in index.md at top level.

**Comment by sdsu-unrc** [comment]
Ok, pull request is [545](https://github.com/swcarpentry/git-novice/pull/545)
I created a new branch after I had made the changes in my gh-pages branch, and then I did the pull request with that.  That was based on looking at the other pull requests.

**Comment by sdsu-unrc** [comment]
Just a comment; I see now how building the pages locally is in fact very easy.
For me the magic bullet was gem install bundler jekyll, which, since it is step one on the jekyll page, is kind of obvious.  But that makes it a lot easier to do edits.

**Comment by munkm** [comment]
Hey @sdsu-unrc, you did a great job on your PR! I see I'm getting to a few of your questions a little bit late, but you've figured everything out. Thank you so much for your contribution!
