### ISSUE TITLE
line lengths

### ISSUE THREAD

**Issue by tkphd** [swcarpentry/git-novice#548]
`make lesson-check-all` flags the following:

- [ ] `./CONTRIBUTING.md: Line(s) are too long: 18`
- [ ] `./README.md: Line(s) are too long: 1, 2`
- [ ] `./_episodes/01-basics.md: Line(s) are too long: 20, 27, 28, 45, 60, 61, 64, 70, 73, 74`
- [ ] `./_episodes/02-setup.md: Line(s) are too long: 32, 72, 73, 82, 83, 84, 85, 86, 97, 99, 138`
- [ ] `./_episodes/03-create.md: Line(s) are too long: 32, 106, 147, 155`
- [ ] `./_episodes/04-changes.md: Line(s) are too long: 52, 162, 168, 169, 709`
- [ ] `./_episodes/04-changes.md:61: Unknown or missing code block type None`
- [ ] `./_episodes/05-history.md: Line(s) are too long: 94, 486, 494`
- [ ] `./_episodes/06-ignore.md: Line(s) are too long: 106, 215, 243, 250, 252`
- [ ] `./_episodes/07-github.md: Line(s) are too long: 220, 222, 224, 237, 247, 269, 275, 276, 280, 294`
- [ ] `./_episodes/09-conflict.md: Line(s) are too long: 136, 163`
- [ ] `./_episodes/09-conflict.md:424: Unknown or missing code block type None`
- [ ] `./_episodes/10-open.md: Line(s) are too long: 79`
- [ ] `./_episodes/11-licensing.md: Line(s) are too long: 76`
- [ ] `./_episodes/12-citation.md: Line(s) are too long: 31, 49, 52`
- [ ] `./_episodes/12-citation.md: Line(s) end with whitespace: 53`
- [ ] `./_episodes/12-citation.md:51: Unknown or missing blockquote type None`
- [ ] `./_episodes/13-hosting.md: Line(s) are too long: 86`
- [ ] `./_extras/discuss.md: Line(s) are too long: 10, 12, 127`
- [ ] `./_extras/discuss.md: Line(s) end with whitespace: 458`
- [ ] `./_extras/guide.md: Line(s) are too long: 40`
- [ ] `./aio.md: Unexpected metadata`
- [ ] `./reference.md: Line(s) are too long: 8, 11, 13, 58, 65, 66, 67, 68`

**Comment by kekoziar** [comment]
Thank you for your submission. Since an updated version of the lesson style has been implemented, fixing much of the original problem this issue addressed, this issue will now be closed.
