### ISSUE TITLE
Some exercises in 05-history should be modified

### ISSUE THREAD

**Issue by djsperka** [swcarpentry/git-novice#557]
The exercises in this episode should be modified. I submitted a pull request with a new solution and a modified solution to two exercises. Those exercises are good, I think.  

Two of the exercises, "Reverting a commit" and "Getting Rid of Staged Changes", cover fairly important topics (and are probably fairly commonly needed), and I think they should really be turned into their own section in the lesson itself. 

The "revert" question covers a command (git revert) that is never discussed in the lesson. 

The "Getting Rid of Staged Changes" question is a good question, but I think it might be better if folded into the discussion of the staging area. The operation described in the question is a very important one - and should help understanding the difference between the repository, the staging area, and the working directory. 

I wonder (much bigger topic) whether the title of this episode is the right title. We're really not exploring history in this section - an in depth discussion of "git log" would do that. 

---

**Comment by kekoziar** [comment]
Thank you for contributing. Merged PR.
