### ISSUE TITLE
Clarifying 'conflict' in lesson 01

### ISSUE THREAD

**Issue by JoaoRodrigues** [swcarpentry/git-novice#567]
Hi there,

I have the feeling this might be nitpicking at the wording on the first lesson - `01-basics` - but a git conflict is a concept I've had trouble explaining to people. Also my first issue here, so sorry if it indeed is nitpicking.

In the first lesson, about halfway, there is a mention to conflicts in `git` without ever defining what a conflict is;
>Unless there are conflicts, you can even incorporate two sets of changes into the same base document.

Would it be a good idea to extend a bit the sentence, in the context of the analogy, and explain what a conflict is? e.g.,
>Unless multiple users make changes to the same section of the document - a conflict - you can incorporate the different sets of changes into the same base document.

My reason for this change is that resolving conflicts will be something that people have to face when using `git`. Introducing the concept this early is good and framing it in the context of the paper-writing analogy can help people remember later on. Happy to make a PR if that's the case.

On a related note, has there been a suggestion to keep the analogy as a paper writing exercise instead of switching to the Wolfman/Dracula space story? Or is the story there for a particular reason?

Cheers and thanks for the great material,

João

**Comment by JoaoRodrigues** [comment]
Hi @munkm ,

Thanks! PR #568 should address the change. Hope it's all OK.

Thanks also for the reference to #277. I see it's been discussed indeed! I didn't mean to add more to the tutorial (definitely not LaTeX :)) but instead have the same structure of text files and changes to them but make it more 'academic'-themed. I'll pitch my idea in the other issue, although it seems there has been a ton of discussion and ideas.

**Comment by munkm** [comment]
Thanks for the PR João! Your issue and PR a great first contribution to the carpentries! Thank you so much. 🎆 🎉 🎈 🎆
