### ISSUE TITLE
Unix Shell Pipes and Filters uniq command

### ISSUE THREAD

**Issue by sjmillerAZ** [swcarpentry/git-novice#576]
Please delete the text below before submitting your contribution. 

---

Elaborate on the Answer to the question: Why Does uniq Only Remove Adjacent Duplicates?

There is a hint to think about very large data sets, but that's not enough for me to come up with the answer.

---

**Comment by kekoziar** [comment]
Posted in the wrong repository. This issue refers to the [Shell-Novice](https://github.com/swcarpentry/shell-novice) lesson.
