### ISSUE TITLE
Wording in Lesson 5 —> Exploring History —> Version Control with Git

### ISSUE THREAD

**Issue by seanemccartney** [swcarpentry/git-novice#577]
The wording in the last “Solution” section reads strangely. 
I feel it should read: The answer is 2 because “git add venus.txt” was written before the line “Venus is too hot to be suitable as a base” was appended, which was lost when git checkout was executed. Using the flag -a with git commit would have prevented the lost.

I also think it would benefit the same lesson (lesson 5 —> Exploring History —> Version Control with Git) by including Solutions to the questions, “Recovering Older Versions of a File” and “Reverting a Commit”.

Thanks!

**Comment by kekoziar** [comment]
Will you open separate issues with proposed solutions for “Recovering Older Versions of a File” and “Reverting a Commit”

**Comment by kekoziar** [comment]
Thanks for the suggested change to "Understanding Workflow and History." I think it would read better if the word written was changed to executed or used. A git command isn't written, it's executed.  Also, maybe say "appended to the file" to be clear.  What do you think?

**Comment by kekoziar** [comment]
PR556 added and updated wording for solutions referenced here.
