### ISSUE TITLE
"config --edit" to both check editor config & configure more conveniently

### ISSUE THREAD

**Issue by katrinleinweber** [swcarpentry/git-novice#579]
Would it make sense to update the section https://github.com/swcarpentry/git-novice/blame/0f775ae563a09163984e134b068d56928104ee29/_episodes/02-setup.md to something like:

> Let's test and review the settings we made just now. Type `git config --global --edit` to open your git configuration in the text editor that you just configured.

Related to https://github.com/swcarpentry/git-novice/issues/360, because it could prepare learners for switching between CLI & editor during git operations.

**Comment by tkphd** [comment]
Possibly useful, as it teaches an alternative entry point into the config.
In a workshop I taught last week, I did something similar: to teach that the config is just a file, I had students `nano ~/.gitconfig` to see the options we had just set. This also applies to local `.git/config` files.

As a test to make sure the config was successful, so helpers can address misconfigurations, this would make sense. On the other hand, committing ourselves and our helpers to resolve configuration difficulties with the myriad possible editors might be a distracting scope creep for this lesson.

**Comment by katrinleinweber** [comment]
Cool, thanks for sharing your teaching example :-) About "distracting": Would #671 help reduce that risk in your view?

However, since our [only](https://github.com/swcarpentry/git-novice/blame/04ffeff2715ba95433751f6bb0b2df978d6ed3af/_episodes/02-setup.md#L27-L28) [config](https://github.com/swcarpentry/git-novice/blame/04ffeff2715ba95433751f6bb0b2df978d6ed3af/_episodes/02-setup.md#L74-L76) instructions are crucial for the rest of the lessons, helpers will have to debug problems anyway, won't they? IMHO, this is a question of cleverly ordering instructions and checks so that errors do pop-up as quickly as possible.
