### ISSUE TITLE
Add line to exit running process after git config --help

### ISSUE THREAD

**Issue by arockenberger** [swcarpentry/git-novice#580]
Hei!

I've been recently going through the Git lesson again; at the end of `02-setup` when [Git Help and Manual](https://github.com/swcarpentry/git-novice/blob/gh-pages/_episodes/02-setup.md#git-help-and-manual) are introduced, I always find it hard to remember on spot how to exit the enormously long manual. Adding a line in the lesson with "press 'q' for exiting the manual" would be extremely helpful. 
Especially, since you exit a process in a command line environment depending on system, version etc. with either ctrl+q, ctrl+c, ctrl+x or any of these keys without ctrl!

Cheers,

Annika

**Comment by munkm** [comment]
Hi Annika! Thanks for the issue. This is a great thought. A sentence explaining that the `:` in the shell is a prompt waiting for commands and that `q` will exit would certainly be helpful. At this point in a carpentry lesson learners should have learned about navigating in the manual pages of shell commands, but a helpful reminder would be a beneficial addition to the callout box in this section.

**Comment by arockenberger** [comment]
Hei Madicken!
Thanks for the reply!
When you write "At this point in a carpentry lesson learners should have learned about navigating in the manual pages of shell commands" it assumes that one always teaches Unix Shell + Git + Python/R etc. in one workshop. – Even though it deviates from the official Carpentries model, we here at @uio-carpentry teach the lessons individually (it's easier for our researchers & students to join a half-day or one day workshop than a two-day one) and then these small issues can create a lot of confusion as well as frustration. This holds true for those re-visiting the Carpentries material for self-study or after a workshop. I would definitely add a line with a reminder :)

**Comment by munkm** [comment]
This issue has been resolved via swcarpentry/git-novice#678 

@arockenberger if you feel the lesson might be improved by adding this type of callout elsewhere, feel free to reopen the issue.
