### ISSUE TITLE
Collaborating episode references forking without explaining it

### ISSUE THREAD

**Issue by kerchner** [swcarpentry/git-novice#584]
_episodes/08-collab.md references forking in the solution to the first challenge (`On GitHub, the Collaborator can go to their own fork of the repository` etc.) without ever previously mentioning forking, unless I am missing something (if I just missed this, please let me know!)

I would be glad to submit a PR with content to rectify this, but would first want to hear others' thoughts on whether forking should or should not be in the scope of this lesson.

**Comment by munkm** [comment]
Hi @kerchner. Thank you for your issue! This is a great catch. Lesson 08 describes a workflow where vlad gives wolfman collaborator access (and thus push permissions) to their repository at github.com/vlad/planets.git, so a fork doesn't actually exist when two learners are working together in this example. The diagram earlier in the lesson shows both wolfman and vlad's computers pointing to the same remote. The solution in this section should be revised to not mention forks at all but rather have whoever is the collaborator navigate to the owner's repository on github and inspect the commits there.  If you would be interested in submitting a PR, that would be great!
