### ISSUE TITLE
Consider tagging a new release so that Zenodo picks it up

### ISSUE THREAD

**Issue by kerchner** [swcarpentry/git-novice#585]
_episodes/13-hosting.md references this (git-novice) repository as an example of a repository connected to Zenodo.  However, the DOI is for the only release of this repository, which dates back to 2016.  We may want to consider periodically tagging releases, so that Zenodo detects these and archives them.  Especially for this particular lesson, since it's about Git/Github.

**Comment by munkm** [comment]
This is a great point @kerchner. I'm tagging @fmichonneau to weigh in on this.

**Comment by fmichonneau** [comment]
Most of our lessons are due for a release. We'll discuss our plans for this at the February maintainer's meeting.

**Comment by munkm** [comment]
Ok great thanks @fmichonneau! I'm going to leave this open until our next release unless another maintainer weighs in with a differing opinion.

**Comment by kekoziar** [comment]
The new release was pushed to Zenodo in 2019.  https://zenodo.org/record/3264950
