### ISSUE TITLE
Venus line added to mars.txt in Episode 04, but not present in Episode 05

### ISSUE THREAD

**Issue by zingale** [swcarpentry/git-novice#596]
In Episode 04, in the "Committing Multiple Files" section, we add the line:
```
Maybe I should start with a base on Venus.
```
to `mars.txt` and then commit this.  

But in the next episode (05), when we look at `mars.txt` and add more to it, that line about Venus is missing.  This seems inconsistent and can confuse following all the commands as they read along.

**Comment by kekoziar** [comment]
"Committing Multiple Files" is an exercise.  The exercises used change depending on the instructor/workshop, so any changes to files in the exercises aren't necessarily reflected in the regular lesson text.

**Comment by zingale** [comment]
okay.  That makes sense.
