### ISSUE TITLE
spaceships in Episode are added but never committed.

### ISSUE THREAD

**Issue by zingale** [swcarpentry/git-novice#597]
In Episode 4, we do the following:
```
$ touch spaceships/apollo-11 spaceships/sputnik-1
$ git status
$ git add spaceships
$ git status
```
but we never commit this.  This leaves these files in the staging area.  Later as we add more to the repo, we never discuss these uncommitted files.  Perhaps they should just be committed after adding here?

**Comment by kekoziar** [comment]
This makes sense.  Would you like to make the change and submit a PR?
