### ISSUE TITLE
image in episode 3 has images of wrong planets

### ISSUE THREAD

**Issue by dmnielsen** [swcarpentry/git-novice#599]
I was reading through the git lesson and I saw that the image (motivatingexample.png) in Ep 3: Creating a repository has planets labeled "Mars" and "Pluto." The pictures shown are Venus and Neptune. This is a small issue that doesn't interfere with the lesson content, but as a former astronomer and a pedant, I could _not_ say something.

**Comment by kekoziar** [comment]
Good catch. It's more the image has the wrong pictures than they are labeled incorrectly, since the lesson is about a mission to Mars, and one of the examples uses Pluto.

**Comment by dmnielsen** [comment]
You're right, the pictures are incorrect, not the labels. I updated the title to reflect this

**Comment by charlesincharge** [comment]
pull request opened

**Comment by joenio** [comment]
I guess this issue solved, maybe could be closed?

**Comment by dmnielsen** [comment]
The image has been updated with the correct planets. Closing the issue
