### ISSUE TITLE
Lesson 5: No solution listed for “Reverting a Commit” exercise

### ISSUE THREAD

**Issue by chennesy** [swcarpentry/git-novice#603]
The _Reverting a Commit_ exercise in the [Exploring History section](http://swcarpentry.github.io/git-novice/05-history/index.html) does not currently have a _Solution_ section. This exercise is a fill-in-the-blank question, and some students might guess any number of incorrect answers based on commands learned during the lesson above (`git diff, git status`). It would be helpful, then, to provide a solution along with a brief explanation. Here’s a proposed solution:

Jennifer could look at the project’s history of commits, including full identifiers with:
`git log`

For a shorter list, with short identifiers for each commit, she could use:
`git log --oneline`

If Jennifer is sure her last commit to the repository was the most recent commit by the group, she could also find the commit identifier by looking at the repository’s HEAD:
`git show HEAD`

**Comment by brainwane** [comment]
My learner just ran into this and it caused a lot of confusion.

**Comment by kekoziar** [comment]
Solution merged #675
