### ISSUE TITLE
"forge" is a word many people don't know, especially non-native english speakers

### ISSUE THREAD

**Issue by steltenpower** [swcarpentry/git-novice#606]
"forge" and "forges" are in _episodes/13-hosting.md

Googling for the meaning gives me multiple options of which I don't know which to choose, which is why I was not able to make a pull request

**Comment by kekoziar** [comment]
@steltenpower, Thanks for pointing this out. I don't use the term forge when referring to hosting options, (other than within the name SourceForge). Here is a [wiki entry](https://en.wikipedia.org/wiki/Forge_(software)) regarding this context of forge.

**Comment by kekoziar** [comment]
I think using the term "server" might bring pushback from folks who are precise, since usually hosting services are supported by multiple servers.  Perhaps "hosting service" instead of forge, a link to the wiki page, or both?

**Comment by kekoziar** [comment]
conversation abandoned.
