### ISSUE TITLE
Workflow clarity in Collaborating and Conflicts

### ISSUE THREAD

**Issue by esmesh** [swcarpentry/git-novice#609]
The end of [8 - Collaborating](http://swcarpentry.github.io/git-novice/08-collab/index.html) includes a "Basic Collaborative Workflow". A visual representation of this that connects the actions and commands to the learner's mental model (working, staging, local repo, remote) would be very helpful.

I'd suggest a variant of the diagram in [9 - Conflicts](http://swcarpentry.github.io/git-novice/09-conflict/index.html) that shows an individual's basic workflow. The diagram in Conflicts can then be updated to have order (i.e. a conflict is a race condition - both pull, both edit, one pushes before the other) **and** make it clear what is impacted at each step (local repos, working copies, or remote).

Similarly, when the workflow is referenced again with respect to minimizing conflicts at the end of lesson 9, there should be a clear distinction between individual workflow best practices vs. common group practices -- all of which are process/project management related (the lesson refers to the individual workflow practices as "technical approaches").

**Comment by kekoziar** [comment]
@esmesh, thanks for the feedback.  We are always looking to improve the lesson. 

Can you clarify the diagram you're referring to in [episode 9](http://swcarpentry.github.io/git-novice/09-conflict/index.html)? The only diagram in that episode show a merge conflict, not an individual's basic workflow; I don't think that diagram lends itself to describing an overall workflow, but it could be that I just need to see it created by someone.  Feel free to create and submit a PR for a visual aid demonstrating the collaborative workflow.

**Comment by esmesh** [comment]
I think I was referring to adding something like the episode 9 diagram into the episode 8 "Basic Collaborative Workflow" section - for consistency and so the the episode 9 visualization would then build on the one from episode 8. (It's been a long time since I looked at this.)

**Comment by kekoziar** [comment]
> I think I was referring to adding something like the episode 9 diagram into the episode 8 "Basic Collaborative Workflow" section - for consistency and so the the episode 9 visualization would then build on the one from episode 8. (It's been a long time since I looked at this.)

I understand, @esmesh.  Thanks for the clarification!

**Comment by erinmgraham** [comment]
Hi @esmesh, 
Thank you for your contribution to the git-novice repository. We noticed that this issue has been inactive since 2021, and although it's been labelled help wanted, no one else has taken it up. To keep our repository clean and focused, we are closing this issue for now.

If you believe this issue still needs attention, please feel free to reopen it or create a new one with updated details.

Thank you for your understanding and support!
