### ISSUE TITLE
June 2019 Lesson Release checklist

### ISSUE THREAD

**Issue by fmichonneau** [swcarpentry/git-novice#611]
If your Maintainer team has decided not to participate in the [June 2019 lesson release](https://carpentries.topicbox.com/groups/maintainers/T61c75ac1a8a89538/timeline-and-process-for-june-lesson-release), please close this issue.

To have this lesson included in the 18 June 2019 release, please confirm that the following items are true:

- [x] Example code chunks run as expected
- [x] Challenges / exercises run as expected
- [x] Challenge / exercise solutions are correct
- [x] Call out boxes (exercises, discussions, tips, etc) render correctly
- [x] A schedule appears on the lesson homepage (e.g. not “00:00”)
- [x] Each episode includes learning objectives
- [x] Each episode includes questions
- [x] Each episode includes key points
- [x] Setup instructions are up-to-date, correct, clear, and complete
- [x] File structure is clean (e.g. delete deprecated files, insure filenames are consistent)
- [x] Some Instructor notes are provided
- [x] Lesson links work as expected

When all checkboxes above are completed, this lesson will be added to the 18 June lesson release. Please leave a comment on carpentries/lesson-infrastructure#26 or contact Erin Becker with questions (ebecker@carpentries.org).

**Comment by kekoziar** [comment]
@iglpdc @daisieh  @munkm @nhejazi   I think we can work through the checklist for the lesson as it currently stands.  The question is can we address/incorporate #277 before the deadline?

**Comment by munkm** [comment]
I think we should wait to do #277 until we hear back from the CAC.

**Comment by munkm** [comment]
For *Lesson links work as expected* issues swcarpentry/git-novice#618, swcarpentry/git-novice#619, swcarpentry/git-novice#620, and swcarpentry/git-novice#622 were created.

**Comment by kekoziar** [comment]
For lesson **Example code chunks run as expected**, some of the output has changed due to either changes in the lesson, git base code, or github responses.  Issues #621, #623, #624, #625, #626, and #627 were created in response, detailing the issue and specifying the updated needed, sometimes with verbatim code.

**Comment by munkm** [comment]
For **Each episode contains key points** issues swcarpentry/git-novice#629 and swcarpentry/git-novice#630 were created. However, all episodes currently do have key points so this isn't a blocker for the lesson release.

**Comment by munkm** [comment]
For *Each episode includes learning objectives* issue swcarpentry/git-novice#631 was opened. However, all episodes currently have learning objectives so this issue isn't a blocker for the lesson release.

**Comment by kekoziar** [comment]
For **Challenges / exercises run as expected** and **Challenge / exercise solutions are correct**, issues #632, #633, #634, #635, #636 were opened.  All other exercises and solutions run and are correct.

**Comment by kekoziar** [comment]
I checked **Call out boxes (exercises, discussions, tips, etc) render correctly**.  Currently, they all render correctly; however, parts of the lesson that change from issues opened as a result of process should be rechecked.  So, this checkbox will remain unchecked until after issues have been processed and completed, allowing a last check for proper rendering.

**Comment by kekoziar** [comment]
Home stretch.

**Comment by kekoziar** [comment]
I rechecked **Call out boxes (exercises, discussions, tips, etc) render correctly**.  All is well.  Yay!

Per @ErinBecker's email, we leave this issue open so she and @fmichonneau know it's an opted-in lesson.

**Comment by ErinBecker** [comment]
Awesome work @swcarpentry/git-maintainers  and everyone else who contributed! This is just a quick message confirming that this lesson will be included in the release that @fmichonneau and I are preparing this week. The release is scheduled to go through on the 18th and to be announced to the community on the 24th. Please let us know if you have any questions! And congratulations again!

**Comment by fmichonneau** [comment]
lesson released! :tada: https://doi.org/10.5281/zenodo.3264950
