### ISSUE TITLE
Include vscode as a text editor 

### ISSUE THREAD

**Issue by TrevorLeeCline** [swcarpentry/git-novice#613]
I use vscode, and I notice VS code isn't part of [the table](https://github.com/swcarpentry/git-novice/blame/811686a57238d1820df21a15c2f60692cc34ad7f/_episodes/02-setup.md#L76-L90) in episode 2, set-up. I believe it's a fairly popular text editor, worthy of including in the table. I will submit a pull request to add vscode as a default text editor for git.

**Comment by nhejazi** [comment]
Thanks for this. You're right that VS Code is quite popular so it makes sense to include it in our list.
