### ISSUE TITLE
Lesson 01-basics: Exercise is missing solution

### ISSUE THREAD

**Issue by gassmoeller** [swcarpentry/git-novice#615]
I noticed that the exercise in lesson 01-basics does not have a solution, while most other exercises do (http://swcarpentry.github.io/git-novice/01-basics/index.html). I realize these are very basic questions, but I think for learners without experience in using the 'Track changes' option in Microsoft Word or LibreOffice Writer the answer is not obvious.

For reference the questions in the exercise are:

- Imagine you drafted an excellent paragraph for a paper you are writing, but later ruin it. How would you retrieve the excellent version of your conclusion? Is it even possible?

- Imagine you have 5 co-authors. How would you manage the changes and comments they make to your paper? If you use LibreOffice Writer or Microsoft Word, what happens if you accept changes made using the Track Changes option? Do you have a history of those changes?

And I propose to add a solution along the lines:
- Recovering the excellent version is only possible if you created a copy of the old version of the paper. The danger of losing good versions lead to the problematic workflow illustrated in the PhD Comics cartoon at the top of this page.
- Collaborative writing with traditional word processors is cumbersome. Either every collaborator has to work on a document sequentially (slowing down the process of writing), or you have to send out a version to all collaborators and manually merge their comments into your document. The 'track changes' or 'record changes' option can highlight changes for you and simplifies merging, but as soon as you accept changes you will lose their history. You will then no longer know who suggested that change, why it was suggested, or when it was merged into the rest of the document.

If you think this would be a useful addition I am happy to create a pull request. In that case let me know if you want anything changed compared to my suggestion above. Thanks for maintaining an awesome course!

**Comment by munkm** [comment]
Hi @gassmoeller! I like the solutions you've proposed here and I agree that without using Word it's not evident what would happen when changes are accepted. For example, a GoogleDocs user might have a different experience with equivalent tools. We'd really love to get a PR if you're happy to make one! 

One minor cc: I might change the wording slightly of the first bullet from `versions lead to the problematic...` to `versions often leads to the problematic...`

**Comment by gassmoeller** [comment]
Hi @munkm! Thanks for reviewing :+1:. I included your suggested change, and added one sentence about online word processors (as they become more common for many students) in #643.

**Comment by munkm** [comment]
You rock! Thanks for submitting the PR!
