### ISSUE TITLE
Link to ssh tutorial by Bitbucket no longer helpful 

### ISSUE THREAD

**Issue by munkm** [swcarpentry/git-novice#619]
In lesson 07 Remotes with Github there is a callout box *HTTPS vs SSH* linking to tutorials on setting up SSH keys for Github, Bitbucket, and Gitlab. The Bitbucket page now has no content, so this [link](https://github.com/swcarpentry/git-novice/blame/gh-pages/_episodes/07-github.md#L83) needs to be updated.

**Comment by slel** [comment]
Updated link at #628.
