### ISSUE TITLE
Introduction seems to be biased towards collaboration

### ISSUE THREAD

**Issue by petebachant** [swcarpentry/git-novice#63]
Just an observation that from the first paragraph users may not realize that version control can be useful for working alone as well as with a team. Though it is essentially mentioned later in the first bullet point:

>Nothing that is committed to version control is ever lost. This means it can be used like the "undo" feature in an editor, and since all old versions of files are saved it's always possible to go back in time to see exactly who wrote what on a particular day, or what version of a program was used to generate a particular set of results.

It is also mentioned in chapter 1, but may have a place in the introduction. Some examples that may motivate the usefulness of version control beyond collaborating:

  * Not testing a piece of software after every change, so 20 commits down the road it may be inexplicably broken. Being able to check out and test each commit is helpful for identifying the problem. 
  * Trying to achieve manual version control by saving multiple versions of files with different names.

**Comment by daisieh** [comment]
While it's true that version control is great even when working alone, I find that for me personally, the benefits are self-explanatory after I've used it in collaboration. Like, even though I knew, when I first started writing code again after a five year hiatus, that I probably should look into some sort of version control, I didn't actually bother until I wanted to collaborate with others, and now I use it all the time even for my own work.

I think that for a lot of novices, vc won't be that useful for the latter case you mention: we had a moment in the workshop I was teaching last week where someone asked if they could use Git for their Word manuscripts, and I think we de-motivated her a bit when I said that you probably wouldn't want to use Git for that.

**Comment by lwjohnst86** [comment]
I agree with @petebachant, the introduction is heavily focused on collaboration. See my pull request regarding a possible addition: https://github.com/swcarpentry/git-novice/pull/107.

I want to expand on this. I think it would be a great disservice to SWC to _not_ mention the role that version control systems would play in solo researchers lives. I myself am one and I use git extensively, especially given that I am _very_ paranoid about losing data/work. A day of working on my data analysis scripts would be a major setback for me (I feel anyway), so having everything under git and also pushed to GitHub or BitBucket eases my paranoia.

At least within many of my fellow graduate students/researchers, most are fairly solo researchers when it comes to their data analysis. Biomedical sciences with respect to modern approaches to computational research practices is (in my experience) lagging behind that in other areas. And there are a lot of biomedical researchers out there, and by not at least mentioning git's role in solo researchers lives makes it seem like they wouldn't benefit.

Also, regarding @daisieh comment on Word and Git... I don't think we should be dismissive of using Git with Word. I agree that the power of git really shines with plain text and I believe plain text is the way to go for researchers everywhere, we still live in a world where Microsoft is dominate in all aspects of computing life. They should still be encouraged to use Git even though they use Word (as much as I dislike Word...).

**Comment by iglpdc** [comment]
Hey, I just merged PR #107 by @lwjohnst86 addressing this issue. 

@petebachant, @daisieh do you think it's better now? Should we close this issue now?

**Comment by petebachant** [comment]
:thumbsup: @lwjohnst86 addressed it quite well.
