### ISSUE TITLE
Episode 5 - Exploring History: Exercise Understanding Workflow and History

### ISSUE THREAD

**Issue by kekoziar** [swcarpentry/git-novice#632]
The current solution to "Understanding Workflow and History" can lead to confusion in a novice learner, especially since the last sentence "The working copy still has the second line (and git status will show that the file is modified)." makes it seem as if the current version of `venus.txt` has two lines in it; it does not.

This is a clearer answer:

The answer is 2.

The command `git add venus.txt` places the current version of `venus.txt` into the staging area. The changes to the file from the second `echo` command are only applied to the working copy, not the version in the staging area.  

So, when `git commit -m "Comment on Venus as an unsuitable base"` is executed, `venus.txt` committed to the repository is the version from the staging area and has only one line. 

At this time, the working copy still has the second line (and `git status` will show that the file is modified).  However, `git checkout HEAD venus.txt` replaces the working copy with the most recently committed version of `venus.txt`.  

So, `cat venus.txt` will output `Venus is beautiful and full of love`.

**Comment by munkm** [comment]
Resolved via swcarpentry/git-novice#648!
