### ISSUE TITLE
Episode 5 - Exploring History: Exercises Checking Understanding of git diff & Explore and Summarize Histories

### ISSUE THREAD

**Issue by kekoziar** [swcarpentry/git-novice#633]
This exercise needs to be updated.
~~~
Consider this command: git diff HEAD~3 mars.txt.
~~~

this command will return a log.  The purpose of this exercise is to force a `fatal` response due to out of range request.  The number `3` should be changed to something higher, so it's obvious the request is out of range.

This error is also in the next exercise, "Explore and Summarize Histories".  `git log --patch HEAD~3 *.txt` should be updated to a higher number to force a `fatal` response.

**Comment by hugedata** [comment]
The question is how big this number has to be to force a fatal response. Something like 20 will do. I played a bit with git log, and even if it found only 11 versions in my repository with 

  git log mars.txt

the command failed only when

  git diff HEAD~17 mars.txt

but was OK until git diff HEAD~16 mars.txt

I have hard time explaining this behaviour.

    Best,
    Dimitri Bourilkov

**Comment by hugedata** [comment]
Looks like git log mars.txt only shows revisions which affected mars.txt, not revisions where other files were added and/or modified. With 

git rev-list --all

I see 19 revisions in total which is slightly more than 17.

In any case if we count the total number of revisions nrev with  git rev-list --all | wc and choose a number greater than this, we are sure that  git diff HEAD~<nrev+1> mars.txt will fail.

   Best,
   Dimitri Bourilkov

**Comment by kekoziar** [comment]
Higher increment (`head~9`) changed in PR #638.  This should be high enough for self-learners and most instruction.  Hopefully, if an instructor teaching a workshop adds many more commits during the lesson, they will remember they need to go +1 over the number of commits when asking the learners to consider this thought exercise. 

Thank you, @umihoshijima for the PR.  Thank you @hugedata for your input regarding this issue.

**Comment by munkm** [comment]
This isn't necessary for the lesson release, but maybe we should consider mentioning the +1 over the number of commits to trigger this event in the instructor notes.
