### ISSUE TITLE
Link to list of issues for Software Carpentry doesn't seem to work

### ISSUE THREAD

**Issue by craigca** [swcarpentry/git-novice#637]
In the "What to Contribute" section of CONTRIBUTING.md (https://github.com/swcarpentry/git-novice/blob/gh-pages/CONTRIBUTING.md#what-to-contribute), the link to the list of issues for Software Carpentries doesn't seem to work. For me, it goes to a page with the message "404 This is not the page you were looking for".

**Comment by kekoziar** [comment]
Can you verify which link to which you are referring? All of the links in that section work for me

**Comment by kekoziar** [comment]
Thanks for double-checking!
