### ISSUE TITLE
All-in-one-page broken

### ISSUE THREAD

**Issue by iamc** [swcarpentry/git-novice#652]
Episodes -> "all in one page" broken.

**Comment by fmichonneau** [comment]
to fix it, please replace `aio.md` in this repo with this file: https://github.com/carpentries/styles/blob/gh-pages/bin/boilerplate/aio.md

**Comment by kekoziar** [comment]
Thank you for your submission. Since an updated version of the lesson style has been implemented, fixing the original problem this PR addressed, this PR will now be closed.
