### ISSUE TITLE
Git Cheat Sheet Link: pdf or parent page?

### ISSUE THREAD

**Issue by kekoziar** [swcarpentry/git-novice#664]
The [lesson reference page](http://swcarpentry.github.io/git-novice/reference.html) contains a link to a pdf git cheat sheet in English. The [parent page](https://github.github.com/training-kit/) for the git cheat sheet contains cheat sheets in many languages, so it might be worth it to change the lesson text slightly and refer to the parent page.

**Comment by dsconstable** [comment]
Thank you for raising this. The lesson page also includes a link to try.git.io, which is parent to the full list of cheatsheets, among other resources. However, could change the link to the cheatsheet to go directly to that [https://github.github.com/training-kit/](parent folder)

**Comment by munkm** [comment]
This was resolved via swcarpentry/git-novice#676
