### ISSUE TITLE
Images on the all-in-one page are broken

### ISSUE THREAD

**Issue by HaoZeke** [swcarpentry/git-novice#693]
![image](https://user-images.githubusercontent.com/4336207/65823363-6464fd80-e272-11e9-8229-09accaa280f0.png)

As is visible in the image above, the images of the lessons are not being rendered.

Fixed as part of [my checkout process](https://pad.carpentries.org/2019-09-26-ttt-online-EDT).

**Comment by munkm** [comment]
Thanks for finding this issue and fixing it @HaoZeke . I'm sure many instructors and learners will appreciate your fix! 🎉
