### ISSUE TITLE
Exercise submission

### ISSUE THREAD

**Issue by mjj81** [swcarpentry/git-novice#708]
Greetings Carpenters,

We have been using this lesson to introduce our students to `git`, but also looking for a follow-up that covers other important `git` elements (like branching and merging for example).

Is there any plan to develop a "git-intermediate" lesson? If so, we've created a few short exercises for demonstrating understanding of particular commands (see attached example).

To see this in action, open the `html` file (`merge.html`) in a browser, and run the shell script (`mergebase.sh`) in a "clean" directory (*i.e.* one that is not already part of a `git` repository). The script will create a simple repository whose history matches the initial diagram on the webpage. Following the model answer's instructions should change the repository in the manner depicted in the later diagrams.

The `html` file shows the initial setup of the repository/repositories, then gives a short summation of the intended task (such as a demonstrator/marker might describe it to a student). The intent is that the demonstrator will run the appropriate script on the student's machine, describe the task, then observe how the student goes about solving it. Each exercise is based around one significant action (such as a `merge` or `rebase`), though it may require several operations to complete (*e.g.* due to dealing with merge conflicts). The task should still be such that a student who is familiar with `git` will be able to complete them while the demonstrator watches (but it should not be a time-based assessment - it ought to be quickly clear to the demonstrator if the student has no idea/the wrong idea how to go about solving the task).

Diagrams are created using a modified version of [GitGraph.js](http://gitgraphjs.com/).

Let me know if this is of any use.
Regards,
mjj81

[merge_example.zip](https://github.com/swcarpentry/git-novice/files/3937280/merge_example.zip)

**Comment by kekoziar** [comment]
Thank you, @mjj81.  Please feel free to [start developing](https://cdh.carpentries.org) an advanced git lesson.
