### ISSUE TITLE
Specify text to immediately after opening text editor

### ISSUE THREAD

**Issue by gimode** [swcarpentry/git-novice#709]
The git-novice workshop is really good, and I got to learn about git fairly sufficiently without prior experience in it.
However, the lessons instruct the learner to edit texts as the lessons progress. Typically as exemplified beginning at episode 4 "Tracking changes", the instruction is:
$ nano mars.txt
which is immediately followed by;
$ cat mars.txt
and the output shows the edited text.

For some learners who are just getting acquinted with Unix and then git, there may be some confusion.
I suggest that the exact text to be added be given in an instruction prior to the request to open the text editor.
For example: 

Now suppose Dracula adds the following information to the file"The two moons may be a problem for Wolfman"
$ nano mars.txt
$ cat mars.txt

Output
Cold and dry, but everything is my favorite color
The two moons may be a problem for Wolfman

Thanks

**Comment by sgolley** [comment]
My read of how the second edit is constructed is that it assumes familiarity with the steps performed at the start of the lesson. This could be complicated by working with new environments and/or text editors.

I think the above suggestion is good for clarity, and would also suggest being explicit in what we're adding to the file using the code format, mirroring the initial text written at the start of the lesson.

`$ nano mars.txt`
Add the text below into the mars.txt file:

`The two moons may be a problem for Wolfman`

And verify the file has changed by running
`$ cat mars.txt`

`Output:
Cold and dry, but everything is my favorite color
The two moons may be a problem for Wolfman`

**Comment by kekoziar** [comment]
Thanks for the feedback.  Someone added the text
> (Again, we’ll edit with nano and then cat the file to show its contents; you may use a different editor, and don’t need to cat.)

right above the commands when the second line is added to the file.  Do you think this explanation is enough?  It might be very cluttered if each `nano` `cat` pairing needs explicit instructions.

**Comment by kekoziar** [comment]
Closing, given changes to the lesson have addressed the original issue.
