### ISSUE TITLE
Lesson 2: More information about vim (insert mode)

### ISSUE THREAD

**Issue by akcorut** [swcarpentry/git-novice#711]
In lesson 2, there is a brief section explaining vim to first time users:

![image](https://user-images.githubusercontent.com/42179487/71025304-c47e7980-20d4-11ea-8c73-4eaae290e99c.png)

I think it is a great place to introduce some useful vim commands but I thought it might be even better to include an information about insert mode (i). This way learners would be able to learn briefly about how to insert a text in vim, save the text and quit. 

Thanks.

**Comment by kekoziar** [comment]
Thank you for the suggestion.  Teaching Vim is out of scope of this lesson.  The callout was included because some learners will accidentally get stuck in Vim, and it's not intuitive how to exit.  I will leave this open for a short while for feedback.
