### ISSUE TITLE
Episode 12 - More general information on citation format

### ISSUE THREAD

**Issue by dsconstable** [swcarpentry/git-novice#712]
[Episode 12 - Citation](https://github.com/swcarpentry/git-novice/blob/gh-pages/_episodes/12-citation.md) section recommends including a citation file, without explaining that these can be provided in machine-readable format, as shown in the sample. This could be clarified by adding a short description, such as: “Citations can be formatted in machine-readable format that can be automatically rendered or imported into a citation management program. For more information, see [BibTex](http://www.bibtex.org/Format/). 

Although this is extra information, it may help avoid leaners being distracted by the format of the citation in the example.

**Comment by MathewBiddle** [comment]
To add on to @dsconstable comments. There should be a reference to [GitHub's guidance on CITATION.cff files](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-citation-files). The information and services GitHub provides when using a CITATION file make citing GitHub repositories a breeze!

**Comment by joenio** [comment]
Just some cents from my side here on this topic, I recommends also about adding content about Citation File Format (CFF) as it is being more popular and the standard way on adding citation information on repositories in general, more info: https://citation-file-format.github.io/
