### ISSUE TITLE
Episode 14 - Challenge solution should be in R

### ISSUE THREAD

**Issue by jrkirk61** [swcarpentry/git-novice#718]
While reviewing episode 14, which is the supplemental Rstudio lesson, I noticed that the answer to the [challenge question ](http://swcarpentry.github.io/git-novice/14-supplemental-rstudio/index.html) is given in bash code. Wouldn't it make more sense to give the answer in R, since the lesson is about using git in Rstudio and it can be assumed that attendees would have some experience with it if they are interested in this lesson? When I was trying to guess the answer myself, I immediately thought to try and answer it within Rstudio and was surprised to see that the answer was in bash. 

If you agree, below would be my proposed changes to the Challenge solution:

```
> dir.create("./graphs/")
# Open .gitignore file in the right-hand panel, add "graphs/" to the list and then save.
```

**Comment by munkm** [comment]
Hi @jrkirk61! Thanks for bringing this up and offering a suggestion for an alternative solution. I think it's a great idea to have a solution here that's done completely in the RStudio GUI. It's more consistent with this episode and it will reinforce some RStudio principles. Would you be interested in submitting a PR to update the solution to what you've proposed?

**Comment by jrkirk61** [comment]
Done!

**Comment by munkm** [comment]
Awesome @jrkirk61! I see you've committed this change to your fork of the repo. Would you mind turning it into a pull request so we can use your changes in the main lesson here in swcarpentry? If you're on https://github.com/swcarpentry/git-novice or on your fork at  https://github.com/jrkirk/git-novice you should see a banner saying that your branch `patch-1` differs from the `gh-pages` in this repository and directs you to make a PR. Let me know if you need any help or don't see it or something! We'd love to see your contribution here too!

**Comment by jrkirk61** [comment]
I think I submitted a PR? Haha. I've never tried to do a PR before, so let me know if it's still not right.

**Comment by munkm** [comment]
You definitely submitted one! 🎉 Congratulations! I'll review it shortly. Thank you so much for contributing!

**Comment by kekoziar** [comment]
Issue resolved.
