### ISSUE TITLE
Episode 8 - No notifications in Github after inviting collaborator

### ISSUE THREAD

**Issue by paalmbj** [swcarpentry/git-novice#724]
I recently co-instructed on the Git lesson. We asked participants to join into pairs, and pick roles of collaborator and owner. After the owner had invited the collaborator, we did not find an easily accessible place in Github to accept this invitation. There was no notification at the link given in the lesson, https://github.com/notifications (which redirects to https://github.com/notifications/beta).

When the collaborator received an email, it worked to accept from there. However, some had a problem receiving the email.

We found that the collaborator could go to `https://github.com/USER/planets/invitations` , where `USER` is the name of the owner. I'm not completely satisfied with this solution, because it requires them to input a long URL manually.

Do others have the same experience, or does it usually work better?

**Comment by slel** [comment]
Same experience at a Software Carpentry workshop
in Lancaster on 2020-02-20 -- 2020-02-21
where I was a helper. Participants were expecting
the notification to appear somewhere on GitHub
but it was only to be found as an email.

**Comment by paalmbj** [comment]
Thanks for confirming it !

**Comment by edbennett** [comment]
We found at 2020-02-25-cardiff that some users got notifications while others got emails only. I suspect that this is related to 2-factor authentication settings—if you don't have it, then you have to get the notification from your email.
