### ISSUE TITLE
Episode 5 - Exploring History: Explain state "detached HEAD" and how to handle it.

### ISSUE THREAD

**Issue by christianhueserhzdr** [swcarpentry/git-novice#730]
Dear Carpentries Contribution Reviewer Team,

in order to complete my contribution step for the instructor checkout process, I proof-read lesson "Version Control with Git" and would like to suggest improvements for section "Don't Lose Your HEAD" in "Episode 5 - Exploring History".

There are basically five suggestions I have which are targeting the introduction and explanation of the state "detached HEAD":

1) The example in the episode just shows the output given by git but does not explain the output properly. I would appreciate explanations in a different wording than that given by git itself.

2) In my understanding state "detached HEAD" is not only restricted to "look, but don't touch". It is completely fine to make changes in this state which git's output mentions as well. You just need to know a couple of extra information which need to be taken into account like "orphaned" commits and garbage collection.

3) The concept of git's garbage collection is not mentioned so far. I would suggest to explain that commits will be "orphaned" and removed by garbage collection in fixed intervals, because the changes do not belong to any branch.

4) It would be nice to have one full example in 4 steps in which we 
a) go into state "detached HEAD", 
b) make changes to the files, 
c) commit these changes, 
d) create a branch including these commits and switch to it.

5) A note on best practices or recommendations regarding state "detached HEAD" would be helpful as well like: 
a) Do not commit changes in state "detached HEAD" if you do not intent to create a new branch straight away which includes the new commit, because you need to remember the commit hash associated with the new "orphaned" commit later on and because the garbage collector will remove them at some point in time automatically; 
b) create a new branch while specifying a specific commit hash which basically prevents from entering state "detached HEAD" in the first place; 
c) go back to the branch you were on before you entered state "detached HEAD", if state "detached HEAD" has been entered unintentionally.

I hope these five suggestions demystify state "detached HEAD" a bit more, so that people feel comfortable and know what to do when facing state "detached HEAD".

Many thanks in advance for your feedback on my contribution.

Link to section "Don't Lose Your HEAD" in "Episode 5 - Exploring History":
* [Don't Lose Your HEAD](https://github.com/swcarpentry/git-novice/blob/gh-pages/_episodes/05-history.md#dont-lose-your-head)

**Comment by fer-rum** [comment]
As someone who uses _git_ on a daily basis, I wholeheartedly support this suggestion. Even as a professional user, I tend to end up in _detached HEAD_ from time to time and every time it sends me scrambling to the documentation.

It is important to teach novices not to panic in those moments but understand how they got there and what to do next.

**Comment by kekoziar** [comment]
There are a lot of good suggestions here, but they add a number of new concepts that will add significant cognitive load.  Creating new branches is definitely out of scope of this novice lesson.  However, please feel free to work on an advanced git lesson that includes these concepts. 

I think the "Don't lose your head" callout does a good job of walking learners through the commands which will result in a detached head state, and the command required to get out of it.
