### ISSUE TITLE
Applying a Creative Commons license to software

### ISSUE THREAD

**Issue by agitter** [swcarpentry/git-novice#731]
One of the Key Points in the Licensing episode is
> The Creative Commons family of licenses allow people to mix and match requirements and restrictions on attribution, creation of derivative works, further sharing, and commercialization.

I've found that using Creative Commons licenses for software is a common source of confusion.  Would it be useful to link to the Creative Commons [FAQ](https://creativecommons.org/faq/#can-i-apply-a-creative-commons-license-to-software) about this?  Perhaps the instructor notes would be best so that it doesn't clutter the Key Points.

**Comment by munkm** [comment]
Hi @agitter! Thanks for bringing this up. I like your idea about adding something to the instructor notes. I agree that I think putting this in the main lesson itself is probably out of scope, but as an addition for instructors is certainly worthwhile. Are you interested in submitting a PR with this change to the lesson?

**Comment by agitter** [comment]
Yes, I'll make a quick PR.
