### ISSUE TITLE
Episode 6 - Ignoring Things: Reference to other option for ignoring files

### ISSUE THREAD

**Issue by DanielKotik** [swcarpentry/git-novice#736]
I would recommend (at least) to mention that there exists a complement to `.gitignore` - for very good reasons:

Most likely, if you create a repository from scratch it will contain files that are specific to your *personal*, local repository and which you don't want to have tracked and/or that you don't want anybody to know of. Such files may be OS related files (like mac OS `.DS_Store` files or Linux KDE/Dolphin specific `.directory` files, for example, or may be files and folders for experimentation, testing etc. The ignore pattern for such files should not be part of a tracked `.gitignore` file, which is shared with others.  For locally-generated files that one don't expect other users to generate, one should define rules in a file called `.git/info/exclude`. This file is ignored per default by git and hence will not be checked in.

**Comment by kekoziar** [comment]
@DanielKotik, thank you for your comment.  I think your solution adds significant cognitive load and is out of scope for this novice lesson.  Please feel free to [start developing](https://cdh.carpentries.org) an advanced git lesson, where this improvement would be appropriate.
