### ISSUE TITLE
Link missing to download files required for git lesson

### ISSUE THREAD

**Issue by rraffiu** [swcarpentry/git-novice#746]
I am teaching git lessons tomorrow - and while checking I realized the link to download files required for git lessons (I remember from previous lesson it was directory called planes) is missing on this page:
https://swcarpentry.github.io/git-novice/setup.html

Could someone please quickly help with this?

**Comment by kekoziar** [comment]
As a clarification, the only setup requirement for the lesson is installation of git.  No additional files are required for the git lesson.  All items are created during the lesson.
