### ISSUE TITLE
Exercise timings are all zero

### ISSUE THREAD

**Issue by colinsauze** [swcarpentry/git-novice#747]
None of the exercises in this lesson having timings. This makes the suggested time for the lesson (1 hour 57 minutes) completely unrealistic. 

I tried timing how long we spent on some exercises at a recent session, although this was being run online so might differ a little from something run in person. My timings are:

Tracking changes - 15 minutes
Exploring history -  25 minutes
Ignoring changes - 10 minutes
Remotes in github - 15 minutes

**Comment by ErinBecker** [comment]
Thank you for this @colinsauze! Updating the exercise timings on some of the older lessons so that they're realistic will be an incredible improvement to the lessons and make it much easier for new instructors to teach.

**Comment by kekoziar** [comment]
This duplicates an older issue https://github.com/swcarpentry/git-novice/issues/521
