### ISSUE TITLE
 Suggestion for clarification in .gitignore lesson

### ISSUE THREAD

**Issue by tmuylder** [swcarpentry/git-novice#749]
In the [.gitignore lesson (06)](http://swcarpentry.github.io/git-novice/06-ignore/index.html) the following line is stated:

*As a bonus, using `.gitignore` helps us avoid accidentally adding to the repository files that we don't want to track:*

Is not really clear in that context, proposed edit:

*Furthermore, by using `.gitignore` we can avoid that files in the repository are accidentally added to the staging area that we don't want to track:*

**Comment by kekoziar** [comment]
Hi, @tmuylder.  Thanks for bringing this up.  This section as been wordsmithed a couple of times because it can be unclear, especially when read aloud.  What do you think of just rewording the sentence to provide clarity?
 
> As a bonus, using `.gitignore` helps us avoid accidentally adding files that we don't want to track to the repository:

**Comment by tmuylder** [comment]
Hi @kekoziar ,

Thanks for your swift reply. Your suggestion is definitely great, here is another one in case you like it. No need of checking back with me, either are fine for me. 

*As a bonus, using `.gitignore` helps us avoid accidentally adding files to the repository that we don't want to track:*

(BTW, it's part of my checkout process, so don't want to annoy you with these minor things)
