### ISSUE TITLE
Creating a repository section - might it be worth doing via github/bitbucket web interface instead?

### ISSUE THREAD

**Issue by MauriceHendrix** [swcarpentry/git-novice#756]
The *[Creating a Repository](http://swcarpentry.github.io/git-novice/03-create/index.html)* section explains how to crate a new repository using the command line, locally. The topic of remotes comes up much later on.

When I taught a git workshop, I have found this problematic, as many of the learners were asking about the remote and questioning what the point of "all this" was, until we finally got to show the remote on github. In terms of usefulness, which according to the instructor training the lessons should focus on, I think knowing how to create a new repository via the command line and connect it up to a new remote is something done very infrequently usually by only 1 person per project. 

Of course we need a new repository to be able to do anything. What I have done in the past when I taught git as part of an undergraduate module, is have students create a repository on github.com (or whichever provider is being used) and clone the empty repository. In my view this has the following benefits:
- It makes for a quicker start and keeps learners engaged by showing quick progress, in a visual way. Learners can see we're one stap closer to sharing cod.
- One less thing / command to remember (they'll need to know about clone anyway)

I'm not 100% sure how to best integrate this in the lesson, but I would suggest it's worth having at least as an alternative, either in the main material and/or the instructor notes.

**Comment by kekoziar** [comment]
That's an interesting perspective.  I've fielded questions about remotes a few times prior to their being introduced.  I will respond with a few things.  First is reiterating that git is not github, and many cloud services will have different methods of creating repositories.  Some of our research labs will have their shared git repository on a shared server on their network, and not use cloud services at all.  And lastly, the usefulness and importance of having a 3-2-1 backup strategy, and how a local copy of the repository fits in.  One or more of these usually answers the questions. 

Taking all of these options into account, in terms of pedagogy it's useful to teach the skill and term that is the most foundational, and allow other skills to scaffold upward from that skill.

**Comment by kekoziar** [comment]
That said, from your issue, it sounds as if you've adapted the curriculum as part of a larger undergraduate program.  I think that's impressive, and even encouraged, to adapt the lessons to help undergraduates gain skills they can use in their subsequent academic and professional career.  Perhaps sharing instances when they will need to use only the command line will help them understand that git is used by different types of groups and organizations in different ways, and so knowing the command line basics will always be a skill they can fall back onto.

**Comment by MauriceHendrix** [comment]
In my experience participants don't really care about the difference between git and github, but the 3-2-1 backup is a very good point. Overall I do prefer using the command line over say a GUI, as I found the command line much better for building up their mental model.

**Comment by kekoziar** [comment]
The lesson introduces the basics of Git on CLI.  This proposal will remove that, and cause all learners to ask questions about remotes (a more advanced topic) prior to learning the basics of Git.
