### ISSUE TITLE
Lesson contribution - nano text editor commands

### ISSUE THREAD

**Issue by jpatinox** [swcarpentry/git-novice#766]
Nano text editor
---

In episode 4 Tracking changes of this lesson, I think it would be helpful for novices who have never used a text editor before for us to include the commands they will be using in the nano text editor in this lesson, namely the ^O (Control +O) to write out and ^X (Control + X) to exit.

**Comment by britnaybeaudry** [comment]
@jpatinox, I agree. While the commands are available at the bottom of nano text editor, it is certainly confusing for someone with possibly no experience to know what to do to save their work and exit out of the text editor. I would also suggest a brief description of what "Write Out" means/does.

**Comment by kekoziar** [comment]
Hello, and thank you for your comment.  At the beginning of episode 4, there is a reference to a section on working with text editors.  For those who are completing this in the workshop sequence (Shell then Git) won't necessarily need this, but those who are reading through on their own, or teaching it as a stand-alone lesson will have a link to the content covered in the shell lesson

> For a refresher on text editors, check out [“Which Editor?”](https://swcarpentry.github.io/shell-novice/03-create/) in The Unix Shell lesson.
