### ISSUE TITLE
Ep. 7 Remotes Screenshots out of date

### ISSUE THREAD

**Issue by torwhite** [swcarpentry/git-novice#775]
1) Github has changed the look of the "new repository" page, this old screenshot could be confusing for learners.

git lesson:
![image](https://user-images.githubusercontent.com/58574172/105548833-01904480-5cb5-11eb-9b24-221ba8e21a96.png)
redesigned github page:
![image](https://user-images.githubusercontent.com/58574172/105548766-e9b8c080-5cb4-11eb-934a-2701fd64b70f.png)

2) The screenshot for the page after creating a repository which gives the tips for creating a new repo on command line/push existing repo to command line is also out of date. This relates to the #761 issue on the switch to main from master vocabulary.

git lesson:
![image](https://user-images.githubusercontent.com/58574172/105549151-6ba8e980-5cb5-11eb-8a45-a5adf36ee7aa.png)
new page:
![image](https://user-images.githubusercontent.com/58574172/105549283-a14dd280-5cb5-11eb-80e9-98b45190b8d6.png)

**Comment by torwhite** [comment]
in the workshop we taught today we followed the new directions on Github to rename your master branch to main when you connect your local repo to the Github repo. This went smoothly and may also be an easy solution to the question brought up in #761. Doing the renaming as part of the Remotes lesson conforms to Github's instructions so may be the least confusing place to lead learners through the change. Also gives an opportunity to mention why Github has made the decision to change the vocabulary.

**Comment by kekoziar** [comment]
Hi, @torwhite.  Thanks for catching this.  Are you able to make a PR updating the screenshots?

**Comment by kekoziar** [comment]
Also, @torwhite, thanks for providing feedback.  It's very important to know what works and doesn't during workshops.

**Comment by kekoziar** [comment]
Fixed, https://github.com/swcarpentry/git-novice/pull/818
