### ISSUE TITLE
"Lesson" is used in place of "episode"

### ISSUE THREAD

**Issue by edbennett** [swcarpentry/git-novice#777]
I believe the standard Carpentries nomenclature is that a _lesson_ is a collection of _episodes_—so this repository contains the git-novice _lesson_, which comprises _episodes_ such as "Setting up Git", "Creating a Repository", "Tracking Changes", etc.

This terminology is mixed up in the lesson material, however. Episodes 7 and 8 refer to episodes, but elsewhere in the lesson the episodes are referred to as "lessons" - specifically:

* In episode 2, "in a later lesson", "For these lessons"
* In episode 5, 'As we saw in the previous lesson"
* In episode 7, "If you remember back to the earlier lesson", "In this lesson" (and also uses "section"—"in the final section", "In this section"—to refer to the episode)
* In episode 10: "You'll learn how to do this in lesson 12: Citation"

I think in the minimal case that the nomenclature should be consistent across all episodes of the lesson, rather than the mixing that is currently done. Making it consistent with the Carpentries usual nomenclature seems like the best option?

**Comment by kekoziar** [comment]
Thanks, @edbennett.  Good catch.  Feel free to add a PR for these changes.
