### ISSUE TITLE
Suggestion for improving Episode 1 and the version lesson, exemplify version control with code not docs

### ISSUE THREAD

**Issue by jurra** [swcarpentry/git-novice#780]
## Problem: Git is designed to version control code, not documents or other types of files...
Even though version control is important in general, we should be more specific to code. I have personally tried git for all kinds of things from docs, to text, to CAD files, and the main learning is that is designed and optimized for code version control. 
It is particularly suited for spotting small code syntax details that can break code, this is why you want to have very strict version control in coding, which is not the case for writing documents since documents do not perform functions or are dependable like code is. This might lead to a misunderstanding and clarity of how git is used in an individual and also in a collective context.

## Solution idea: Make a representative use case version control with code
Normally users/learners want to learn git when they already code and struggle with not doing version control. They have a need and awareness about why it is important to a certain extent. At this point, we could teach how to do version control on Unix Shell bash scripts, demonstrate and concatenate the content of Unix Shell with git.

**Comment by kekoziar** [comment]
Thank you for your feedback.  There is an open issue regarding this: https://github.com/swcarpentry/git-novice/issues/277
