### ISSUE TITLE
Improving the setup page

### ISSUE THREAD

**Issue by Madchild95** [swcarpentry/git-novice#781]
Hello community

I have made a proof reading of the [Git novice lesson](http://swcarpentry.github.io/git-novice/) and thought I would make a comment on the [setup page](http://swcarpentry.github.io/git-novice/setup.html). I think the issue has already been discussed in here: #735, but I wanted to make a suggestion for how to make it a bit better, while still keeping the link for the [general setup page](https://carpentries.github.io/workshop-template/#git  ) (as I gathered that it was important to keep the setup page for the lesson and the instruction page for the setup separate).

As of now the current setup page looks like this:
<img width="1161" alt="Screenshot 2021-02-16 at 11 34 31" src="https://user-images.githubusercontent.com/54779393/108051575-596b6280-704b-11eb-9ef9-3bb7e87535f3.png">

**Issue:** Personally, the first thing I would gather from this page is that setup for this lesson is just to have the Desktop as working directory in the terminal. Whereas the setup that really matters, namely to install Git and GitHub is sort of in the background and just mentioned in one sentence with a hyperlink.

**Solution:** My suggestion is to make a heading that says "_Installing Git and creating GitHub account_" much like in other lessons such as the [Plotting and Programming with Python setup page](http://swcarpentry.github.io/python-novice-gapminder/setup.html):
<img width="1163" alt="Screenshot 2021-02-16 at 11 45 23" src="https://user-images.githubusercontent.com/54779393/108052608-b0be0280-704c-11eb-8434-71550e9b8806.png">

An explanation in this section could include an introduction text like the one on the general setup page: 
"Git is a version control system that lets you track who made changes to what when and has options for easily updating a shared or public version of your code on github.com. You will need a supported web browser.

You will need an account at github.com for parts of the Git lesson. Basic GitHub accounts are free. We encourage you to create a GitHub account if you don't have one already. Please consider what personal information you'd like to reveal. For example, you may want to review these [instructions for keeping your email address private](https://docs.github.com/en/github/setting-up-and-managing-your-github-user-account/setting-your-commit-email-address) provided at GitHub."

And then additional information about how to navigate in the general setup page as a warning, something like:
"To setup Git and GitHub, you will need to go to our general setup page [here](https://carpentries.github.io/workshop-template/#git), where there will be an instruction video on how to do so. You can choose which operating system (OS) you are working on (Mac, Windows, Linux) to install it correctly. The hyperlink will take you directly to the Git setup, but there will also be other setup instructions on this page, that you can ignore if you are just going to setup for this lesson. Whenever finished with the video setup you should be able pursue with this lesson in you terminal."

Then another subheading could have the title "_Unix Shell_" with the instruction text:
"Navigate to Unix Shell (see this [setup page](http://swcarpentry.github.io/shell-novice/setup.html) if you haven't installed Unix Shell already) where the code for this lesson will be written."

And then the rest of the page could follow as it is already with the description:
"We’ll do our work in the Desktop folder so make sure you change your working directory to it with:"
followed by the output from Bash.

I hope this makes sense and is clear, otherwise feel free to ask for any elaboration!

/Matilde Jacobsen

**Comment by kekoziar** [comment]
Hi, @Madchild95. A few headers would improve the readability of the page.  However, I am in the "keep the install instructions in one place so we only need to update that one place" camp.  IMO, it's easier on all maintainers, workshop instructors/admins, and learners.  I especially think it's important to having the install instructions in one place for learners to get ready for their workshop. 

Feel free to submit a PR with headers to improve readability.

**Comment by marco-foscato** [comment]
Here is a suggested change that adds headers: #842

**Comment by wdconinc** [comment]
Increased visibility of the Git installation instruction with headers:
![image](https://user-images.githubusercontent.com/4656391/161393260-807e7b10-a389-4b93-ba5e-7001a40def0d.png)
The links to different operating systems are all exactly the same and only serve to give visual weight and ensure the learners understand there are specific instructions for each operating system. Further discussion in PR #872.
