### ISSUE TITLE
Broken link in git-novice/CONTRIBUTING.md

### ISSUE THREAD

**Issue by dsarahstamps** [swcarpentry/git-novice#783]
Towards the end of the CONTRIBUTING.md file under the section Using GitHub, the link for "How to Contribute to an Open Source Project on GitHub" does not go to a real article. This is the link that is broken: https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github

**Comment by bkmgit** [comment]
Link seems to have moved to https://app.egghead.io/playlists/how-to-contribute-to-an-open-source-project-on-github

**Comment by cgentemann** [comment]
make a pull request to fix link.
https://github.com/swcarpentry/git-novice/pull/811

**Comment by kekoziar** [comment]
Updates to the style are resolved through a different mechanism, specifically pulling from https://github.com/carpentries/styles/.  I opened an issue there so it can be fixed in all Carpentries lessons.

**Comment by kekoziar** [comment]
Closing, as updates to the style are resolved through a different mechanism, specifically pulling from https://github.com/carpentries/styles/. An issue and PR were opened, so that it can be fixed in all Carpentries lessons.  It will be fixed on this lesson the next time the style is updated.
