### ISSUE TITLE
"All in One Page" view of the Git-novice lessons is filled with broken image links

### ISSUE THREAD

**Issue by karlbenedict** [swcarpentry/git-novice#801]
It appears that the consolidated document code is generating image links in the single-page document that are missing the /git-novice/ element of the image paths. Compare the following output in the Safari Web Inspector for loading the first image of the first lesson (phd101212s.png) in the single lesson view:

![Image file request and result for single episode display](https://www.dropbox.com/s/5hpnwznpuzeuuy1/2021-04-19_22-26-28.735.png?raw=1)

with the output of attempt to load the same image through the "All in One Page" view:

![Image file request and result for the All in One Page view](https://www.dropbox.com/s/2sqx9g55vmakz2a/2021-04-19_22-32-26.433.png?raw=1)

**Comment by tobyhodges** [comment]
It looks like the `permalink` field was accidentally removed from the YAML header of `aio.md` in c4843ad, resulting in internal paths breaking for the all-in-one page. (Compare to the first few lines of [the equivalent file in `shell-novice`](https://github.com/swcarpentry/shell-novice/blob/gh-pages/aio.md).) Would you like to submit a pull request to fix this, @karlbenedict?

**Comment by karlbenedict** [comment]
PR #803 submitted for this issue.

**Comment by kekoziar** [comment]
@tobyhodges, @karlbenedict updates to the style are resolved through a different mechanism, specifically pulling from https://github.com/carpentries/styles/.  This usually happens through an update from that group.   @fmichonneau, do you think we can get a style update?

**Comment by fmichonneau** [comment]
Thanks for pinging me here @kekoziar. I opened #814 which should address the issues with the broken images in the "all in one" page among other improvements.

**Comment by kekoziar** [comment]
Thanks, @fmichonneau.  I merged your PR.  I look forward to viewing the other style improvements!
