### ISSUE TITLE
Transition to `main` as default branch name?

### ISSUE THREAD

**Issue by jhlegarreta** [swcarpentry/git-novice#805]
There as been a heated debated in the past few months about the convenience of transitioning the default branch name from `master` to `main`.

Although `git` itself has not made the transition yet, strides are being made towards that purpose:
https://lore.kernel.org/git/pull.762.git.1605221038.gitgitgadget@gmail.com/

`GitHub`, `GitLab` and other major code hosting services already use `main` as the default branch name when starting a new repository.

So the evidence is that the transition has been happening. Maybe the lesson should be updated to match the new naming, or at least the transition could be mentioned as a callout so that users are warned about it in case their local `git` version has still not transitioned.

Loosely related to #716.

Thanks for this wonderful lesson

**Comment by snownontrace** [comment]
I noticed this as well and was going to open an issue on it!

**Comment by c089** [comment]
I was also thinking about this exact same proposal after I used the git course for my teaching demo last week. While it adds a little overhead, the course already has a [section](https://swcarpentry.github.io/git-novice/02-setup/index.html) where students are using `git config` to set their name and e-mail where it could easily be added. I also think it is in line with the CoCs intent of [using inclusive language](https://github.com/swcarpentry-ja/carpentries-coc/blob/main/topic_folders/policies/code-of-conduct.md) and even if git eventually migrates, many students might be running older git versions that come with e.g. the Mac OS command line tools or their Linux distributions for a while.

**Comment by laufers** [comment]
Could this change for setting the defaultBranch name be merged? We have started teaching this in our local workshops for Git. For those running Git 2.27 and earlier, the command for renaming a branch could also be included in the instructor notes 

```git branch -m master main```

**Comment by jhlegarreta** [comment]
@laufers thanks for the suggestion: done in 5f77afb (push-forced). The note also allowed me to realize that the instructor notes had also some instances that had to be changed. Thanks.
