### ISSUE TITLE
Mention Enter in addition to Return in the Git lesson

### ISSUE THREAD

**Issue by abhidg** [swcarpentry/git-novice#809]
There are a few mentions of pressing Return in the lesson in https://swcarpentry.github.io/git-novice/02-setup/index.html:

* As with other keys, when you hit Return on your keyboard...
* If you haven’t used Vim before and wish to exit a session without saving your changes, press Esc then type :q! and hit Return

In many keyboard layouts, Return is labelled as Enter or even a symbol. I'd suggest labelling the key as Return / Enter / ↵

**Comment by kekoziar** [comment]
@abhidg, sounds good. Feel free to submit a PR.

**Comment by cassgvp** [comment]
Looks like this issues is ready to be closed? My informal review of the commit looks good.
