### ISSUE TITLE
Wording in 03-create

### ISSUE THREAD

**Issue by pawsey-kbuckley** [swcarpentry/git-novice#810]
Would normally try and create a pull from a personal fork but think
this might open up a wider discussion, so I'll just raise the issues,
as I see them

I'm helping out with a RezBaz event next week and came to revisit
the git-novice lesson (It's been a while!)

I found this bit of the text

```
Then we tell Git to make planets a repository - a place where Git can store versions of our files:
$ git init
```

to be a little incorrect

What is really happening here is that 

Git is being "told" to create a repository WITHIN the planets directory.

The planets directory itself is not a repository, the .git directory within it is.

I feel it would be better, and it would certainly be more correct, to say 

```
Then we tell Git to initialise a repository - a place where Git can store versions of our files - within the planets directory
$ git init
```

My other "gripe: is with the flip-flop between "directory" and "folder", such as

```
'First, let’s create a directory in Desktop folder'
```

For me

```
'First, let’s create a sub-directory within Desktop  '
```

Another case in point

```
To check if everything was successful:
$ ls -a
You should see a .git folder.
```

For me, if one is using ls, you are not listing "folders", so use the word directory

```
To check if everything was successful:
$ ls -a
You should see a .git directory
```

Probably just me though,
Kevin

**Comment by pawsey-kbuckley** [comment]
> The planets directory itself is not a repository, the .git directory within it is.

Just to validate that claim, the diagram in the section entitled "The Three States" ,
in Part 1.3 of the Pro Git book (https://git-scm.com) lays out the correct nomenclature.

For the git-novice lesson then, the "planets" directory is the "Working directory"
and ".git" is the repository.

**Comment by kekoziar** [comment]
Thanks @pawsey-kbuckley  for referring to the book.  The wording we use is actually very similar to the book at [Chapter 2.1](https://git-scm.com/book/en/v2/Git-Basics-Getting-a-Git-Repository).
```
You typically obtain a Git repository in one of two ways:

You can take a local directory that is currently not under version control, and turn it into a Git repository, or [...]
```
turn a local directory into a repository; make a folder a repository.  It's easier for learners to understand this new concept by first couching it in language that is familiar, then explaining the technicalities.

**Comment by pawsey-kbuckley** [comment]
On 2021/06/24 22:45, K.E. Koziar wrote:
> Thanks @pawsey-kbuckley  for referring to the book.  The wording we use is actually very similar to the book at [Chapter 2.1](https://git-scm.com/book/en/v2/Git-Basics-Getting-a-Git-Repository).
> ```
> You typically obtain a Git repository in one of two ways:
> 
> You can take a local directory that is currently not under version control, and turn it into a Git repository, or [...]
> ```
> turn a local directory into a repository; make a folder a repository. 

But even that wording is incorrect, in that it suggests that the
repository is the working directory.

The two are different: that much is clear.

A repository can exist without a working directory.

One could take the repository, the .git directory,
move it to a different working directory and it
would still function as a repository, whilst the
new directory within which the .git repository is
now found, has become a working directory.

> It's easier for learners to understand this new concept 

Equally, it's better to have learners who have not encountered
Git before to begin using the correct terminology from the start
though, no?

Anyroad, your call.

-- 
Supercomputing Systems Administrator
Pawsey Supercomputing Centre
