### ISSUE TITLE
Episode 4 (Tracking Changes): Small edit/correction.

### ISSUE THREAD

**Issue by CristinaUrizar** [swcarpentry/git-novice#815]
Episode:  http://swcarpentry.github.io/git-novice/04-changes/index.html

The italicized and bolded line of code in the below text of the Tracking Changes Episode is not needed.  Simply running the git commit will result in this message. 

-----------------------------------------------------------------------------------------------
After reviewing our change, it’s time to commit it:

$ git commit -m "Add concerns about effects of Mars' moons on Wolfman"
**_$ git status_**

On branch main
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

  modified:   mars.txt
no changes added to commit (use "git add" and/or "git commit -a")

-----------------------------------------------------------------------------------------------

**Comment by kekoziar** [comment]
Thank you @CristinaUrizar.  Previous versions of Git only included abbreviated output, and so one needed to execute `git status` in order to receive the full output, that also includes hints on what to do next. Please feel free to submit a PR removing `git status` from that section.

**Comment by kekoziar** [comment]
Perfect @CristinaUrizar.  Thank you!
