### ISSUE TITLE
Add end of line configuration in 01-setup.md

### ISSUE THREAD

**Issue by iglpdc** [swcarpentry/git-novice#82]
In the teaching notes in `instructors.md`, we mention the problem of end of line characters for learners using Windows. I think this could be solved during the configuration in `01-setup.md` by setting:

    git config --global core.autocrlf input 

for Mac OS and Linux, and,

    git config --global core.autocrlf true

for Windows, [as recommended by Github](https://help.github.com/articles/dealing-with-line-endings/#platform-all).

Shouldn't that fix all end-of-line issues for everyone? It's just one more line and a little bit harder to explain than the rest, but may be worthy.

**Comment by wking** [comment]
On Sun, Mar 22, 2015 at 09:01:51PM -0700, Ivan Gonzalez wrote:

> In the teaching notes in `instructors.md`, we mention the problem of
> end of line characters for learners using Windows. I think this
> could be solved during the configuration in `01-setup.md` by
> setting:
> …
>     git config --global core.autocrlf true
> 
> for Windows. 

You might also want:

  $ git config --global core.safecrlf warn

There's a more extensive discussion of this setting in git-config(1).

Personally, I prefer leaving these settings alone and using a
reasonable text editor.  Emacs and nano both definately handle
auto-detecting the end-of-line character(s), so users can edit the
files transparently regardless of the endlines it uses.  I expect
other serious editors do the same (I vaguely remember Notepad++ being
able to handle LF line endings, as well as Window's default CRLF).
Are we suggesting editors that *can't* handle that?  The only other
reason I can think of for using these settings is if we don't want to
pollute a repository with non-native line endings, and I don't think
we care that much about such minor polishing for the novice lesson.

**Comment by daisieh** [comment]
I'd like to leave this in the instructor notes: weird config issues that only affect a subset of users and require unnecessary explanations should be saved to explain to just the few people who need it, I think.

**Comment by daisieh** [comment]
My concern is that, as it is, the git config global things we already tell them at the very beginning set up this atmosphere of "magic incantations" about Git, and I'd like to minimize that until they feel a little more grounded in it. I think dealing with adding config statements as needed during training works better for that. But I do think we should have this page easily accessible by the instructors. I'll make a PR for that.

**Comment by iglpdc** [comment]
I'm closing this by #92.
