### ISSUE TITLE
Error message when using nano in git-for-windows version 2.32.0.windows.2

### ISSUE THREAD

**Issue by murraycadzow** [swcarpentry/git-novice#831]
This is more of an FYI for people coming across the error as part of a workshop

The following error occurs when using nano (e.g. at the start of http://swcarpentry.github.io/git-novice/04-changes/index.html) when using git version 2.32.0.windows.2: "Error in /etc/nanorc on line 237: Error expanding /usr/share/nano/*.nanorc: No such file or directory"

This is an error in git-for-windows and has been reported https://github.com/git-for-windows/git/issues/3315 and will hopefully be fixed in the next release.

It does not seem to cause any issues beyond the message appearing each time nano is used.

**Comment by kekoziar** [comment]
Thanks, @murraycadzow, for making a note of that, and following up with git-for-windows.  I saw the same issue, not in git, but a unix class I recently taught.  I used it as an opportunity to explain how you can double-check functionality (which is really just using the `ls` command followed by the `cat` command).

**Comment by kekoziar** [comment]
Git Bash error has since been fixed
