### ISSUE TITLE
Ep.11 "address patent rights" meaning clarification

### ISSUE THREAD

**Issue by masamiy** [swcarpentry/git-novice#844]
<details>
<summary><strong> Meaning of addressing patent rights is not clear </strong></summary>

Hello,
The statement I want to raise my feedback is part of Licensing (https://swcarpentry.github.io/git-novice/11-licensing/index.html)

We are working on localising the lesson and a statement and I found 'Whether you want to address patent rights.' was a little ambiguous statement and it was a little challenge to translate. Does it mean you want to enforce patent rights or want to apply patent right? Is it possible to clarify a little?

Thank you and Kind Regards,
Masami

**Comment by kekoziar** [comment]
@masamiy feel free to add more comments if you want clarification, but I'm going to close this as the discussion seems over.
