### ISSUE TITLE
Possible clarifications for ep. 7 and ep. 8

### ISSUE THREAD

**Issue by dylan-alcazar** [swcarpentry/git-novice#848]
In episode 7: 'Remotes in GitHub' after giving GitHub our public key the lesson tells the learner to move on to the GitHub website and does not mention that the output from the previous bash that asks if we would like to "continue connecting (yes/no/[fingerprint])?" appears again. In order for GitHub to actually connect you have to type "yes" and that is not mentioned in the lesson. 

In episode 8: 'Collaborating" the lesson mentions that you can work alone by opening a new terminal window, but it is unclear what to do afterwards. The lesson tells the learner to invite a collaborator, but if the learner is alone do they invite themselves to the project? 

Discussed these issues with @zpainter

**Comment by kekoziar** [comment]
RE Episode 8 comment: the callout states 

> If you’re working through this lesson on your own, you can carry on by opening a second terminal window. This window will represent your partner, working on another computer. You won’t need to give anyone access on GitHub, because both ‘partners’ are you.

which provides clarification to the concern.

**Comment by kekoziar** [comment]
Re Episode 7 comment:  The output for that section includes

```
Are you sure you want to continue connecting (yes/no/[fingerprint])? y
Please type 'yes', 'no' or the fingerprint: yes
```

which addresses concern.
