### ISSUE TITLE
Update look of figures

### ISSUE THREAD

**Issue by r-gaia-cs** [swcarpentry/git-novice#85]
The following figures need to be update to have the same look of the others figures.

- [x] `fig/git-when-revisions-updated.svg`
- [x] `fig/git-freshly-made-github-repo.svg`
- [x] `fig/github-repo-after-first-push.svg`

**Comment by daisieh** [comment]
Updated to match which figures? I think there are several styles throughout, and the ones I've pushed into #74 don't match any of them, but aren't merged yet anyway.

**Comment by iglpdc** [comment]
A bunch of scientists that cannot draw, eh? I agree the figures could have some makeup.

**Comment by daisieh** [comment]
So...which style do we want the figures to be in?

**Comment by gvwilson** [comment]
Whomsoever draweth the figures, it shall be to them to chooseth the 
styles thereof.

**Comment by daisieh** [comment]
I suppose I can do it, since I have the Illustrator files for what I've already done.
