### ISSUE TITLE
🐛 Images on ..github.io/git-novice/01-basics.. do not display 😥

### ISSUE THREAD

**Issue by matuskalas** [swcarpentry/git-novice#850]
![image](https://user-images.githubusercontent.com/992660/142192518-850c2d03-0543-4963-8a0d-84faddb2f1e8.png)

Images on https://swcarpentry.github.io/git-novice/01-basics/index.html do not load, their direct links return 404. Anything wrong with the github.io deploy?

In contrary, the images on _e.g._ https://swcarpentry.github.io/git-novice/03-create/index.html work fine. Also not problem with the images directly in GitHub (https://github.com/swcarpentry/git-novice/blob/gh-pages/_episodes/01-basics.md)

Tried on multiple devices, various networks.

This is bad, as I'll be teaching this lesson in 20 hours (Thu 10am UTC) 😥
 
<details>
<summary><strong>Instructions</strong></summary>

Thanks for contributing! :heart:

If this contribution is for instructor training, please email the link to this contribution to
checkout@carpentries.org so we can record your progress. You've completed your contribution
step for instructor checkout by submitting this contribution!

If this issue is about a specific episode within a lesson, please provide its link or filename.

Keep in mind that **lesson maintainers are volunteers** and it may take them some time to
respond to your contribution. Although not all contributions can be incorporated into the lesson
materials, we appreciate your time and effort to improve the curriculum. If you have any questions
about the lesson maintenance process or would like to volunteer your time as a contribution
reviewer, please contact The Carpentries Team at team@carpentries.org.

You may delete these instructions from your comment.

\- The Carpentries
</details>

**Comment by slel** [comment]
Hopefully #851 fixes that.

**Comment by matuskalas** [comment]
Works now, awesome! 🙌🏽

**Comment by kekoziar** [comment]
@ErinBecker, #845 caused this, but rendered properly locally.  Do you think this should be kicked over to styles and/or add [a section to the lesson example ](https://carpentries.github.io/lesson-example/07-checking/index.html) that even if links work properly locally, they need to be double-checked after a PR is pushed live? ![git-make-serve-issue](https://user-images.githubusercontent.com/28507641/142245430-95d6a640-e7c3-4193-a4da-c857cfa53ec2.PNG)

**Comment by ErinBecker** [comment]
Thanks for the info @kekoziar. I'm gonna bump this question to @zkamvar :-)

**Comment by zkamvar** [comment]
@kekoziar, I think adding a callout in the lesson example is probably the correct way to go. I've added some text in https://github.com/carpentries/lesson-example/pull/366. Please let me know if you think it should be modified.
