### ISSUE TITLE
Replace "hit" with "press" as an instruction to use a key

### ISSUE THREAD

**Issue by cassgvp** [swcarpentry/git-novice#858]
## Problem
In the [setup](https://swcarpentry.github.io/git-novice/02-setup/) and [first episode of the git-novice lesson](https://swcarpentry.github.io/git-novice/aio/index.html), participant are instructed to "hit" a key. This language is unnecessarily emotive and not precise enough. There may also be interpretation issues for non-native English speakers. 

## Proposed Solution
A more inclusive and precise instruction would be to "press the `x` key on your keyboard"

Note "hit" is also used in a few places in the shell-novice lesson.

**Comment by fesquive** [comment]
As a non-native English speaker, I disagree. I think using synonyms enriches our vocabulary :)

**Comment by cassgvp** [comment]
Fair enough @fesquive! Perhaps this might be a difference of [high and low context communication styles](https://www.unitedlanguagegroup.com/blog/communicating-high-context-vs-low-context-cultures). I look forward to seeing how the team disentangle the priorities of enriched vs (my interpretation of) aggressive language. Absolutely not trying to be inflammatory here! Just providing the feedback :)

**Comment by kekoziar** [comment]
Here's [another conversation](https://english.stackexchange.com/questions/152777/do-you-hit-or-press-a-button) on the use of words indicating someone is depressing a key on their keyboard.

I personally am for word variation since a number of different words are used interchangeably in actual use.  If a learner is new to any of the content in The Carpentries lessons, I think it's better for them to be exposed to the different terms in a safe learning environment.  A couple of other examples of this are directory and folder; and, command line, shell, console, and terminal. But, I can see the point on aggressive language. 

That said, since this is something that has the potential to impact all Carpentries lessons, I encourage discussion which we can then give to the curriculum committee. 

@cassgvp do you know any references/studies on how aggressive language impacts pedagogy?

**Comment by gazalk** [comment]
I would like to mention a traditional phrase in computer science: "Press any key to continue...". 

"Press" is more delicate, formal, and traditional within this context, while "hit" sounds more like slang. The difference is slightly subtle with "hit", although it is not incorrect, I would still prefer to use the word "press" for the written lesson. It may be up to the instructor to choose the level of formality, delivery of commands, and spoken language in the class.

**Comment by mahermanns** [comment]
Hi all, I tend to agree with @gazalk. I, personally as a non-native Speaker in English, also understand *press* as a more delicate action than *hit*.

Additionally, a while back attending a scientific writing course the instructor actually discouraged the use of different words for the same concept in a single scientific context, as it may confuse the reader. IIRC, he argued that, while done in prose to add variation and suspense, in a scientific context it may add imprecision and confusion

While I appreciate that *hit* and *press* are used interchangeably by many people, some may still recognize their subtle differences and be confused by their equivalent use in the same context. 

For example, there is something like a "long press", yet no equivalent for "long hit", as a hit (in my understanding as a non-native  speaker in English) is (always?) a quick action (and presumably with more force, as suggested in the conversation linked by @kekoziar ? :shrug: native-speakers for the rescue?). 

Assume the following example:

> "Press the 'A' key followed by 'B'
> ...
> "Now hit the 'C' key

A reader/course participant may wonder: Does the physical action associated with the 'C' key have to be different from the one associated with the 'A' and 'B' key? Why else are two different words used in this context?

As *press* is (in my understanding) the more broadly applicable term when interacting with the keyboard (I can *hit* a key, but I can also *press*, *short press*, *long press*, *press and hold*, ...), I favor it's use in a technical teaching environment.

**Comment by astroDimitrios** [comment]
Building on @mahermanns note about consistency - using consistent terminology helps reduce cognitive load.

I think the word hit only appears 3 times in the lesson and as a native English speaker I would expect this to be `press`.
I have opened #1009 to remove hit which I feel is the concensus.

**Comment by martinosorb** [comment]
I have no particular opinion on this. I think it's rather irrelevant and cannot imagine anyone not understanding, at least from context, what those sentences mean. We can change it or not change it and I do not mind either way.
