### ISSUE TITLE
Text at images going outside of boxes

### ISSUE THREAD

**Issue by r-gaia-cs** [swcarpentry/git-novice#87]
At some images part of the text is outside of the box.

![s](https://cloud.githubusercontent.com/assets/1506457/6966889/6579f82c-d932-11e4-97af-6c0465ebc6a7.jpg)

This is bugging me for a long time.

First I thought that this is a font problem but I check the font and I didn't get any warning. Because of it I report a bug to LibreOffice developers, https://bugs.documentfoundation.org/show_bug.cgi?id=90414, and will be grateful if someone with more experience using LibreOffice than me could help solving this.

**Comment by daisieh** [comment]
It looks fine in my browser: I'm not sure how to deal with a problem that is dependent on browser-specific rendering of SVG files.

**Comment by r-gaia-cs** [comment]
> It looks fine in my browser

Thanks for the feedback.

> I'm not sure how to deal with a problem that is dependent on browser-specific rendering of SVG files.

I don't believe this is web browser-specific since this happen with all the web browsers that I have installed (Firefox, Chromium and Epiphany). This can be something related with my machine that has unusual configuration.

@wking Do you have this problem?

@daisieh I'm OK to have this closed or not included to 5.3.

**Comment by daisieh** [comment]
How does SVG choose to render text? On my machine, I see sans-serif text, which fits fine in the image.
![screen shot 2015-04-16 at 8 48 21 pm](https://cloud.githubusercontent.com/assets/1827728/7195747/f83b8c96-e479-11e4-8911-92f6938799ed.png)

**Comment by iglpdc** [comment]
Don't your two screenshots look the same, but for the font type? @r-gaia-cs, which is the text you see outside the box in your screenshot?

**Comment by iglpdc** [comment]
Oh, sorry, I see know.

**Comment by iglpdc** [comment]
@r-gaia-cs, should I close this after #97 and maybe #102?
