### ISSUE TITLE
Replace dracula & wolfman image

### ISSUE THREAD

**Issue by tobyhodges** [swcarpentry/git-novice#870]
A discussion on [The Carpentries Slack workspace](https://carpentries.org/connect/#slack) made me aware that we may not have permission to re-use [the "Dracula & Wolfman" image from DeviantArt](https://www.deviantart.com/b-maze/art/Werewolf-vs-Dracula-124893530) that forms part of the narrative illustration in [`03-create`](https://swcarpentry.github.io/git-novice/03-create/index.html). There is no indication on the DeviantArt page that the image has been licensed for re-use, and (unless someone can correct me e.g. by pointing to where we received permission to use the image) I believe we should remove the the illustration from the lesson, perhaps opening another issue to request help from someone willing to create a new illustration to replace it.

**Comment by jrfep** [comment]
Hi @tobyhodges, that's a good question, probably the permission was granted to some of the original contributors of the lesson and the information is hidden somewhere. I cannot find any explicit documentation in the repo about the external copyright of the images used in the lessons other than the attributions below the images themselves. 

For example, there are two conditions to get permission to reuse the comic in [`01-basic`](https://swcarpentry.github.io/git-novice/01-basics/index.html) according to the [instructions here](https://phdcomics.com/about.php): to send an e-mail request and to add a text next to the image. It appears that the second condition is met in the text, and I would assume someone did send the e-mail with the request, but again, I don't see that information in the repo. 

Not sure if this is something that can be added to the LICENSE file, or if it could be added to a README file in the directory containing the figures.

**Comment by maccxs** [comment]
Dear all, I am not a designer, but here would be my first step towards replacing the image. All parts 
freely available under the [Pixabay license](https://pixabay.com/de/service/license/) and modified by myself. I'd happily discuss any modifications or share the gimp xcf-file with you.
![universal_missions_hintegrund](https://user-images.githubusercontent.com/49159623/208888405-431079e7-cede-4bf9-ab4a-81b542e4b5aa.png)

- Mars from [OpenClipart-Vectors](https://pixabay.com/de/users/openclipart-vectors-30363/?utm_source=link-attribution&utm_medium=referral&utm_campaign=image&utm_content=1298905) at [Pixabay](https://pixabay.com/de//?utm_source=link-attribution&utm_medium=referral&utm_campaign=image&utm_content=1298905) 
- Pluto from [Eugene](https://pixabay.com/de/users/vollex-1236651/?utm_source=link-attribution&utm_medium=referral&utm_campaign=image&utm_content=2201446) at [Pixabay](https://pixabay.com/de//?utm_source=link-attribution&utm_medium=referral&utm_campaign=image&utm_content=2201446)
- Mummy from [OpenClipart-Vectors](https://pixabay.com/de/users/openclipart-vectors-30363/?utm_source=link-attribution&utm_medium=referral&utm_campaign=image&utm_content=148976) at [Pixabay](https://pixabay.com/de//?utm_source=link-attribution&utm_medium=referral&utm_campaign=image&utm_content=148976)
- Base image from [4558954](https://pixabay.com/de/users/4558954-4558954/?utm_source=link-attribution&utm_medium=referral&utm_campaign=image&utm_content=3710569) at [Pixabay](https://pixabay.com/de//?utm_source=link-attribution&utm_medium=referral&utm_campaign=image&utm_content=3710569)

**Comment by martinosorb** [comment]
See also #277 though. It might be a good excuse to take that decision

**Comment by tobyhodges** [comment]
Related to this issue and #277: the Software Carpentry Curriculum Advisory Committee is also discussing the narrative for this lesson - see https://github.com/swcarpentry/curriculum-advisors/issues/5
