### ISSUE TITLE
Add link to "how to undo" decision tree

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/git-novice#88]
https://twitter.com/emmajanehw/status/549919920990208000

**Comment by wking** [comment]
On Fri, Apr 03, 2015 at 04:23:51AM -0700, Greg Wilson wrote:
> https://twitter.com/emmajanehw/status/549919920990208000

Along these lines, there's also [1], which has a slideshow going into
more detail on the motivation behind the final flowchart.

[1]: http://justinhileman.info/article/git-pretty/

**Comment by iglpdc** [comment]
> https://twitter.com/emmajanehw/status/549919920990208000

The full-sized version is here https://raw.githubusercontent.com/emmajane/gitforteams/master/resources/workflow-undoing-changes.png

**Comment by daisieh** [comment]
@iglpdc: I think that this is a nice idea but we should push this to the next version. What do you think?

**Comment by iglpdc** [comment]
@daisieh, maybe... Let's not mark it as a 5.3 milestone, and but someone wants to do it, we'll take it :-)

**Comment by iglpdc** [comment]
Closing in favor of #212 (see the comments there).
