### ISSUE TITLE
Flesh out 'Key Point' in 'Ignoring Things' lesson with context

### ISSUE THREAD

**Issue by sadielbartholomew** [swcarpentry/git-novice#887]
The [lone 'Key Point' in the 'Ignoring Things' lesson](https://swcarpentry.github.io/git-novice/06-ignore/index.html#key-points), namely:

> **Key Points**
> The .gitignore file tells Git what files to ignore.

seems rather self-evident and lacks context regarding the sense in which git 'ignores' the files. I light of this, I think a few extra words to clarify this would be both important and useful, especially since key points are intended to summarise material and may well be revised independently of the lesson itself. Something along the lines of the following three ideas would work well, I think, but a similar clarification would also be sufficient here:

* The .gitignore file tells Git what files to ignore *when tracking the repository*.
* The .gitignore file tells Git what files to ignore *for tracking purposes*.
* The .gitignore file tells Git what files to ignore *for [/under] version control*.

(The ending to the first idea could precede the third, or similar, too.)

**Comment by jrfep** [comment]
Hi @sadielbartholomew I would suggest adding two key points:

- The .gitignore file is a text file that gives specific instructions to Git about tracking files in the repository.
- You can specify which files or folders to ignore, or to include files that would otherwise be ignored

**Comment by sadielbartholomew** [comment]
Thanks @jrfep, your idea sounds good to me, being even more detailed and clear. Shall I open a PR to add those lines into the lesson Key Point section? I don't mind if somebody else does the PR, either, though I am very happy to do it myself.
