### ISSUE TITLE
Episode on Tracking Changes shows 0 min exercises but there are some

### ISSUE THREAD

**Issue by aghr** [swcarpentry/git-novice#897]
Dear all,

The summary at the top of the episode on Tracking Changes shows 0 min exercises although this episode contains some exercises at the end. Not sure if this is intended or a mistake.

**Comment by bencomp** [comment]
I noticed this too, on multiple episodes. My guess was that any exercises have to be chosen by the instructor(s).

**Comment by martinosorb** [comment]
Closing as superseded by #955.
