### ISSUE TITLE
Replace .dat file-ending with similar sensible ending

### ISSUE THREAD

**Issue by fiveop** [swcarpentry/git-novice#903]
The material uses files that end in `.dat`, spoken “dot dat”. With unclear pronunciation or with bad acoustics this can be misheard as “dot dot” at some point and properly understood at another, which can then lead to confusion: Files are ending in `.dot` but .gitignore contains `*.dat`. (Based on recent experience.)

We could replace the file ending `.dat` with something distinct and recognizable, for example `.csv`, throughout the material.

**Comment by kekoziar** [comment]
Changing it to `.csv`  sounds like a good idea.  Especially since `.dat` is often a data file that program developers will encounter, but not researchers (who are more likely to attend these lessons).

Feel free to submit a PR.
