### ISSUE TITLE
`working directory` has been renamed to `working tree`

### ISSUE THREAD

**Issue by lexnederbragt** [swcarpentry/git-novice#905]
Previously, `git status` resulted  in

```
# On branch main
nothing to commit, working directory clean
```

More recent git versions have this:

```
On branch main
nothing to commit, working tree clean
```

I have not been able to track the version where this changed, but it was somewhere between 1.X and 2.0 or 2.0 and 2.X.

The outputs in lesson should perhaps be updated with this change with a notification about older git versions.

**Comment by benjwolff** [comment]
Hi Lex,

yes, you are right. The change happened in git v2.9.1 ([see release notes for git v2.9.1](https://raw.githubusercontent.com/git/git/master/Documentation/RelNotes/2.9.1.txt)).
I agree with your suggestion. The output of ```git status``` should be adapted to the actual version. Also we should include a hint, that the output in older versions (< 2.9.1) can differ.

**Comment by benjwolff** [comment]
I created a new MR (#906) which applies the suggested change. I did not add a hint, that the output can differ in older versions. I think this information will not be helpful and confuse the reader.
