### ISSUE TITLE
create repository from bash

### ISSUE THREAD

**Issue by joh4nd** [swcarpentry/git-novice#917]
Hi, I considered linking to [`gh`](https://cli.github.com/manual/gh_repo_create) command line tool (and perhaps [installation](https://github.com/cli/cli#installation)) in the [Remotes in GitHub episode](https://swcarpentry.github.io/git-novice/07-github/index.html). Let me know.

**Comment by shelllbw** [comment]
I feel that it's a bit more advanced topic though the tool is powerful and I am also using it. The focus of the Git lesson is to provide a foundation in using Git for version control, collaborating on projects, and managing repositories effectively. Personally, I think introducing the `gh` may add an additional layer of complexity and could divert the attention away from the core concepts being taught. Participants might find it overwhelming, especially if they are new to Git.

**Comment by kekoziar** [comment]
Also, consider that the lesson focuses on git, and `gh` is specifically a GitHub command.  The lesson uses GitHub to model remotes because it's convenient; not because we're teaching GitHub.  When at all possible, we try to avoid commands and content that is only or primarily available on GitHub.

**Comment by joh4nd** [comment]
Right, fair enough. The idea was just to make pushing repositories from the desktop to github a bit easier.
