### ISSUE TITLE
Multi-factor authentication will be required by GitHub by the end of 2023

### ISSUE THREAD

**Issue by tobyhodges** [swcarpentry/git-novice#922]
[GitHub recently announced that it will enforce a requirement for two-factor authentication by the end of 2023](https://github.blog/2022-05-04-software-security-starts-with-the-developer-securing-developer-accounts-with-2fa/).

This will affect Learners and Instructors using this lesson and, much like the combined approach taken towards updating lessons to reflect the loss of password-based GitHub access, it would probably be a good idea for us to take a coordinated approach to addressing this on the Software Carpentry and Library Carpentry lessons. 

cc @swcarpentry/curriculum-advisors

**Comment by kekoziar** [comment]
Thanks for the update, @tobyhodges.
