### ISSUE TITLE
SSH Supplementary episode

### ISSUE THREAD

**Issue by longr** [swcarpentry/git-novice#923]
The "Remotes in GitHub" episode has a tip box making reference to a supplementary episode about Advanced SSH,  I cannot see this, I can only see one for R.  Has the episode been dropped?

**Comment by kekoziar** [comment]
@longr  the episode is still in development on the [ssh-adv branch](https://github.com/swcarpentry/git-novice/blob/ssh-adv/_episodes/15-supplemental-ssh.md).  Feel free to contribute to it so we can merge it to the main lesson when it's finished.

**Comment by kekoziar** [comment]
I'm closing this as a duplicate.
