### ISSUE TITLE
Links need to be fixed in CONTRIBUTING.md

### ISSUE THREAD

**Issue by tobyhodges** [swcarpentry/git-novice#925]
The Contributing Guide, `CONTRIBUTING.md`, contains two links with URLs that should be updated:

1. the _How to Contribute to an Open Source Project on GitHub_ link leads to a 404 and should be updated to link to https://egghead.io/courses/how-to-contribute-to-an-open-source-project-on-github
2. the `[repo]` link reference currently points to a placeholder URL (https://example.com/FIXME) and should be updated to point to the source repository for the lesson (i.e. this GitHub repository).

The Contributing Guide is one of the files that is unique to each repository - to allow for individual lesson projects to define their own guidance for contributors - so unfortunately this is not an issue that can be fixed centrally e.g. by updating the template files in the lesson infrastructure. Instead the file must be updated in the individual lesson repositories themselves.

**Comment by CYBWEBALI** [comment]
Hey, I can work on this issue.

**Comment by CYBWEBALI** [comment]
Assign this issue to me.

**Comment by kekoziar** [comment]
> Assign this issue to me.

@CYBWEBALI feel free to submit a PR for this.

**Comment by CYBWEBALI** [comment]
Done. PR #926

**Comment by kekoziar** [comment]
@CYBWEBALI Thank you for contributing!
