### ISSUE TITLE
Lesson 14: broken internal link to git setup instructions

### ISSUE THREAD

**Issue by bgoli** [swcarpentry/git-novice#938]
---
This regards the link Lesson 14: https://github.com/swcarpentry/git-novice/blob/main/episodes/14-supplemental-rstudio.md

in the section titled: 
`### Find your Git Executable`

there is a dead link [Git installation instructions](https://swcarpentry.github.io/git-novice/setup.html): 

`[Git installation instructions](https://swcarpentry.github.io/git-novice/setup.html)`

which could now be replaced with the general: [Git installation instructions](https://swcarpentry.github.io/git-novice/#installing-git)

`[Git installation instructions](https://swcarpentry.github.io/git-novice/#installing-git)`

---

**Comment by kekoziar** [comment]
Thanks for catching this.  Feel free to submit a PR with the correction.
