### ISSUE TITLE
A second point is introduced without a first point

### ISSUE THREAD

**Issue by maneesha** [swcarpentry/git-novice#946]
### What is the problem?

The [Hosting episode](https://swcarpentry.github.io/git-novice/13-hosting.html) begins with "The second big question for groups..." but does not follow what the first big question might be.  

### Location of problem (optional)

https://swcarpentry.github.io/git-novice/13-hosting.html

**Comment by kekoziar** [comment]
I'm fairly certain the first big question is what license to use.  Feel free to suggest text to avoid confusion.

**Comment by maneesha** [comment]
I don't see any way to know that would be the first big question, as there is no connection here to that section.  I don't have specific suggestions -- I would leave it up to the lesson maintainers/developers or people who use this curriculum regularly to decide how to connect this second question to what the first big question is.
