### ISSUE TITLE
Suggest flipping order of git clone screenshots 

### ISSUE THREAD

**Issue by maneesha** [swcarpentry/git-novice#953]
### How could the content be improved?

In the [Connect to remote repo](https://swcarpentry.github.io/git-novice/aio.html#connect-local-to-remote-repository)  we have two steps - first to set to ssh instead of https, and then to copy the address.  

However, the first screenshot shows the mouse pointer on the 'copy' function and the second shows selecting ssh.  It would make more sense for these screenshots to be reversed, so the one selecting ssh comes first and the one selecting 'copy' is second.  

### Which part of the content does your suggestion apply to?

https://swcarpentry.github.io/git-novice/aio.html#connect-local-to-remote-repository

**Comment by martinosorb** [comment]
Thank you maneesha. I agree it seems they were involuntarily swapped. I fixed it on branch.
