### ISSUE TITLE
Note that there is no response when typing password/pass phrase/etc in your terminal

### ISSUE THREAD

**Issue by maneesha** [swcarpentry/git-novice#956]
### How could the content be improved?

In the [part of the git lesson about setting up an ssh key](https://swcarpentry.github.io/git-novice/07-github.html#create-an-ssh-key-pair) we should note that when typing in passwords in terminal, there is no feedback (ie your cursor doesn't move, you don't see your display changing, etc.).  We had several learners in a workshop today who thought their computer had frozen and was being non-responsive.

### Which part of the content does your suggestion apply to?

https://swcarpentry.github.io/git-novice/07-github.html#create-an-ssh-key-pair

**Comment by peterjc** [comment]
Yes, that was raised by multiple people in the workshop I was teaching on today.
