### ISSUE TITLE
"AFK" may not be a recognizable term to everyone

### ISSUE THREAD

**Issue by maneesha** [swcarpentry/git-novice#957]
### How could the content be improved?

In the [typical work session](https://swcarpentry.github.io/git-novice/09-conflict.html#a-typical-work-session) exercise, the last step is to "celebrate" with "AFK."
I am assuming this means "away from keyboard" but everyone may not know this, especially because  everything else in that exercise is an actual shell/git command and it may cause confusion to think that "AFK" may also be a command they should know.

### Which part of the content does your suggestion apply to?

https://swcarpentry.github.io/git-novice/09-conflict.html#a-typical-work-session

**Comment by martinosorb** [comment]
Thanks maneesha. I would not have known what AFK meant myself. I think we should remove it altogether.
