### ISSUE TITLE
Commits from #66 seem lost

### ISSUE THREAD

**Issue by iglpdc** [swcarpentry/git-novice#96]
I'll take a lot tomorrow, but I think we accidentally removed/reverted some merged commits.

**Comment by daisieh** [comment]
The 01-backup edit got lost in the split of the files: they need to be placed into 02-create.
The instructors edit got lost in this commit: https://github.com/swcarpentry/git-novice/commit/eb5160d3f325d7ed1f5e679f14f6b123eb3aa12b#diff-f93309feecc5f30e1e60ad085e650818

**Comment by iglpdc** [comment]
Fixed by #125.
