### ISSUE TITLE
Add note about how rm from command line is irrecoverable

### ISSUE THREAD

**Issue by maneesha** [swcarpentry/git-novice#965]
### How could the content be improved?

In the [section about removing the `.git` file](https://swcarpentry.github.io/git-novice/03-create.html#correcting-git-init-mistakes) if we accidentally did a `git init`, there is a note to use with caution.  In emphasizing that caution, consider adding a line about how the `rm` command is irrecoverable -- items do not end up in your trash/recycle bin but are gone forever.  

### Which part of the content does your suggestion apply to?

https://swcarpentry.github.io/git-novice/03-create.html#correcting-git-init-mistakes

**Comment by a-smith-github** [comment]
I agree with this suggestion. The information could be beneficial to students who haven't spent much time using shell commands yet and, hopefully, with little additional overhead for maintainers and doesn't bloat the content too much (this doesn't introduce a new idea). 

Perhaps taking

> Running this command in the wrong directory will remove the entire Git history of a project you might want to keep. 

And afterwards inserting 

> This change cannot be undone.
 
is sufficient? Alternatively,

> This cannot be reversed.

**Comment by martinosorb** [comment]
See #992.
