### ISSUE TITLE
Maintainer mismatch with website

### ISSUE THREAD

**Issue by martinosorb** [swcarpentry/git-novice#975]
### What is the problem?

Hi all, the [software carpentry website](https://software-carpentry.org/lessons/index.html) lists Scott Gruber (@scottgruber) as a maintainer of this lesson, but this is not listed in the README.md file on this repo. Could you please clarify which version is correct?
Thanks - Martino from the software carpentry governance committee

### Location of problem (optional)

README.md

**Comment by ErinBecker** [comment]
Thanks for raising this issue @martinosorb. Fixed with https://github.com/swcarpentry/website/pull/1265.

**Comment by martinosorb** [comment]
Hi Erin, thanks for doing this. This issue was referencing the Readme of this repo, which is not updated. I will now update it to reflect the actual names as on the website, since these are recognized by the core team. Thanks.

**Comment by ErinBecker** [comment]
Ah, thanks for clarifying @martinosorb!
