### ISSUE TITLE
Do not mention branches while creating the first repository?

### ISSUE THREAD

**Issue by alpkaanaksu** [swcarpentry/git-novice#983]
### How could the content be improved?

The setup episode includes configuring the git environment and setting the deafult branch to 'main'. The lesson for creating the first repository uses `git checkout -b main` again, to make sure that we are in the 'main' branch.

This might not be necessary since we already do the configuration step in the previous episode. This forces us to talk about branches prematurely in a context where we want to focus on creating new repositories and the `.git` directory. This might confuse some learners. If we mention branches, we also need more time to explain them, which would shift the focus of this episode. 

### Which part of the content does your suggestion apply to?

https://swcarpentry.github.io/git-novice/03-create.html

**Comment by martinosorb** [comment]
I think I agree with this change, provided one indeed follows the configuration step. Newly installed versions of git should anyway have main as default anyway. Would you be willing to submit a pull request for consideration @alpkaanaksu ? Thank you for your contribution.
